### ISSUE TITLE
some doc pages have unformatted headers

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#1]
See http://docs-v2.readthedocs.org/en/latest/installing-deis/digitalocean/

<img width="1440" alt="screen shot 2016-02-23 at 10 54 32 am" src="https://cloud.githubusercontent.com/assets/1360539/13262865/eeb808aa-da1b-11e5-9b47-b5cace4961a0.png">

**Comment by mboersma** [comment]
That particular URL seems to have gone extinct. Is this still a problem in the Workflow docs @bacongobbler?

**Comment by bacongobbler** [comment]
Yes. It still seems like an issue in http://docs-v2.readthedocs.org/en/latest/installing-workflow/quickstart/ (and everywhere else).

**Comment by bacongobbler** [comment]
I think MkDocs is handled differently on readthedocs. Looking at the source it seems like that nav bar is injected into the document by RTD, so we'll have to style around it.

**Comment by bacongobbler** [comment]
closed via #243
