### ISSUE TITLE
Ensure getting started docs will point to install workflow-beta1

### ISSUE THREAD

**Issue by arschles** [deis/workflow#106]
Ref https://github.com/deis/deis/issues/4962

Depends on https://github.com/deis/charts/issues/167

**Comment by lazydino** [comment]
So the doc site is not good? I tried "helm fetch deis/workflow-beta1 ", and it complains 'Chart workflow-beta1 not found...."

**Comment by arschles** [comment]
Thanks for asking @lazydino. These docs are a bit ahead of where we are right now. We haven't yet officially released the beta, so that chart isn't available right now. We'll publish a blog post when it _is_ published however. Sorry for the confusion!

**Comment by lazydino** [comment]
So how should I proceed with installation of workflow? I can skip fetching chart, generating secrets? Don't I need to do 'helm install workflow'? Please advise.

**Comment by arschles** [comment]
Currently, there are two choices, and both should be considered pre-beta as of this writing. See the below list for descriptions.

- `deis/workflow-dev` is a 'canary' build of Workflow. The images referenced in this chart are the most up-to-date and will change frequently. These images get published only when they have passed our [end-to-end test suite](https://github.com/deis/workflow-e2e) (which is a work in progress, FYI), but they have not been fully vetted and do not represent an official release
- `deis/workflow-beta1-test` is a chart that we have used for pre-beta testing. It will not be changing over time, but will likely be removed after we officially release our beta

I hope this helps @lazydino. Please let me know if you have further questions.

**Comment by arschles** [comment]
@lazydino we just cut the `deis/workflow-beta1

**Comment by lazydino** [comment]
Hi,

Thank you. It worked, I got the same screen dump as you posted.

Reggie.
