### ISSUE TITLE
Section headings no longer have anchors

### ISSUE THREAD

**Issue by carmstrong** [deis/workflow#122]
You used to be able to send people links to a specific section, such as http://docs.deis.io/en/latest/troubleshooting_deis/#troubleshooting-etcd

**Comment by bacongobbler** [comment]
I know @krancour has been getting around this by using raw HTML in the docs. For example `## <a name="logger"></a>Logger: fluentd, logger` at https://github.com/deis/workflow/blob/master/src/understanding-workflow/components.md

**Comment by krancour** [comment]
Ya... Markdown allows you to drop to HTML for certain things... explicitly adding anchors to section headings is one of them.  But I've done that in cases where I needed to link from one place in the document to another... i.e. in cases where I needed to know (or control) what the anchor's name was.

I think in the general case, however, that we used to get anchors automatically generated for all section headings.  We could mouseover a section heading to make a little icon appear that you could click to take you directly to that section... which meant you could then copy the URL, including the anchor, from the address bar.  This isn't happening anymore... and I would presume it's a function of the change in how docs are generated.  i.e. Maybe mkdocs doesn't do this for us?

**Comment by carmstrong** [comment]
> I think in the general case, however, that we used to get anchors automatically generated for all section headings.

:+1: I'd love to see this as an automatic thing, as it once was.

> Maybe mkdocs doesn't do this for us?

Pretty sure we were using mkdocs in v1, too, no?

**Comment by bacongobbler** [comment]
@carmstrong we were still using sphinx in v1: https://github.com/deis/deis/blob/master/docs/conf.py

**Comment by carmstrong** [comment]
> we were still using sphinx in v1

Ah, okay.

**Comment by krancour** [comment]
@bacongobbler I don't know mkdocs well.  Do you know if this is something it can do if enabled/configured correctly?

**Comment by bacongobbler** [comment]
This is still currently something that is yet to be implemented. See https://github.com/mkdocs/mkdocs/issues/248

**Comment by bacongobbler** [comment]
Actually, if we just enable the [HeaderID](https://pythonhosted.org/Markdown/extensions/header_id.html) extension we should get exactly what we're looking for. This can be easily plugged in. See https://github.com/deis/workflow/blob/master/mkdocs.yml#L68 and https://github.com/deis/workflow/blob/master/requirements.txt#L2 for an example on how we add custom extensions to mkdocs.
