### ISSUE TITLE
'-a' flag produces different output than '-a='

### ISSUE THREAD

**Issue by arschles** [deis/workflow#127]
for example, when listing configs:

```console
ENG000656:workflow aaronschlesinger$ deis config:list -a test1
=== test1 Config
A        B
FOO      1
ONE      1
ENG000656:workflow aaronschlesinger$ deis config:list -a=test1
=== =test1 Config
```
The former and the latter should produce the same output, or one should error.

**Comment by Joshua-Anderson** [comment]
@arschles `-a` is supposed to be the short form of `--app=`.  So the usage would be `-a example` or `--app=example`.

It's the expected behavior, but it is a little confusing.

**Comment by arschles** [comment]
@Joshua-Anderson yea, I assumed the same. It's the confusing part that concerns me. It's very easy for a user to accidentally type `-a=...`, forgetting that they should type `--app=`.

**Comment by Joshua-Anderson** [comment]
The client uses docopt for flag parsing, which means in order to support the `-a=<app>` syntax we would also have to edit the help text of all the commands.

So the help text line:
```
Options:
  -a --app=<app>
    the uniquely identifiable name for the application.
```

Would have to become:
``` diff
Options:
+ -a -a=<app> --app=<app>
    the uniquely identifiable name for the application.
```

Is the current behavior of using `-a=<app>`  right now confusing enough to justify adding explicit support for it?

**Comment by arschles** [comment]
>Is the current behavior of using -a=<app> right now confusing enough to justify adding explicit support for it?

No, but my $0.2 is that the current behavior is confusing enough to justify returning an error or otherwise indicating that the flag is being used incorrectly.

**Comment by krancour** [comment]
My $0.02... this isn't so confusing... it seems pretty ubiquitous that equal signs don't follow short flags.

**Comment by arschles** [comment]
Replaced by deis/workflow-cli#22
