### ISSUE TITLE
Make workflow docs point to the workflow-beta3 chart

### ISSUE THREAD

**Issue by arschles** [deis/workflow#129]
Currently, some docs (such as [object storage](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md)) point to https://github.com/deis/charts/tree/master/workflow-dev, but they should probably point to https://github.com/deis/charts/tree/master/workflow-beta1

**Comment by arschles** [comment]
Currently it looks like docs point to `workflow-beta2

**Comment by arschles** [comment]
Scratch that, #159 fixes this one. Creating a new issue to update docs

**Comment by bacongobbler** [comment]
I'm gonna tackle this once beta3 has been released.
