### ISSUE TITLE
Set env vars in rc or pod manifest

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#13]
Instead of doing a programmatic `docker build` to add on last-mile environment variables, the k8s.py scheduler code could instead add them to the configuration / manifest it creates. `docker.sock` would still be necessary to pull images and push them to deis-registry, but this could be simpler and more efficient for the last-mile layer.

**Comment by bacongobbler** [comment]
We considered this but thought of it as a security concern at one point, but I'm not sure why. It doesn't matter where we store that metadata internally in the cluster, just as long as it *stays* internal. I'm +1 on this idea, since it will dramatically simplify the "magic" behind the scenes.

**Comment by helgi** [comment]
Would be fine with just dumping it all into `env` for now and then later we can look into combining `secrets` into it somehow? There is a GH issue on k8s to expose `secrets` as `env` but it's still in the works. We could do a little scripty injection to achieve that if we wanted to support that adhoc.

Thinking `deis config:set hello=secret --secret` kind of dealio and it would know what to do it it correctly

Would spin that off into a separate ticket

**Comment by bacongobbler** [comment]
yes, I think that's fine for now.

**Comment by helgi** [comment]
https://github.com/kubernetes/kubernetes/issues/4710 is the ticket I was referring to upstream

**Comment by helgi** [comment]
Looks like we are already seeding ENV Vars into k8s RC templates (the pod portion of them). Happened as part of another ticket. That work also specifically added `DEIS_APP` and `DEIS_RELEASE`.

I did a PR that drops those parts (needs proper testing)

**Comment by helgi** [comment]
Created a new ticket, #347, to deal with the secret portion
