### ISSUE TITLE
containerize the test environment

### ISSUE THREAD

**Issue by arschles** [deis/workflow#139]
It should extend [`quay.io/deis/go-dev:0.3.0`](https://quay.io/deis/go-dev) and also include [`ginkgo`](github.com/onsi/ginkgo/ginkgo) and [`gomega`](github.com/onsi/gomega). An alternative is to include those two binaries inside of that image.

Currently the [Makefile](https://github.com/deis/workflow/blob/master/_tests/Makefile) calls `go get ...` on each run.

**Comment by krancour** [comment]
With deis/docker-go-dev#8 merged and deis/workflow-e2e#1 opened, I think this issue can be closed here.

**Comment by arschles** [comment]
@krancour reopening, as the go-dev image has ginkgo in it, but the makefile in `_tests/` doesn't use it yet
