### ISSUE TITLE
Better logic for differentiating apps

### ISSUE THREAD

**Issue by smothiki** [deis/workflow#141]
The current logic assumes all procfile type apps are web and dockerfile type apps are web.
We have a way to identify whether an app has dockerfile or not. Need to pass this as an extra argument while creating an RC. So that users can create Procfile or Dockerfile type apps of any type.

**Comment by arschles** [comment]
@smothiki I suggested the below in #258. I think it removes all ambiguity between dockerfile and buildpack apps.

- for buildpack builds, builder sends `quay.io/deis/slugrunner` as the image, and the URL of the slug as another param
- for dockerfile builds (not yet implemented), builder sends the URL of the image (which would be in the internal registry) and no URL for the slug (since it's N/A). It would no longer send "dockerfile": true

**Comment by smothiki** [comment]
I was thinking the same. But Embedding images and envs into a singel template is more maintenance than choosing two different templates. I'm thinking of having single RC template and two container templates which make life easier

**Comment by helgi** [comment]
I'm waiting for a k8s PR to land (and get released) that separate the Pod Template from RC. That'd help here in the future :)

**Comment by smothiki** [comment]
there is not requirement for a separate POD template as only containers are being changed

**Comment by arschles** [comment]
that's fine. my suggestion was only about the API (which, to my knowledge, is only used by builder). to illustrate, here's a prototype of the request that workflow could take for a buildpack app:

```json
{
  "sha": "abc....",
  "receive_user": "arschles",
  "receive_repo": "myapp",
  "app": {
    "type": "buildpack",
    "procfile": {
      "web": "example_go"
    }
  }
}
```

and here's a prototype for a dockerfile app:

```json
{
  "sha": "abc....",
  "receive_user": "arschles",
  "receive_repo": "myapp",
  "app": {
    "type": "dockerfile",
    "image": "quay.io/somerepo/someimage:sometag"
  }
}
```

**Comment by smothiki** [comment]
As of now builder sends whether an apptype is dockerfile or not. If we can define App type we have to change the  workflow release model which is a good start and builder can send directly the container JSON object which can be embedded directly into the RC template .

**Comment by smothiki** [comment]
The above mentioned model will simplify k8s scheduler code alot in choosing type of apps. Having builder send the templated container object to workflow makes k8s scheduler code agnostic of app type.

**Comment by arschles** [comment]
what do you mean by "templated container object"

**Comment by smothiki** [comment]
Apologies the above described theory is not possible as builder has no idea about releases from workflow. Please ignore

**Comment by arschles** [comment]
no problem. will do
