### ISSUE TITLE
should the manifests include the namespace?

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow#143]
So the deis chart puts all the components in the deis namespace. But when you are hacking on 1 component and want to have a full cluster these components wont be installed in the deis namespace. 

It seems like the dev experience should mimic the actual experience as close as possible.

**Comment by krancour** [comment]
There have been a lot of discussions about this.  Afaik, we're mostly sticking to what I have proposed... that manifests in individual repos should be close enough to the manifests in the charts that you can hack on a compoment and using the manifests that come with it, easily use that component as a drop in replacement for the released one installed by some chart.

**Comment by krancour** [comment]
Which would mean using the deis namespace.

**Comment by jchauncey** [comment]
That means they should be name spaced
