### ISSUE TITLE
Can't deis register

### ISSUE THREAD

**Issue by pfeodrippe** [deis/workflow#147]
I'm using v2, created a cluster in aws following the docs (kubernetes) and trying to deis register, it's saying 

Registration failed: Error:
401 Unauthorized
Unauthorized

Why can't I create a new user?

**Comment by bacongobbler** [comment]
Closing as it seems you figured it out thanks to @jchauncey's help in https://github.com/deis/controller/issues/405#issuecomment-207897793. :)
