### ISSUE TITLE
docs: Fix installation instructions to _not_ use `kubectl edit`

### ISSUE THREAD

**Issue by technosophos** [deis/workflow#149]
We should not be recommending `kubectl edit` for two big reasons:

1. It does not work with all editors. With `vi` on Mac it silently fails OOTB.
2. If you do it, your remote state differs from your local charts, and every time you update you have to re-set that value or else routing breaks.

The correct method is to edit the chart in the workspace and use `kubectl apply` to load it back in.

Options for editing are:

- Use `helm edit`, though only the newest version of Helm works well
- Edit `$(helm home)/workspace/charts/deis/manifest/deis-router-rc.yaml`. This is what the first version said, but somebody removed this and I don't know why.

**Comment by krancour** [comment]
I was the one who changed this, albeit not so deliberately, when I last updated these docs... it did have two lgtms.  Sorry.

I understand editing locally is a better approach and the docs changes I made DO recomend it.  They just don't go into detail on HOW.  Not going into detail on that and mentioning `kubectl edit` as an alternative are both a response to what feels like a problem with helm...

When I `helm up` and `helm fetch deis/deis`, my local changes all get lost anyway... which seems to make it no better than `kubectl edit`.

Sorry... I wasn't trying to force a certain opinionated way of doing things on anyone.  I was trying to avoid overly documenting the helm workflow in Deis docs while, it seems to me, that the helm workflow is still emerging and being refined.
