### ISSUE TITLE
rewrite k8s.py app manifests as YAML

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#15]
[JSON](https://github.com/deis/workflow/blob/master/rootfs/scheduler/k8s.py#L15) is a pain, and we prefer YAML elsewhere (such as [charts](https://github.com/helm/charts)).

**Comment by rimusz** [comment]
+1

**Comment by mboersma** [comment]
Looking at this more closely, I think changing to YAML inside k8s.py would be more painful than helpful. It would necessitate installing the third-party PyYAML package and doing yaml-to-json conversions in many places just to satisfy HTTP requests, which isn't worth it just to make the three small manifest templates more readable IMHO.

I'm closing this, but please re-open it or comment if you have strong arguments for YAML in this particular context.

**Comment by bacongobbler** [comment]
Ah, I thought this was for the manifests in https://github.com/deis/workflow/tree/master/manifests, but those are already written in YAML and those are superceded by the Deis v2 chart for Helm. I agree that this is a larger pain in Python specifically for the reasons you stated above (PyYAML being one, python dicts being native to Python being another).
