### ISSUE TITLE
deis run doesn't work

### ISSUE THREAD

**Issue by smothiki** [deis/workflow#152]
run should be a job template than a pod and shoudl change according to the app type.

**Comment by helgi** [comment]
@smothiki What do we need to do here? The Job Template is out of scope unless we can guarantee k8s 1.2 being our target.

**Comment by smothiki** [comment]
I created this issue to keep track not as a part of deis v2.

**Comment by smothiki** [comment]
closing this in favor of https://github.com/deis/workflow/issues/362
