### ISSUE TITLE
deis limits doesn't work

### ISSUE THREAD

**Issue by smothiki** [deis/workflow#154]
running 3 minions with 2GB each.
```
$ deis limits:set web=2GB -a quacky-waterbed
$ deis scale web=6
Scaling processes... but first, coffee!
done in 97s
=== quacky-waterbed Processes
--- web:
web.1 up (v3)
web.2 up (v3)
web.3 up (v3)
web.4 up (v3)
web.5 up (v3)
web.6 up (v3)
```
should be able to scale 3 or revert scale operation

**Comment by bacongobbler** [comment]
I believe `deis limits` was off the table for alpha. `config` and `domains` are OK though.

**Comment by smothiki** [comment]
Yes. I was just creating issues to keep track of things
