### ISSUE TITLE
Document pods endpoint

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#156]
https://github.com/deis/controller/blob/f1ee725031cbc037b52511add9c1f356b9fa4aeb/rootfs/api/urls.py#L32-L47

ping @helgi

**Comment by helgi** [comment]
copy paste the container documentation and rename `container` to `pod`, at least in terms of the the endpoints and their params

**Comment by bacongobbler** [comment]
it looks like the `next` and `previous` pointers are gone in the view due to https://github.com/deis/controller/blob/master/rootfs/api/views.py#L322-L323, similar to the `restart` view here: https://github.com/deis/controller/blob/master/rootfs/api/views.py#L334-L336

I'l update the documentation on those.

**Comment by helgi** [comment]
Yeah, some of the responses will be different, especially because we are not talking to the DB anymore and I had to fake out some interactions (for now) so a handful of things look different.

Listing pods for sure looks different than listing containers, more data returned
