### ISSUE TITLE
deis ps shows inaccurate process status

### ISSUE THREAD

**Issue by krancour** [deis/workflow#160]
I have an application pod that is crashing:

```
[kent@mbp ~]$ k get pods --namespace=burley-autoharp
NAME                           READY     STATUS             RESTARTS   AGE
burley-autoharp-v2-web-6kilr   1/1       Running            0          2d
burley-autoharp-v2-web-fvcim   0/1       CrashLoopBackOff   7          15m
```

(Don't worry about _why_.  I made it crash.)

But `deis ps` doesn't accurately reflect this:

```
[kent@mbp ~]$ deis ps -a burley-autoharp
=== burley-autoharp Processes
--- web:
web.1 up (v2)
web.2 up (v2)
```

Apart from it being inaccurate that both are up, it's also impossible for me to know _which_ of these is wrong.  Which of those two pods is "web.1" and which is "web.2"?  There is no easy way to tell.  So I'd further propose that labeling processes in that manner (a carryover from the old fleet scheduler on v1.x) is not doing anyone any favors.

**Comment by technosophos** [comment]
Seems like we should replace the web.1/web.2 nomenclature with the actual pod names (though that's not necessary for alpha).

**Comment by krancour** [comment]
:100: :smile:

**Comment by smothiki** [comment]
Container is an object that get's created even before RC is scaled . I don't think we can show POD names in place of showing web.1 etc 
https://github.com/deis/workflow/blob/master/rootfs/api/models.py#L283-L298

**Comment by smothiki** [comment]
Regarding PS showing different status. The second POD was created 15 mins ago . While creating the POD it might have succeeded and then went to crash state. I mean I was not able to reporduce the issue, but this is my hunch for ps showing up . PS shows UP If the POD is Running after creating the POD. It doesn't give the current running status of the POD. Which we need to address.

**Comment by smothiki** [comment]
Did little more research ps:list is a DB query and doesn't give the current state of the POD https://github.com/deis/workflow/blob/master/rootfs/api/views.py#L290-L294

**Comment by technosophos** [comment]
At @smothiki's suggestion I'm dropping this off of the showstopper list, as this behavior is analogous to the existing Deis v1 behavior. But I really think we should get this fixed in Beta.

**Comment by bacongobbler** [comment]
We can easily change it to just call out to the scheduler and grab the pod names and status associated with an application. The only reason we did a dB query before was so we could find the process type and the process ID (the numerical value in `web.1`), which then we used that to find its "job name" which is an alias for the fleet unit name (`myapp_v2.web.1.service`).

**Comment by bacongobbler** [comment]
After that it was a query to fleet to get the unit status, so the process should be generally the same for kubernetes :)
