### ISSUE TITLE
Unable to ping registry

### ISSUE THREAD

**Issue by pfeodrippe** [deis/workflow#166]
I'm using the ```worflow-beta-1 ```, using a Dockerfile, when I ```git push deis master```, the output give me this

```
Step 11 : EXPOSE 3000
 ---> Running in 0c4f5db00aa0
 ---> 963f8323b121
Removing intermediate container 0c4f5db00aa0
Step 12 : CMD rails server -b 0.0.0.0
 ---> Running in 5002da3cf455
 ---> 286ac7a95043
Removing intermediate container 5002da3cf455
Successfully built 286ac7a95043
pushing to registry
{"status":"The push refers to a repository [10.0.106.212:80/indoor-yardbird] (lremote:

{"errorDetail":{"message":"unable to ping registry endpoint https://10.0.106.212:80/v0/\nv2 ping attempt failed with error: Get https://10.0.106.212:80/v2/: tls: oversized record received with length 20527\n v1 ping attempt failed with error: Get https://10.0.106.212:80/v1/_ping: tls: oversized record received with length 20527"},"error":"unable to ping registry endpoint https://10.0.106.212:80/v0/\nv2 ping attempt failed with error: Get https://10.0.106.212:80/v2/: tls: oversized record received with length 20527\n v1 ping attempt failed with error: Get https://10.0.106.212:80/v1/_ping: tls: oversized record received with lremote: 527"}

Build complete.
Launching app.
Launching...
Done, indoor-yardbird:v4 deployed to Deis

Use 'deis open' to view this application in your browser

To learn more, use 'deis help' or visit http://deis.io

To ssh://git@deis.feodrippe.co.uk:2222/indoor-yardbird.git
   e76816a..15acbd2  aws_eb -> master
```

**Comment by bacongobbler** [comment]
That error indicates that you did not add your worker nodes' private network to the insecure flag. This is because the registry is not secured with a SSL cert, so pushing and pulling images from it requires adding the --insecure-registry flag to your hosts so that they may communicate with it.

http://docs-v2.readthedocs.org/en/latest/installing-workflow/system-requirements/#docker-insecure-registry

**Comment by matthewrudy** [comment]
I get the same issue.
So, @bacongobbler, this is a change we need to make to our Kubernetes install?

**Comment by bacongobbler** [comment]
Yes. This is something we can fix in the future by installing a self-signed certificate for the registry, but for now you'll have to make the change to your kubernetes install.

**Comment by matthewrudy** [comment]
So I ended up solving this by creating my kubernetes with the command.

```
export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=us-east-1b
export KUBE_ENABLE_INSECURE_REGISTRY=true
export KUBE_AWS_INSTANCE_PREFIX=deis
export MASTER_SIZE=m3.medium
export NODE_SIZE=m3.large
export NUM_NODES=4

wget -q -O - https://get.k8s.io | bash
```

**Comment by helgi** [comment]
Sounds like this is resolved. Setting `KUBE_ENABLE_INSECURE_REGISTRY=true` in `kube-up` is the required adjustment.

Workflow 2.2 will include changes that do not require this to be done anymore, keep an eye out for that release (soon).

**Comment by matthewrudy** [comment]
Yep, we resolved the insecure registry that way.
Excited to see 2.2 though.

Especially supporting external docker repos.

Thanks!

**Comment by helgi** [comment]
@matthewrudy 2.1 has support for private (and external) registries if you don't need ECR or GCR in short live token mode, if that helps in the mean time :)
