### ISSUE TITLE
`deis tag` should add nodeSelector to pod template

### ISSUE THREAD

**Issue by technosophos** [deis/workflow#168]
I guess that our plan for `deis tag` is to have it create node selectors as documented here: http://kubernetes.io/v1.1/docs/user-guide/node-selection/README.html

**Comment by rimusz** [comment]
GKE does not really support proper nodes labelling yet, labels are gone then the node gets upgraded.
So we have to take this in to mind for `deis tag`

**Comment by krancour** [comment]
> labels are gone then the node gets upgraded

Didn't understand that part.  Does this mean it's nit a graceful degradation?

**Comment by rimusz** [comment]
automatic node upgrade on GKE is deleting the node and creating the new one

**Comment by krancour** [comment]
I think we should still do this.  The fact that one particular managed k8s offering (even if it's the premiere one) has trouble with node labeling probably shouldn't stop us.  We could note in the documentation that mileage from this feature may vary with k8s distribution.

I've experimented with labeling nodes on my kube-aws cluster and it works great.
