### ISSUE TITLE
Bad notes syntax in docs

### ISSUE THREAD

**Issue by krancour** [deis/workflow#171]
There are numerous spots in the docs where `!!!` is used for "notes."  This seems to be a carryover from sphinx and isn't valid markdown.

**Comment by bacongobbler** [comment]
It's valid Markdown when used in conjunction with [the Admonitions extension](https://pythonhosted.org/Markdown/extensions/admonition.html), which is a plugin for mkdocs.

**Comment by krancour** [comment]
Ah. Thanks for the explanation.  I'm going to close this.
