### ISSUE TITLE
Error installing deis 2 beta 2 on deis-builder RC

### ISSUE THREAD

**Issue by arkkanoid** [deis/workflow#172]
I run:

    helm fetch deis/workflow-beta2
    helm generate -x manifests workflow-beta2
    helm install workflow-beta2

Installing deisv2 beta2, I get:

    The ReplicationController "deis-builder" is invalid.
    spec.template.spec.containers[0].env[10].valueFrom: Invalid value: "": may not have more than one field specified at a time

How can I solve it?

**Comment by bacongobbler** [comment]
Which version of kubernetes are you running? I think that error occurred to me when I was using a v1.1.x cluster

**Comment by arkkanoid** [comment]
I'd kubectl on version 1.1.2. On version 1.2.0 is working now :)

**Comment by bacongobbler** [comment]
For reference I updated the documentation in #176 because we were still recommending 1.1 :)
