### ISSUE TITLE
Add documentation on how to configure Amazon Route53 for a new Deis cluster

### ISSUE THREAD

**Issue by arschles** [deis/workflow#180]
Similar to #146, we should have detailed instructions for how to configure Route53 after a Deis cluster is up and a load balancer is running in front of the routers. The docs should preferably handle load balancers that provide domains (so you'd have to create a CNAME record) and ones that provide IPs (so you'd have to create an A record.

**Comment by mboersma** [comment]
Might be worth bringing [`route53-wildcard.py`](https://github.com/deis/deis/blob/master/contrib/aws/route53-wildcard.py) forward from Deis v1, and/or writing an equivalent script to make dealing with Google's DNS easier.

**Comment by arschles** [comment]
Punting to RC1

**Comment by bacongobbler** [comment]
yes, especially since the AWS documentation [only specifies nip.io](http://docs-v2.readthedocs.io/en/latest/quickstart/provider/aws/dns/#prepare-the-hostname) at this point. Users are not going to go into prod with that setup.
