### ISSUE TITLE
Document GKE setup

### ISSUE THREAD

**Issue by krancour** [deis/workflow#182]
@arschles has suggested that we document GKE setup in our own docs since this seems, currently, to be tribal knowledge.

I know I would personally benefit from the existence of such docs.  That being said, I would question whether documenting this might implicitly throw too much weight behind one specific zero-to-k8s option...

That's not to say we shouldn't do it.  Just trying to start a discussion...

**Comment by arschles** [comment]
Agreed RE throwing too much weight. Maybe we can solve by creating a new section dedicated to outlining zero-to-k8s processes and mark it as a WIP?

**Comment by krancour** [comment]
Also something to consider, having gone through this yesterday... GCP networking is pretty complex and constraining.  See https://github.com/deis/controller/issues/657 for an example of some of the complexities that actually cannot be overcome atm.

**Comment by Joshua-Anderson** [comment]
@krancour Is this still relevant? We now have quickstart docs on GKE.

**Comment by bacongobbler** [comment]
yep, we also have internal docs on our "champagne" clusters we use for our internal apps (slackbot integrations, k8s-claimer, etc.).
