### ISSUE TITLE
Lots of docs still reference deis/deis

### ISSUE THREAD

**Issue by krancour** [deis/workflow#185]
There are many points in the documentation where references or links to the deis/deis project should be replaced either with references or links to deis/workflow _or_ (as appropriate) with language that acknowledges the existence of additional projects and repositories for individual Deis components.

Relates to #161

**Comment by bacongobbler** [comment]
I think the jury's still out if we're going to merge this back into deis/deis at some point before 2.0 so we should figure that out first :)

**Comment by krancour** [comment]
That's easy enough to fix later.  For now though, this is a "where there's smoke, there's fire" sort of thing.  References to deis/deis probably coincide with other stale bits of doc.  I've been on a doc bender, but these would be pieces that probably still need love.

**Comment by bacongobbler** [comment]
is this good to close now?

**Comment by krancour** [comment]
Let me check on this.

**Comment by krancour** [comment]
Most remaining references to deis/deis are links to specific issues.  Some of those may be relevant still and others, not so much.  Apart from that, there looks to be just a few remaining references to deis/deis.  It is the roadmap that is most in need of cleanup.

**Comment by bacongobbler** [comment]
sounds good. I found the ones you're referencing by just scrubbing with good ol' `git grep`, so I'll clean those up/

**Comment by krancour** [comment]
@bacongobbler, @technosophos has suggested that we let @slack handle the roadmap changes.  I'm going to close this and open a separate issue for that.
