### ISSUE TITLE
integration tests: move to a separate repo

### ISSUE THREAD

**Issue by arschles** [deis/workflow#190]
I consider our suite a distinct deis component, that should be managed and built separately. It should contain and produce all the normal artifacts (Dockerfile, CI config to build & push, Makefile, k8s manifests), and, since it's a Go project, should have the normal dependency management and structure as all the others.

**Comment by sgoings** [comment]
I believe @gabrtv was workin' on something of this sort...

**Comment by arschles** [comment]
ah, thanks @sgoings. I'll let @gabrtv comment here if any concrete plans

**Comment by helgi** [comment]
This is done. see github.com/deis/workflow-e2e
