### ISSUE TITLE
No docs to set up local install

### ISSUE THREAD

**Issue by featheredtoast** [deis/workflow#204]
Hey guys! New user excited to try out Deis, but I'm running into a few issues in getting set up:

The [vagrant](https://docs-v2.readthedocs.org/en/latest/installing-workflow/quickstart/#choose-a-provider) setup link `http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html` is broken.
When attempting to set up Kubernetes via Docker (the next best way to start up a local kube cluster) and installing deis workflow, it [runs into a port collision on 443 when running the API node.](https://github.com/deis/router/issues/95)

The way to move forward with evaluating Deis seems to be to just install on a cloud provider and eat a few bucks, but the docs should probably be updated to avoid the pitfall, or have a different recommendation for a local test install if possible.

**Comment by bacongobbler** [comment]
hey @featheredtoast! Thanks for pointing that the link's now broken. You can follow http://kubernetes.io/docs/getting-started-guides/binary_release/ to get started with kubernetes and vagrant.

**Comment by featheredtoast** [comment]
Awesome, thanks for the quick response!
