### ISSUE TITLE
Replicate deis componets in Kubernetes

### ISSUE THREAD

**Issue by arkkanoid** [deis/workflow#207]
Hi,
What happens if I create replicas of the Deis components? It makes Deis HA?
It would be nice in case of component or node failure.

**Comment by arschles** [comment]
@arkkanoid we don't currently support running _all_ components with more than 1 replica. For example, you can't run the database with >1 replica, but I believe you can run the router with >1 replica (@krancour: can you comment here?)

Related: deis/builder#86

**Comment by bacongobbler** [comment]
as far as I know, the router and the registry are the only ones that can be scaled. The controller and the builder relies on a file lock for an upstream issue with parallel docker pulls/pushes, and the builder also relies on a file lock to prevent a second concurrent push to happen on the same app, but those are the only technical barriers for those components. Everything else like the database, minio and the logger were designed around a single replica. That may change as these components grow, but that's the limitations AFAIK.

**Comment by bacongobbler** [comment]
running and configuring master/master databases on kubernetes *with* fault tolerance is not an easy task.

**Comment by arkkanoid** [comment]
Ok, I understand that  is complicate to create replicas in components with persistent data such as database. It will be possible to externalize the database as Deis v1?

**Comment by bacongobbler** [comment]
technically no. You just point the controller to use a postgres RDS instance; which was essentially what we did for v1.

**Comment by arkkanoid** [comment]
Fine! Thanks for the info

**Comment by bacongobbler** [comment]
for reference, here are the environment variables you need to set to point the database to RDS. A lot of these are populated by kubernetes but can be overridden in the chart manifest. https://github.com/deis/controller/blob/master/rootfs/deis/settings.py#L293-L297
