### ISSUE TITLE
rewrite docs in markdown

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#21]
We've already written the docs for helm using mkdocs and it's seeing success in both contribution and readability, so let's refactor the docs now while I'm already in the middle of re-writing half of it.

**Comment by krancour** [comment]
:+1:

**Comment by jgmize** [comment]
FYI you can automate some of that work with [pandoc](http://pandoc.org/).

**Comment by bacongobbler** [comment]
thanks. I kept giving pandoc a try but 90% of the work done by pandoc is complete gibberish, especially when we are using admonition and internal link extensions in Sphinx. pandoc cannot translate that syntax, which it then ignores and most of the work is done trying to figure out which internal links have to be ported over. Because of our reliance on some extensions like [markdown-checklist](https://github.com/FND/markdown-checklist), most of the documentation has to be hand-written. it's much easier for me to do an easy batch search-and-replace for most of the docs anyways. Good suggestion though!

**Comment by duanhongyi** [comment]
:+1:

**Comment by bacongobbler** [comment]
closed with #27.
