### ISSUE TITLE
Unexpected kubernetes node reboot running Deis

### ISSUE THREAD

**Issue by arkkanoid** [deis/workflow#210]
Hi,
I was running Deis on AWS r3.large node. Today this node has rebooted unexpectedly. 
After reboot the node has 'Not ready' status.
I've scheduled a new node and after 5 minutes it has the same 'Not ready' status.
I attach you the logs previously rebooting of the second node. 
After the restart I see:

    Failed Units: 1
    locksmithd.service

And no container is running.

Why is the machine rebooting?

    -- Logs begin at Thu 2016-04-28 18:37:01 UTC, end at Fri 2016-04-29 14:46:40 UTC. --
    Apr 29 14:37:25 ip-10-0-0-162.eu-west-1.compute.internal systemd[1]: Started docker container     e39f9fe9945e2ea236814216901956c3b5632b018be36ab58364a12308675d70.
    Apr 29 14:37:25 ip-10-0-0-162.eu-west-1.compute.internal kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev     mqueue, type mqueue)
    Apr 29 14:37:37 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:37:37.307728    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:37:52 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:37:52.302192    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:38:05 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:38:05.303116    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:38:10 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: I0429 14:38:10.851964    1214 manager.go:1748] pod "deis-controller-    bgpmr_deis(62fceda4-0e03-11e6-b941-068435e62e39)" container "deis-controller" is unhealthy
    Apr 29 14:38:17 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:38:17.306851    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:38:29 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:38:29.303075    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:38:40 ip-10-0-0-162.eu-west-1.compute.internal dockerd[1003]: time="2016-04-29T14:38:40.852744298Z" level=info msg="Container     abd8fb65712cb556db5aadb5a68dee4e4a9805389ddc840ca7a81439201e6c0e failed to exit within 30 seconds of S
    Apr 29 14:38:40 ip-10-0-0-162.eu-west-1.compute.internal systemd[1]: Stopped docker container     abd8fb65712cb556db5aadb5a68dee4e4a9805389ddc840ca7a81439201e6c0e.
    Apr 29 14:38:40 ip-10-0-0-162.eu-west-1.compute.internal systemd[1]: Started docker container     8a88f790b5a4794df71e3424021f462247b41c304a748e37d8e3e7e18f3e2837.
    Apr 29 14:38:41 ip-10-0-0-162.eu-west-1.compute.internal kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev     mqueue, type mqueue)
    Apr 29 14:38:42 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:38:42.304011    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:38:56 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:38:56.302416    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:39:08 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:39:08.302305    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:39:09 ip-10-0-0-162.eu-west-1.compute.internal systemd[1]: Started docker container     756fd1ec69e999098e153847096c6347be5c227a9616e51b2ebfa6e39d6d7429.
    Apr 29 14:39:10 ip-10-0-0-162.eu-west-1.compute.internal kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev     mqueue, type mqueue)
    Apr 29 14:39:20 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: I0429 14:39:20.853085    1214 manager.go:1748] pod "deis-controller-    bgpmr_deis(62fceda4-0e03-11e6-b941-068435e62e39)" container "deis-controller" is unhealthy
    Apr 29 14:39:22 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:39:22.305683    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    Apr 29 14:39:33 ip-10-0-0-162.eu-west-1.compute.internal kubelet-wrapper[1214]: E0429 14:39:33.322707    1214 pod_workers.go:138] Error syncing pod     62b73719-0ae0-11e6-b941-068435e62e39, skipping: failed to "StartContainer" for "rising-air
    -- Reboot --

**Comment by bacongobbler** [comment]
This looks like your issue:

> Apr 29 14:38:41 ip-10-0-0-162.eu-west-1.compute.internal kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev     mqueue, type mqueue)

I'm assuming you're using CoreOS' instructions on setting up a kubernetes AWS cluster? You might have better luck posting there on why the node is rebooting.
