### ISSUE TITLE
Failed health checks still deploy

### ISSUE THREAD

**Issue by sstarcher** [deis/workflow#214]
I created an app that without proper configuration would fail health checks.  The following steps were followed.

* Deis create app
* git push deis
* First version of app is deployed and in a crashback loop as expected
* deis config:set HEALTHCHECK_URL=/
* Second app version deployed and in a crashback loop as expected.  At this point ```kubectl get rcs --namespace=app``` shows 2 app versions are in a crashback loop
* deis config:set rest of data to make app function
* Third app version claims it has passed the health check, but the app takes several minutes to start up.  At this point the deis router routes to the app and gives a 503 even though the deis command line shows the app is good.  ```deis info``` shows version 3 of the app is up
* Third version of the app finally comes up after several minutes and the router routes correctly to the app.
* deis config:set is used to break the application configuration.  
* Fourth version of the app comes up and deis believes it has passed the health check.  Deis removes the third version of the app and now the router is back to a 503.

End result is
```
NAME                 READY     STATUS             RESTARTS   AGE
hound-v1-cmd-2fe47   0/1       CrashLoopBackOff   20         1h
hound-v2-cmd-qggwg   0/1       Error              5          33m
hound-v4-cmd-dw6u6   0/1       CrashLoopBackOff   6          9m
```

Old RCs are still hanging around and the app is down due to the third version being deleted prior to the 4th version passing health checks.

deis config:list
```
HEALTHCHECK_FAILURE_THRESHOLD      3
HEALTHCHECK_INITIAL_DELAY          1080
HEALTHCHECK_PERIOD_SECONDS         10
HEALTHCHECK_PORT                   5000
HEALTHCHECK_SUCCESS_THRESHOLD      1
HEALTHCHECK_TIMEOUT                400
HEALTHCHECK_URL                    /
```

**Comment by helgi** [comment]
This issue was moved to deis/controller#706
