### ISSUE TITLE
How to disable user registration?

### ISSUE THREAD

**Issue by StaymanHou** [deis/workflow#220]
In the doc [here](https://github.com/deis/workflow/blob/5652eeff2643387f204eff93fadc34982a97b165/src/using-workflow/registering-a-user.md) it says

> It's also possible to disable user registration after creating the superuser account.

Can we add a how-to section or a link to another doc? I did some research for a while, but I'm unable to accomplish that.

Thanks

**Comment by Joshua-Anderson** [comment]
The documentation for disabling registration still needs to be merged, but it can be read [here](https://github.com/deis/workflow/pull/139/files#diff-82b764610a43e1e8dfb5468956267e88R29).

**Comment by StaymanHou** [comment]
Gotcha. Thank you very much :+1:
