### ISSUE TITLE
client: pull core client code into a Go SDK

### ISSUE THREAD

**Issue by arschles** [deis/workflow#221]
The client should be structured as:

- A package or set of packages, that other Go projects can `import`
- A `main` package that wraps the aforementioned packages into a CLI

Note that if work in https://github.com/deis/workflow/issues/220 is done before this work, this issue should be moved into the new repo.

**Comment by technosophos** [comment]
I like this idea a lot. I could definitely see a use case for having client libraries that are easily importable.

**Comment by arschles** [comment]
Replaced by https://github.com/deis/workflow-cli/issues/18. Closing
