### ISSUE TITLE
docs: move to their own repository

### ISSUE THREAD

**Issue by arschles** [deis/workflow#222]
The docs extend beyond just the workflow repo. It makes sense for them to be independent.

**Comment by hermanjunge** [comment]
:+1:

**Comment by krancour** [comment]
I thought this initially.  I don't any longer.  Deis is clearly evolving beyond "just a PaaS."  We have a variety of workloads that are reusable in other contexts.  Documenting each independently _is_ crucial, but I would suggest that the PaaS (and that's what workflow embodies) is the hub of all that we do, with every other component being a spoke.  I think it's unavoidable that a certain degree of documentation for the other component might land in workflow out of sheer necessity.  Of course, it's no excuse to not _also_ document each component independently.  `</$0.02>`

**Comment by arschles** [comment]
@krancour I agree, and this issue is not for splitting the docs up into individual components. This issue simply represents moving the `docs` folder into its own dedicated repo. The docs therein would, IMO, still look the same as they do now.

However, right now they go well beyond the functionality that *just* the code in this repository provides. For example, they cover:

- Installing Deis with helm
- In depth instructions on configuring the router
- The `git push` workflow
- Using and configuring storage (including deis/minio)

**Comment by krancour** [comment]
Gotcha.  I misunderstood the title and OP.  I interpreted as docs currently residing in deis/workflow moving out to other existing repos.

I'm on board with what you are suggesting.  And for the most part, I'm not entirely opposed to abandoning the monorepo of yore (no need to rehash that again though, lol), but I will say that having docs and code in separate repos makes it quite tough to enforce a notion of completeness where a change isn't complete until it's been documented.

**Comment by bacongobbler** [comment]
not going to be able to do this for v2-beta. punting this

**Comment by slack** [comment]
Closing with the creation of https://github.com/deis/docs-v2
