### ISSUE TITLE
`config:set` complains about formatting of `KEY=VAL` but merrily continues

### ISSUE THREAD

**Issue by slack** [deis/workflow#228]
```console
example-go [master]$ deis2 config:set POWERED_BY pushups
'POWERED_BY' does not match the pattern 'key=var', ex: MODE=test
'pushups' does not match the pattern 'key=var', ex: MODE=test
Creating config... ..o^...^o..done

=== mellow-zaniness Config
$
```

Should most likely exit 1.

**Comment by Joshua-Anderson** [comment]
@slack The origonal intention here was that if you were setting multiple variables `config:set FOO=bar TEST true` it would set the properly formatted variable, `FOO` but warn on the improperly formatted variable, `TEST`.

This definitely should return 1.

If would be less confusing if no valid variables were found to abort the `Creating config` stage.

Alternatively config could not be set at all if one of the variables is invalid.

**Comment by slack** [comment]
I'm a bit on the fence about partial application. The intent of the user is to set 'x' things in one go. It might make sense to just error and exit, especially if config application takes a long time (across, say 35 processes).

**Comment by technosophos** [comment]
Yes, we should stick by a particular format and not introduce an ambiguity that will later confuse users. I'd like to see a format error stop processing and return a non-zero exit code.

**Comment by bacongobbler** [comment]
I'll see if I can tackle this today.
