### ISSUE TITLE
rename to deis/workflow-docs

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#23]
Eventually when we move onto Deis v3, we should still technically be able to use this repository to store our own documentation. Therefore I propose we rename this to plain ol' `docs`.

**Comment by krancour** [comment]
Can I suggest, alternatively, that we rename to "workflow-docs," so that we are crystal clear on which product or opinionated assemblage of products this documentation represents?

**Comment by bacongobbler** [comment]
Absolutely. If the documentation will be all about workflow, then workflow-docs makes sense as a name.

**Comment by arschles** [comment]
If this still relevant?

**Comment by bacongobbler** [comment]
nope! changed to deis/workflow.

**Comment by arschles** [comment]
:+1:
