### ISSUE TITLE
release-checklist: figure out how to avoid code freezes

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#233]
The current release workflow requires us to call a development "code freeze" for all pull requests until we're finished with a release. We should try and engineer a way to cut a release without needed to completely freeze all merges across the organization.

**Comment by Joshua-Anderson** [comment]
Could something like this possibly work?

When preparing to cut a release:

1. Create a new RC branch
2. Landings can continue on master and testing/QA can proceed on the RC branch.
3. If bug is caught in the RC, a PR is sent to master, merged, and then cherry picked over to the RC branch.

**Comment by bacongobbler** [comment]
Yep! That's the exact process we thought of. This came out of our release retrospective this afternoon. The work that has yet to be done for this approach now is to get [deisrel](/deis/deisrel) and [deis-workflow-group](/deis/deis-workflow-group) to have the ability to cut charts from the latest commit on the RC branch, make [the component jobs in jenkins](https://ci.deis.io/job/component-seed-job/) build and deploy RC images from said branch, and update the release checklist with the new process. Right now it's more of a "discovery" phase to figure out what other tooling/work needs to be done in order to use this release process.

**Comment by bacongobbler** [comment]
we've long since implemented this
