### ISSUE TITLE
startup loop in the k8s scheduler could loop forever

### ISSUE THREAD

**Issue by arschles** [deis/workflow#233]
The loop is in #172 [here](https://github.com/deis/workflow/pull/172/files#diff-3b6e1f09121075ad67f216aa2bbfc9a6R400). As @helgi comments, the loop should not loop forever according to [k8s pod phases](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pod-states.md#pod-phase), but the loop should be made more resilient anyway, for defensive purposes.

**Comment by smothiki** [comment]
closing in favor of #406 which addresses this issue
