### ISSUE TITLE
Dev workflow can be improved

### ISSUE THREAD

**Issue by krancour** [deis/workflow#234]
So most of the hacking I've done on workflow so far has been on docs.  Today, in order to test deis/router#72 against #197 I'm having to build and deploy workflow from source.  I'm finding the dev workflow _for_ workflow (meta, I know) to be a bit clunky...

Since I already had Deis v2 alpha installed via helm and functioning fine, my goal was to swap the custom-built workflow Docker image for the one that was already running.  I had to do _all_ of the following:

```
$ make build
$ make docker-push
$ make kube-delete
$ make kube-create
```

Another oddity is that `make docker-push` also implicitly executes the `update-manifests` target.  I would argue that updating the manifests is something that needs to happen pre-deployment; _not_ pre-push.

Compare this process to deis/router (which can't take all the credit, because it borrowed so heavily from Deis v1.x conventions).  One command accomplishes all of the above:

```
$ make deploy
```

imo, this would make for a more streamlined developer experience.

**Comment by arschles** [comment]
:+1:

**Comment by helgi** [comment]
`make deploy` exists now. Closing this. Reopen if you think there is more we need to do for the dev flow
