### ISSUE TITLE
unexpected ctrl+c behavior during 'deis pull' 

### ISSUE THREAD

**Issue by jdumars** [deis/workflow#237]
**Validation environment:**
Amazon AWS
1 x Kubernetes Master / etcd t2.medium / CoreOS ~ stable & beta both tested
3 x Kubernetes nodes t2.medium /  CoreOS ~ stable & beta both tested

Initialize a new local repository, deis create, deis pull remote image jsingerdumars/hellonode, press ctrl+c ~5 seconds after “Creating build…” starts

**Expected outcome**: Exiting the build process should trigger a rollback and the container should not run.
**Actual outcome** -  After 20 seconds, the ctrl+c resulted in the image being deployed to the cluster and orphaned with no rollback.  “deis scale” on the worked as though it was intentionally deployed. 

```
ubuntu@ip-172-31-42-36:~/test2$ time deis pull tutum/hello-world
Creating build... o..^C
real	0m19.960s
user	0m0.014s
sys	0m0.001s

ubuntu@ip-172-31-42-36:~/test2$ deis scale cmd=3
Scaling processes... but first, coffee!
done in 227s
```

**Comment by vdice** [comment]
@mboersma if this issue requires a fix in `v2.0-rc1` can we update with the `showstopper` label?  Otherwise, perhaps we move this to the next milestone...

**Comment by slack** [comment]
Ultimately the fix for this will be using Deployments rather than fiddling with the k8s API directly. This should go in 2.1

**Comment by helgi** [comment]
Deployments have landed in master now behind a feature flag `DEIS_KUBERNETES_DEPLOYMENTS` (set it to 1 or whatever) that can be configured globally or per application (`config:set`)

Give that a spin and reopen if this is still a problem
