### ISSUE TITLE
Need a better unit  to set CPU for deis limits

### ISSUE THREAD

**Issue by smothiki** [deis/workflow#244]
Cpu limits were designed keeping docker cli in mind which takes cpu shares from 0-1024.
For K8s we are converting these CPU shares to number of CPU by dividing it with 1024.
and we only allow integer numbers.
Specifying CPU shares and converting them to #CPUS is not a good model in a heterogeneous cluster, where machines might have different #cpus. Also change deis limits from integer to float for assinging more granular limits to apps.
 
https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md#resource-types
https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md

**Comment by bacongobbler** [comment]
yes, I agree that we should just go with specifying the number of CPUs available in float so the data sent in is a 1:1 relationship with how kubernetes handles limit request. We did it the old way so people using v1 wasn't confused when switching from fleet to kubernetes, but now that we're all-in it makes sense to follow their model.

**Comment by mboersma** [comment]
Discussing this offline, we thought that this might be the friendliest implementation:
```console
$ deis limits:set -c cmd=50%  # allocates half of a node's CPUs, as 512 shares did before
$ deis limits:set -c cmd=2    # allocates exactly two of a node's CPUS
```

**Comment by smothiki** [comment]
My bad there is no way to set CPU shares any more in kubernetes. We can only set #CPUS or milli CPU 
units. the client commands are like.
```
$ deis limits:set -c cmd=500m  # allocates 512 shares  or 500 milli units of 1 core cpu.
$ deis limits:set -c cmd=2    # allocates exactly two of a node's CPUS
```
