### ISSUE TITLE
turn "configuring object storage" into a tutorial

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#254]
To a newcomer the [Configuring Object Storage](http://docs-v2.readthedocs.io/en/latest/installing-workflow/configuring-object-storage/) document is largely useless because it does not really describe how one sets up their cluster to use S3/GCS/WABS. Removing this document in favour of #253 along with provider-specific object storage configuration in the [quickstart docs](http://docs-v2.readthedocs.io/en/latest/quickstart/provider/aws/boot/) would probably be more useful.

**Comment by nathansamson** [comment]
one problem I noticed yesterday while trying this out is that "helmc edit char" only works proberly under vim (as in, it did not work with EDITOR=nano which is a relatively common setting).

**Comment by bacongobbler** [comment]
the quickstart documentation now has a tutorial.
