### ISSUE TITLE
Certificates in k8s secrets

### ISSUE THREAD

**Issue by helgi** [deis/workflow#254]
Make certificates discoverable by the router.

Format will be:
name: `<domain>-cert` (248 char limit on the domain)
contents: `cert` (public key and chain) and `key` in base64

There will be no need to mount the secret to the applications for router to work

ref #50

**Comment by krancour** [comment]
And because metadata.name cannot begin with anything but an alphanumeric char, @helgi and I discussed offline that _if_ we support wildcard domains, the naming format for those shall be `<top level domain>-wildcard-cert`.
