### ISSUE TITLE
Cannot push to any app after any one single push fails

### ISSUE THREAD

**Issue by dhilipsiva** [deis/workflow#257]
Hi - not sure if this one belongs to Deis Builder / here. So posting here anyways.

First off - you guys are doing an awesome job with Deis. Thanks a lot for all the effort from community. 👏

This is my reaction to Deis, when I first discovered it a year back:

![2dshtm7](https://cloud.githubusercontent.com/assets/502170/15460329/5e6a7ad2-20cd-11e6-851d-12e29a1adfb2.gif)

Totally in love with Deis.

Anyways, coming to the issue that I am facing: I have 2 apps that I am pushing to on Deis. I call them `Sherlock` (Python/Django) & `Irene` (NodeJS). 

I created a GKE cluster on command line. Installed `workflow-beta4` (+ both beta2 & beta3 had the same Issues) on it, registered with Deis client. I created `sherlock` app on Deis, push the code (Django Buildpack with Procfile)-> this is working just fine, no matter how many times I commit and push it - it always works just fine. 

I create the `Irene` app (A variant of node docker image + Dockerfile) and this build fails because of some reason (Probably some mistake on my side - I will figure this out). But after the Irene build fails - I am not able to push to any apps after that. I am not able to push to the `Sherlock`, or any other app for that matter, as well. It says, I do not have access to repo. When I try deleting the Irene App, create it again and push the code - it says a previous build is still in progress.

If you can point me in the right direction - I am more than happy to debug the code myself.

**_Steps to reproduce the Issue_**:

* `gcloud container clusters create appknox --num-nodes "2"`

<img width="840" alt="screen shot 2016-05-23 at 10 21 37" src="https://cloud.githubusercontent.com/assets/502170/15460600/48aacf82-20d0-11e6-9ca5-a827ce0c488f.png">

<img width="1159" alt="screen shot 2016-05-23 at 10 50 43" src="https://cloud.githubusercontent.com/assets/502170/15460962/56c64e44-20d4-11e6-8dda-88078549e002.png">

* Prepare Helm. (`helmc version 0.7.0+20a7ed7`, `deis version 2.0.0-dev-55497eb`)

<img width="997" alt="screen shot 2016-05-23 at 10 25 57" src="https://cloud.githubusercontent.com/assets/502170/15460659/ecc301a2-20d0-11e6-8aa4-94d804ea57f7.png">

* `helmc install workflow-beta` - I am aware the images above has `workflow-dev` installed. But later, I created a new cluster, generated and installed `workflow-beta4`

* `kubectl --namespace=deis get pods`

<img width="526" alt="screen shot 2016-05-23 at 10 49 21" src="https://cloud.githubusercontent.com/assets/502170/15460938/1cbd5652-20d4-11e6-99fc-def2941ad35b.png">

* `kubectl --namespace=deis get svc deis-router`

<img width="701" alt="screen shot 2016-05-23 at 11 00 01" src="https://cloud.githubusercontent.com/assets/502170/15461125/a6943d40-20d5-11e6-9d1b-202593dfe8fa.png">

* Sorry, for the **Deis version** mentioned above, I just updated it to `2.0.0-dev-f22a325`

<img width="524" alt="screen shot 2016-05-23 at 10 58 49" src="https://cloud.githubusercontent.com/assets/502170/15461103/6ebceffc-20d5-11e6-88ef-e7b9976fc046.png">

* `deis register deis.MY_ROUTER_IP.xip.io`

<img width="479" alt="screen shot 2016-05-23 at 12 12 57" src="https://cloud.githubusercontent.com/assets/502170/15462350/e1e59560-20df-11e6-8c88-61465c3a4655.png">

* `deis apps:create sherlock`

<img width="679" alt="screen shot 2016-05-23 at 12 15 10" src="https://cloud.githubusercontent.com/assets/502170/15462383/188e670e-20e0-11e6-9975-a157133a5aed.png">

* `deis keys:add`

<img width="572" alt="screen shot 2016-05-23 at 12 16 39" src="https://cloud.githubusercontent.com/assets/502170/15462457/89e4f454-20e0-11e6-9a14-dd1819d178ac.png">

* `git push deis 148-upgrade`

<img width="715" alt="screen shot 2016-05-23 at 12 23 26" src="https://cloud.githubusercontent.com/assets/502170/15462586/55eab14c-20e1-11e6-9614-efb3843534c3.png">
<img width="714" alt="screen shot 2016-05-23 at 12 58 55" src="https://cloud.githubusercontent.com/assets/502170/15463331/45d6b918-20e6-11e6-9d1b-1752a0e2021f.png">

* `deis open` is working as expected (400 error is expected)

<img width="584" alt="screen shot 2016-05-23 at 13 00 49" src="https://cloud.githubusercontent.com/assets/502170/15463358/80408840-20e6-11e6-8630-9eb836289089.png">

* Subsequent `git push deis 148-upgrade` seems to be working

<img width="470" alt="screen shot 2016-05-23 at 13 02 19" src="https://cloud.githubusercontent.com/assets/502170/15463377/ae3c67be-20e6-11e6-9e50-c6e846e4c020.png">

* `deis apps:create irene`

<img width="565" alt="screen shot 2016-05-23 at 13 04 12" src="https://cloud.githubusercontent.com/assets/502170/15463424/f32940c2-20e6-11e6-824c-1c4f80a34352.png">

* Here is a Dockerfile config for `Irene`

```
FROM danlynn/ember-cli:1.13.15

MAINTAINER someone@example.com

RUN npm install -g bower
RUN bower install

EXPOSE 4200

CMD ["ember", "serve"]
```

* `git push deis appknox/sherlock#148-upgrade` (After a couple of failed tries)

<img width="944" alt="screen shot 2016-05-23 at 13 27 43" src="https://cloud.githubusercontent.com/assets/502170/15464159/2ea7fcd4-20eb-11e6-9052-bcee54f2f233.png">
<img width="891" alt="screen shot 2016-05-23 at 13 34 28" src="https://cloud.githubusercontent.com/assets/502170/15464158/2ea7cbb0-20eb-11e6-9888-35af1d942d5e.png">

* After one or 2 errors like above - I am not able to push to any App

<img width="935" alt="screen shot 2016-05-23 at 13 30 03" src="https://cloud.githubusercontent.com/assets/502170/15464038/991458ac-20ea-11e6-9840-614e1fa8fcea.png">

<img width="918" alt="screen shot 2016-05-23 at 13 30 16" src="https://cloud.githubusercontent.com/assets/502170/15464039/9944f674-20ea-11e6-9a01-49643d9386d8.png">

🔝  As you can see, I dont have access to push to Deis / Irene anymore.

Any pointers are greatly appreciated!

**Comment by dhilipsiva** [comment]
+ Some times destroying the app and recreating it seems to solve the Issue - but, other times it just saya `A git push is already under progress`.

Please le me know if you guys need anymore details.

**Comment by arschles** [comment]
Hey @dhilipsiva - this is a fine place to post the issue, and thanks for letting us know. We're aware of it and have been to reproduce it and others similar to it.

The issue stems from a lock that we've placed in the builder to prevent two pushes from concurrently executing against the same application. In some cases, it's not released properly and we have a few related issues (deis/builder#235, deis/builder#220, deis/builder#217) that arise from that problem.

We're working on a fix now, but it might not make it into our upcoming RC1 release, which is scheduled for this Wednesday (two days from now).

**Comment by dhilipsiva** [comment]
Will close this for now as it is taken care of already.
