### ISSUE TITLE
[Proposal] Workflow v2.0.0-rc1 Release approach

### ISSUE THREAD

**Issue by vdice** [deis/workflow#258]
For the upcoming `v2.0.0-rc1` release,  we intend to forgo the need for a code freeze, in turn hopefully eliminating some of the repetition involved in the [current process](https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md).  Here we propose the following possible approach (at a high/outline level):

1. Once the `v2.0.0-rc1` milestone has been cleared of tickets, cut `v2.0.0-rc1` branches for all [workflow component repos](https://github.com/deis/deisrel/blob/master/actions/common.go#L49-L64).
2. Push `v2.0.0-rc1` image tags for said components to [quay.io/deisci](https://quay.io/organization/deisci) based on latest commit shas on said branch.
3.  In [deis/charts](https://github.com/deis/charts), PR the `workflow-rc1(-e2e)` charts (with all component images updated to `quay.io/deisci/<component>:v2.0.0-rc1`)
4. Kick off automated and manual testing
5. If testing produces an issue needing a fix:
  * PR the fix, get it reviewed and merged into master of component repo(s)
  * `git cherry-pick <issue_fix_sha>` into the `v2.0.0-rc1` branch(es) of component repo(s)
  * repeat step 2. for component repo(s) to update quay tags
6. Once the release is greenlit, run step 2 for all components,  this time to the [quay.io/deis](https://quay.io/organization/deis) org.
7. Proceed as usual from [Step 6](https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md#step-6-update-helm-classic-chart) of current Release Checklist.

**Comment by jchauncey** [comment]
Eventually I would like to see us move to not having to cut the images in `deisci` but I think for this time around this will be a huge improvement. 👍

**Comment by mboersma** [comment]
This sounds like a good plan to me. 

I wonder if there is a case for doing step 1 ("cut `v2.0.0-rc1` branches") repo-by-repo rather than all at once: some components have been ready for rc1 for days already, while others may need to go down to the wire. We could free up some components for merging while waiting for others to complete their milestone items, at the cost of making this step more complicated.

**Comment by vdice** [comment]
ah good point @mboersma -- in fact, for `rc1`, the branch cutting will probably be done by hand (we didn't have a precedent to automate for in `deisrel`)... 

It could be cool if step 1 was 'crowd-sourced' even, meaning, once a given component repo's release milestone had been cleared, a maintainer for that component repo might just go ahead and cut the branch at that point.

**Comment by sgoings** [comment]
LGTM @vdice. Not sure about adding crowd-sourced step 1 right now is a good idea, but maybe in the future?

**Comment by vdice** [comment]
The steps in this proposal were utilized for the [Workflow v2.0.0-rc1](https://github.com/deis/workflow/releases/tag/v2.0.0-rc1) release; closing.
