### ISSUE TITLE
Installing workflow documentation should include '-w' on the get pods watch instructions

### ISSUE THREAD

**Issue by arschles** [deis/workflow#262]
About 3/4 of the way down the page at https://docs-v2.readthedocs.io/en/latest/installing-workflow/, there reads the following text:

"""
Helm Classic will install a variety of Kubernetes resources in the deis namespace. You'll need to wait for the pods that it launched to be ready. Monitor their status by running:

```console
$ kubectl --namespace=deis get pods
```

If you would like kubectl to automatically update as the pod states change, run (type Ctrl-C to stop the watch):

```console
$ kubectl --namespace=deis get pods
```
"""

The second `kubectl` command should include `-w` at the end

**Comment by Joshua-Anderson** [comment]
This has been fixed!
