### ISSUE TITLE
Test config:set with multi-line values

### ISSUE THREAD

**Issue by krancour** [deis/workflow#268]
See deis/deis#4844.  While the root cause doesn't apply to v2, we should still assert that this works as expected, just in case any of the encoding required to set env vars within a k8s manifest is interfering with proper interpretation of newline characters by the containerized apps consuming those environment variables.

**Comment by arschles** [comment]
we have an automated test for multi-line config values [here](https://github.com/deis/workflow-e2e/blob/master/tests/config_test.go#L46-L51)

**Comment by bacongobbler** [comment]
That works, but we also need to make sure that the environment variable inside the container (through `deis run env`) is ok as well, which is what occurred in deis/deis#4844

**Comment by arschles** [comment]
got it. can you create a new issue over in deis/workflow-e2e for this then?

**Comment by bacongobbler** [comment]
done. deis/deis-e2e#23 covers that. closing!
