### ISSUE TITLE
Slug URL in generated RCs is wrong

### ISSUE THREAD

**Issue by krancour** [deis/workflow#269]
There's an error somewhere in here that results in the slug URL set on the rc to be malformed.  It might look like this, for example:

```
http://10.3.0.171:9000/git/home/nimbus-barbecue-git-afb7db0a/push/slug.tgz
```

Despite the fact that the actual URL where the slug can be found is this:

```
http://10.3.0.171:9000/git/home/nimbus-barbecue:git-afb7db0a/push/slug.tgz
```

In case it's tough to spot, the difference is a dash vs a colon separating the image name from the tag.

The result is that the slugrunner gets a 404 when it uses mc to try to fetch the slug.  This sends the pod into a CrashLoopBackOff.

It looks like the issue was recently introduced in here somewhere:

https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L605-L627

**Comment by arschles** [comment]
I can also reproduce this issue

**Comment by bacongobbler** [comment]
https://github.com/deis/workflow/blob/31190355dbc5b4e7b1477791f0c1f997af19f5c4/rootfs/scheduler/__init__.py#L613 is indeed the culprit.

**Comment by helgi** [comment]
Yeah that was a total mistake from when @arschles and I were debugging the go rewrite and the idea of `-` came up :) fixing

**Comment by krancour** [comment]
That substitution looks like it may have been going on for a while before things broke-- which is why I didn't zero in on that one line initially.  I wasn't sure if some of the surrounding conditionals also played a role in this substitution happening in cases now where it might not have prior.

**Comment by helgi** [comment]
If by a while you mean 4 days ;) https://github.com/deis/workflow/commit/3de4d0d811afee038b8c73f0cecccd749f511018 here is when it got introduced, for recordkeeping

**Comment by krancour** [comment]
4 days is a long time in Deis time!

**Comment by arschles** [comment]
thanks for fixing @helgi - https://github.com/deis/builder/pull/72 now works completely!
