### ISSUE TITLE
[Proposal] Standard kube make tasks

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow#274]
So there seem to be at least 2 standard make tasks - `kube-delete` and `kube-create`.

In the logger repo I have added another which is `kube-update`. This basically deletes the replication controller and recreates it using `manifests/deis-logger-rc.tmp.yaml`.

There is another task that I have seen `kube-replace` which does the following: 
```
kube-replace: build push update-manifests
kubectl replace --force -f manifests/deis-logger-svc.yaml
kubectl replace --force -f manifests/deis-logger-rc.tmp.yaml
kubectl replace --force -f manifests/deis-logger-fluentd-daemon.yaml
```

I also added `kube-install` to logger: 
```
kubectl create -f manifests/deis-logger-svc.yaml
kubectl create -f manifests/deis-logger-rc.yaml
kubectl create -f manifests/deis-logger-fluentd-daemon.yaml
```

This is useful for installing a specific stable version of a component.

If there are better ways to accomplish these tasks thats fine just would like to see us standardize on them across all repos.

**Comment by helgi** [comment]
`make deploy` now exists and really is the only `kube` related action left in `controller` so I am closing this.

Reopen if you have a revised proposal
