### ISSUE TITLE
router fails if scheduled onto a host with kube-api:443

### ISSUE THREAD

**Issue by paulczar** [deis/workflow#277]
Is there a way to provide scheduler hints to ensure this doesn't happen, or perhaps at least document the issue ...   can probably fix it by using an alternative port in the helm manifests for people who have the issue.

of course it may make sense to default to the internal port (6443?)  and rely on the user to use that port, or put it through an LB from 443 -> 6443 ?

```
tcp6       0      0 :::443                  :::*                    LISTEN      8566/kube-apiserver
$ kubectl --namespace=deis describe pod deis-router-0qbsf
 3m	3m	1	{kubelet k8s-02}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-0qbsf_deis_d59d48a6-268a-11e6-aa90-080027f894cd_d73475ca on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use\n"
```

**Comment by jdumars** [comment]
Hi Paul, I had the same issue provisioning clusters in Exoscale on CoreOS, and am wondering what method you provisioned the cluster with, as well as OS.

**Comment by bacongobbler** [comment]
related issue: https://github.com/deis/router/issues/188

the solution as pointed out by @krancour is to either run the kube api server on a different port or to run it on a different host (i.e. master node/worker node)

**Comment by krancour** [comment]
Also, one other option can be to drop the host ports from the router rc's pod template spec _if you don't need them_. (They're there for a reason, but most people don't need them.)

These lines could go:

https://github.com/deis/charts/blob/master/workflow-v2.0.0/tpl/deis-router-rc.yaml#L32-L40

**Comment by bacongobbler** [comment]
closing as the question has been answered in deis/router#188 and by @krancour
