### ISSUE TITLE
Bintray files are Forbidden! (when installing deis client)

### ISSUE THREAD

**Issue by foxycoder** [deis/workflow#282]
Hi!

I clicked a bunch of the client files over on bintray to see if it was just the current one that did not work form me and I could install an older version instead, but they all seem to be `Forbidden!`

See: https://dl.bintray.com/deis/deisci/

(the one I was interested in was: https://dl.bintray.com/deis/deisci/deis-7283e7c-darwin-amd64)

Hope it's an easy fix so I can try out the new version soon! 😄 

Cheers!

**Comment by bacongobbler** [comment]
thanks @foxycoder! We're taking a look into it with https://github.com/helm/helm-classic/issues/482. Stay posted there for updates.

**Comment by bacongobbler** [comment]
actually re-opening as this is the client and that one is for helmc.

**Comment by bacongobbler** [comment]
I have a feeling that this is from the recent notice we got from bintray last night:

> Hi Deis,

> Your Bintray account is currently rate-limited due to overuse.
Customer Support should contact you at the earliest to remove the limits from your account. You may also contact them directly at support@bintray.com.

> Regards,
> The Bintray Team

**Comment by bacongobbler** [comment]
In the meantime you can build the client from source via https://github.com/deis/workflow-cli#from-scratch

**Comment by sgoings** [comment]
I'm working on an immediate solution with Bintray at the moment.

**Comment by foxycoder** [comment]
thanks for the updates!

**Comment by bacongobbler** [comment]
okay so the post-mortem for this is the following: bintray's terms of use does not allow development builds to be uploaded to their site. Under their [terms of service](https://bintray.com/docs/terms_of_service.html):

> , upload and/or store on the Site continuous integration artifacts or nightly builds, (i.e. you may only upload and store content in direct connection to official software releases).

We are currently re-building one client on bintray in deis/workflow-cli#72 and will continue to do so for a short period of time until we get our dev builds uploaded to S3, which you can follow in https://github.com/deis/workflow-cli/pull/73.

Keeping this issue open until deis/workflow-cli#72 is closed and we have a build available for downloading.

**Comment by bacongobbler** [comment]
this has now been fixed.

```
root@329430889cfe:/# curl -sSL http://deis.io/deis-cli/install-v2.sh | bash
Downloading deis-a17f89a-linux-amd64 from Bintray...

deis is now available in your current directory.

To learn more about deis, execute:

    $ ./deis --help
```

Please feel free to follow along with deis/workflow-cli#73 for our progress on migrating to S3.
