### ISSUE TITLE
Proposal: Make the quick start docs have one step per page

### ISSUE THREAD

**Issue by arschles** [deis/workflow#283]
Right now, the guide at http://docs-v2.readthedocs.io/en/latest/quickstart/ seems to provide a basic outline of the steps, but the guide for what you need to do to accomplish each step is at the other side of a link. For example, to accomplish step 2 ("Boot Kubernetes and Install Deis Workflow"), you have to click on a different link to do each of the following:
- Set up your k8s cluster (plus, you have to choose beforehand where you want your cluster to live)
  - Also, people should look at the system requirements before they decide, but that's not clear they should click on the link first (it's below the guides for GKE and AWS)
  - It's not clear which kind of cluster is suitable for what needs. For example, an explanation of pros/cons for single-developer testing / "kicking the tires" would be helpful for each kind of k8s cluster
- Install Deis workflow on the cluster

This issue proposes inlining all of the information in the quickstart guide, and presenting it in a format similar to a slide-show

**Comment by bacongobbler** [comment]
the quickstart docs have been optimized a while ago and follows a more tutorial style for each provider. Closing!
