### ISSUE TITLE
[storage] Design for Off-cluster Storage

### ISSUE THREAD

**Issue by slack** [deis/workflow#3]
For the alpha, we need to point a deis installation at off-cluster storage. This ticket is a placeholder for that design.

* [x] design off-cluster storage configuration (https://github.com/deis/builder/pull/21)
* [ ] document storage configuration in deis/workflow (see #63) _note: https://github.com/deis/workflow/pull/108 has the fix for this, and it was moved to the `v2.0-beta1` milestone._

**Comment by arschles** [comment]
@technosophos FYI removed you from the assignee. I'll be taking this later this week

**Comment by arschles** [comment]
@smothiki are you currently working on this? refer to https://github.com/deis/builder/pull/21 for how it's being done

**Comment by arschles** [comment]
documentation for storage config should be in builder in addition to workflow.

**Comment by smothiki** [comment]
Workflow Right now looks for Minio and falls back to fetcher I have to add checks for outside storage environment variables.

**Comment by arschles** [comment]
great, thanks @smothiki
