### ISSUE TITLE
doc(styles): footer cuts off the sidebar

### ISSUE THREAD

**Issue by flynnduism** [deis/workflow#303]
On a normal laptop screen (any viewport with a height less than 800px or so), the new documentation website has layout issues:

![footerarggh](https://cloud.githubusercontent.com/assets/686194/15942145/0b802c18-2e38-11e6-98c5-826d3f98136f.gif)

The `position: fixed` sidebar is overlapped by the sticky footer when you scroll to the bottom of the page.

**Comment by Joshua-Anderson** [comment]
Fixed in #494
