### ISSUE TITLE
Builder does not expose environment variables anymore during build?

### ISSUE THREAD

**Issue by nathansamson** [deis/workflow#307]
Using the new builder I could not push my (rails) application because it relies on environment variables being available during build (In fact they are in practice not needed, but an initializer of a gem I use crashes when the config is not complete, this is during startup that is executed when precompiling assets...)

On top of that: After the crash during build, the build pod for my app stopped worked / crashed , but the git push never ended

PS:  Note I am sure I had reported this bug already, complete with logs, but for some reason I can't find it back. So sorry if I am double posting, or the lack of logs...

**Comment by bacongobbler** [comment]
You posted the bug on deis/builder. We got your logs and we'll look into it :)

**Comment by nathansamson** [comment]
right, makes sense... Thanks for looking into it, I'll close this issue as it is probably builder related...
