### ISSUE TITLE
doc AWS/GKE/Vagrant quickstart links do not work

### ISSUE THREAD

**Issue by nathansamson** [deis/workflow#308]
The  AWS/GKE/Vagrant quickstart links in the sidebar do not work. YOu just stay on the current page 

The link on the quickstart page itself in the main text actually do work.

**Comment by bacongobbler** [comment]
Thanks @nathansamson! This was quickly patched up in #307. The build should be re-deploying. Please let us know if that doesn't work. :)

**Comment by nathansamson** [comment]
I looked through the list of bug reports; but not the list of closed merged requests.

I assume this can be closed.
