### ISSUE TITLE
Roadmap is referring "closer to release"

### ISSUE THREAD

**Issue by nathansamson** [deis/workflow#309]
from https://docs-v2.readthedocs.io/en/latest/roadmap/roadmap/

"A complete roadmap for post 2.0 will be provided once we are closer to release."

Since the release has passed, I think this message is due a little update :)

Looking forward to what the future will bring :)

**Comment by Joshua-Anderson** [comment]
Bump... should the roadmap be the same as the Deis V2 one. Does anyone want to write a new one?

**Comment by bacongobbler** [comment]
ping @slack as I know he re-wrote the v1 roadmap and will likely want to chime in here.
