### ISSUE TITLE
Serviceaccount tokens not being mounted in minion and router pods

### ISSUE THREAD

**Issue by lachie83** [deis/workflow#314]
This is running the v2-beta containers. Seeing the following issue

```
docker logs 2a3d53d9ed04ff8
2016/01/27 06:53:54 INFO: Starting nginx...
2016/01/27 06:53:54 INFO: nginx started.
2016/01/27 06:53:54 Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory.
root@kubernetes-node-04:~# docker logs 8601e3d1d0f6618
Fatal error  open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by bacongobbler** [comment]
@lachie83 do you have that serviceaccount token available in your cluster? How did you provision your cluster (which platform)? `kubectl get serviceaccounts` should give a better picture.

**Comment by krancour** [comment]
Depending on what admission controls are or are not in place, the default service accouny may or may not have been automatically created along with the `deis` namespace.  I had run into this once before with the router and the resolution I found was the explicit creation of a non-default service account in the `deis` namespace.  I'm not sure exactly why that wouldn't be working.  @lachie83 can we assume that you installed this using the official helm chart?

**Comment by lachie83** [comment]
@bacongobbler. He's what I'm seeing in the namespace

```
kubectl get serviceaccounts,secrets --namespace=deis
NAME      SECRETS   AGE
default   0         1d
deis      0         1d
NAME                        TYPE      DATA      AGE
builder-key-auth            Opaque    1         1d
deis-etcd-discovery-token   Opaque    1         1d
deis-router-dhparam         Opaque    1         1d
django-secret-key           Opaque    1         1d
minio-admin                 Opaque    2         1d
minio-ssl                   Opaque    2         1d
minio-user                  Opaque    2         1d
```

**Comment by lachie83** [comment]
@krancour I'm running with the following admission controls.
```--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota ```

Confirmed I installed using helm install deis-dev

**Comment by krancour** [comment]
@lachie83 each service account should normally have one secret associated with it.  You are showing zero associated with each.  I _think_ it is because you are missing the [ServiceAccount](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/admission-controllers.md#serviceaccount) admission control.

I'll see what can be done about explicitly creating the secret used by the deis service account so that this contingency is accounted for, but I wouldn't expect to get to this very soon.

In the meantime, what are the chances of you enabling the missing admission control?

**Comment by lachie83** [comment]
Added and restarted. Looks like I'm still seeing the same issue

```
root     14348     1  5 21:34 ?        00:00:04 /opt/bin/kube-apiserver --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
```

```
lachlan.evenson@LT3609$ kubectl get serviceaccounts,secrets --namespace=deis
NAME      SECRETS   AGE
default   0         13s
deis      0         12s
NAME                        TYPE      DATA      AGE
builder-key-auth            Opaque    1         12s
deis-etcd-discovery-token   Opaque    1         13s
deis-router-dhparam         Opaque    1         12s
django-secret-key           Opaque    1         12s
minio-admin                 Opaque    2         13s
minio-ssl                   Opaque    2         13s
minio-user                  Opaque    2         13s
```

**Comment by krancour** [comment]
@lachie83 you'd have had to reinstall deis afterwards.  If that's too heavy handed, you could try to be more surgical about it.  You could do the following:

```
$ kubectl delete serviceaccount deis --namespace=deis
$ kubectl create -f $(helm home)/workspace/charts/deis-dev/manifests/deis-service-account.yaml
$ kubectl delete rc deis-router --namespace=deis
$ kubectl create -f $(helm home)/workspace/charts/deis-dev/manifests/deis-router-rc.yaml
```

ymmv... other Deis components might be using that `default` service account in the `deis` namespace.

**Comment by lachie83** [comment]
@krancour 

I ran a helm uninstall deis-dev then another install.

**Comment by krancour** [comment]
This is being tracked in deis/router#101, so I am closing this.
