### ISSUE TITLE
on slug buildhooks from builder, controller should accept the URL for the slug

### ISSUE THREAD

**Issue by arschles** [deis/workflow#315]
specifically, on the `/v2/hooks/build` call, builder should be able to send a `slug_url` parameter in the body. currently, workflow and builder (and its slugbuilder) have to manually ensure that the URLs match

**Comment by helgi** [comment]
Is `slug_url` any arbitrary URL or should I be validating it against a certain list or against anything else to verify authenticity?

**Comment by arschles** [comment]
I can't think of a good list of verifications. @smothiki thoughts?

**Comment by smothiki** [comment]
If we create URL with a specific fixed pattern. Only the artifact name is sufficient to reconstruct the URL.
just send URL in place of image name and it should work fine I guess.

**Comment by helgi** [comment]
`artifact` here being everything but the domain itself? Should we just tack that on the `s3` settings we have already? That's doable, mostly wanted to know how flexible we wanted this.

**Comment by smothiki** [comment]
we are already doing that https://github.com/deis/workflow/blob/master/rootfs/deis/settings.py#L295

**Comment by helgi** [comment]
Yeah, I meant using that setting + artifect path (`/home/git/slugs/foobar.tgz` or whatever) that it sent, instead of sending the full URL.

* If we pass in the full URL then `workflow` does not need to know about `S3EP` at all.
* If we pass in the `artifect` and tack it on `S3EP` then there is slightly higher guarantee on the item coming from a known location but also means we that's the only place those can be stored.

@arschles ?

**Comment by arschles** [comment]
I'd like to allow builder to send the *full* URL, and put the onus on builder & slugbuilder to get it right. Objections?

**Comment by helgi** [comment]
I'm down with that. One less thing `workflow` has to care about. @smothiki do you see any issues?

**Comment by smothiki** [comment]
if the artifact path is fixed and if we know the domain of object store , is there a need to send full URL ?
It makes sense if the URL model is not constant. But I'm okay sending entire URL and workflow supports it I guess unless we are not doing a regex check on image

**Comment by helgi** [comment]
This was resolved with #346
