### ISSUE TITLE
admonition styling is broken

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#317]
This used to be how the doc admonitions (note, important, warning) were styled:

<img width="1440" alt="screen shot 2016-06-13 at 11 04 39 pm" src="https://cloud.githubusercontent.com/assets/1360539/16032538/60cf1298-31bb-11e6-92e4-961330e583ee.png">

And the identical admonition for the docs restyling done in https://github.com/deis/workflow/pull/302 is just plain text:

<img width="1440" alt="screen shot 2016-06-13 at 11 05 42 pm" src="https://cloud.githubusercontent.com/assets/1360539/16032623/de64e804-31bb-11e6-9aeb-37a2f556d33a.png">

More information on admonitions and how they are rendered are shown [here](https://pythonhosted.org/Markdown/extensions/admonition.html).

**Comment by flynnduism** [comment]
Good spot @bacongobbler - I'll restore those styles asap
