### ISSUE TITLE
Trouble Following Install Docs

### ISSUE THREAD

**Issue by jschneiderhan** [deis/workflow#319]
Hi there! I'm having trouble following the installation docs located at https://deis.com/docs/workflow/quickstart/provider/aws/install-aws/. The first problem I encountered was a missing namespace:

```bash
› helmc install workflow-v2.0.0
---> Running `kubectl create -f` ...
Error from server: error when retrieving current configuration of:
&{0xc8201280a0 0xc8200a20e0  deis STDIN 0xc82069bc20 0xc82069b950 }
from server for: "STDIN": namespaces "deis" not found
```

No big deal. I created the namespace with a `kubectl create` command.

Running the command again, it makes it further but crashes with a different error:

```bash
› helmc install workflow-v2.0.0
---> Running `kubectl create -f` ...
namespace "deis" configured

secret "builder-ssh-private-keys" created

secret "builder-key-auth" created

secret "django-secret-key" created

secret "database-creds" created

secret "objectstorage-keyfile" created

secret "deis-router-dhparam" created

serviceaccount "deis-builder" created

serviceaccount "deis-controller" created

serviceaccount "deis-database" created

serviceaccount "deis-logger-fluentd" created

serviceaccount "deis-logger" created

serviceaccount "deis-minio" created

serviceaccount "deis-monitor-telegraf" created

serviceaccount "deis-registry" created

serviceaccount "deis-router" created

serviceaccount "deis-workflow-manager" created

service "deis-builder" created

service "deis-controller" created

service "deis-database" created

service "deis-logger" created

service "deis-minio" created

service "deis-monitor-grafana" created

service "deis-monitor-influxapi" created

service "deis-monitor-influxui" created

service "deis-monitor-stdout" created

Error from server: error when retrieving current configuration of:
&{0xc82000e230 0xc820110310 deis deis-registry STDIN 0xc820463080 0xc820227b80 }
from server for: "STDIN": services "deis-registry" not found

[ERROR] Failed to upload manifests: exit status 1
```

BTW I had initially tried the installation following the Vagrant instructions, then retried here with the AWS instructions. I had the same issues with both.

**Comment by kmala** [comment]
Can you confirm if your kubernetes server and kubectl are both on version 1.2...I had seen similar error because of using a old client/server

**Comment by jschneiderhan** [comment]
Ah - my client is version 1.1.8, while my server is version 1.2.4. I'll update my client and see if that fixes the issue (I'm sure it will).

Thanks @kmala!

**Comment by jschneiderhan** [comment]
Yes, that fixed my second problem. I'm tearing down my cluster and starting up a new one to verify that this also fixes the first (the missing namespace).

**Comment by jschneiderhan** [comment]
Yup. The namespace was created this time around. Thanks again, @kmala. At the least, anyone else hitting this problem can find an easy solution 😃.

**Comment by olalonde** [comment]
Had same issue.. my kubectl also was at an older version than my server. Downloading the kubectl with version same as server fixed problem
