### ISSUE TITLE
[Proposal] Allow custom slugrunner images

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#323]
from https://github.com/deis/deis/issues/4362
(now `deis/workflow` is in charge of the manifest creation)

**Comment by arschles** [comment]
:+1:

**Comment by smothiki** [comment]
+1

**Comment by smothiki** [comment]
Little confusion here . Custom slugrunner images including slugrunner RC templates ??

**Comment by arschles** [comment]
I think the intent here is that a user can `deis config:set CUSTOM_SLUGRUNNER_IMAGE=my/image` and the controller would replace the slugrunner image in the RC template with `my/image`. This issue is similar to https://github.com/deis/builder/issues/66 for builder
