### ISSUE TITLE
Permission denied on dockerbuilder container

### ISSUE THREAD

**Issue by lachie83** [deis/workflow#325]
Following this example -- https://github.com/deis/workflow/blob/master/docs/src/using-deis/using-dockerfiles.md
```
image "quay.io/deisci/dockerbuilder:v2-beta": image pull failed for quay.io/deisci/dockerbuilder:v2-beta, this may be because there are no credentials on this request.  details: (Error: Status 403 trying to pull repository deisci/dockerbuilder: "{\"error\": \"Permission Denied\"}")
```

**Comment by arschles** [comment]
I believe this is because we haven't yet set up CI on the https://github.com/deis/dockerbuilder repo. I will create an issue there to track this.

**Comment by arschles** [comment]
Actually, there already was one. Ref https://github.com/deis/dockerbuilder/issues/4

**Comment by arschles** [comment]
@lachie83 - now that https://github.com/deis/dockerbuilder/issues/4 is closed, this should be working. I'm going to close this issue, but please re-open or open a similar one if you see similar issues. Thanks!
