### ISSUE TITLE
500 Internal Server Error during deis pull while working through Getting started

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/workflow#325]
Following documentation and everything passing checks.  Got to the step:

 `deis pull deis/example-go -a zydeco-airfield`    

results were:

   Creating build... Error: 
   500 Internal Server Error
   detail: Server Error`

How to debug?

**Comment by bacongobbler** [comment]
Hi @jwalters-gpsw! To debug controller errors, you can follow the [Troubleshooting Using Kubectl](https://deis.com/docs/workflow/troubleshooting/kubectl/) guide to grab the controller logs. Would you please post them in a gist? Thanks!

**Comment by jwalters-gpsw** [comment]
Closing issue. Pilot error. didn't have SSH key set up for deis push/pull. I'll see if I can submit a patch to the QuickStart documentation. It works great!
