### ISSUE TITLE
Vague error message when there is no SSH key for push/pull operations.

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/workflow#327]
Following Quick Start documentation and everything passing checks. Got to the step:

deis pull deis/example-go -a zydeco-airfield

results were:

Creating build... Error: 
500 Internal Server Error
detail: Server Error

the underlying issue was that I hadn't added an SSH key for git operations.

**Comment by bacongobbler** [comment]
`deis pull` does not require an SSH key to deploy the image. Do you have server logs to share?

**Comment by jwalters-gpsw** [comment]
Where would I find those?

**Comment by bacongobbler** [comment]
Please see my comment in [your last issue](https://github.com/deis/workflow/issues/325#issuecomment-226325898).

**Comment by jwalters-gpsw** [comment]
Here is the log from the controller. Which other components should I get the logs for?
Also, quick question. How do I shutdown Workflow and Kuberenetes? I want to do that after getting the logs. And you are right of course... without SSH key in agent it still works.

[controller.txt](https://github.com/deis/workflow/files/318600/controller.txt)

Also,

**Comment by bacongobbler** [comment]
From the gist, I see

```
sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied
```

Which is a symptom of https://github.com/deis/controller/issues/801. I'm going to close this as a duplicate so please post there and see if the workaround in that issue works for you.

The only way to "shut down" workflow is to uninstall it. :)
