### ISSUE TITLE
Dockerfile deploy doesn't honor repository's exposed port for readiness check

### ISSUE THREAD

**Issue by n0n0x** [deis/workflow#328]
Sorry I put this here but I don't now which deis service handles this cases!

Came across this when using a Dockerfile like this:

```
FROM nginx
EXPOSE 80
```

by simply doing this, and pushing to deis, the readiness check points to port 443, this is because nginx image [Dockerfile](https://github.com/nginxinc/docker-nginx/blob/11fc019b2be3ad51ba5d097b1857a099c4056213/mainline/jessie/Dockerfile) exposes both 80 an 443 and Deis seems to choose this instead of honoring the repository's dockerfile

### How to reproduce:

1. `git init`
2. Create a Dockerfile
```
echo "FROM nginx
EXPOSE 80" > Dockerfile
```
3. `git add Dockerfile`
4. `git commit -a -m Test`
5. `deis create test-expose`
6. `git push deis master`
7. `kubectl get po --namespace=test-expose`
8. `kubectl describe po --namespace=test-expose <podname> |grep Readiness`

#### Result:
````
    Readiness:		tcp-socket :443 delay=5s timeout=5s period=5s #success=1 #failure=1
````
#### Expected result:

Deis should honor any exposed port from the repository's Docker file rather than the ones on the base image:
```
    Readiness:		tcp-socket :80 delay=5s timeout=5s period=5s #success=1 #failure=1
```

**Comment by bacongobbler** [comment]
hey @n0n0x, at this time we only support dockerfile apps that [expose only one port](https://deis.com/docs/workflow/applications/using-dockerfiles/#dockerfile-requirements) for these reasons.

That being said we are currently working on rewriting how health checks can be configured, which you can follow along in https://github.com/deis/controller/issues/603.

**Comment by n0n0x** [comment]
Oh, I misunderstood the documentation. Because I am actually explicitly telling to expose port 80 in my Dockerfile, but It exposes port 443 because of the inherited Dockerfile from the nginx image. I thought if I explicitly declare `EXPOSE 80` on my Dockerfila that would override it.

**Comment by bacongobbler** [comment]
Yeah that's what I thought too, but that is something built into docker. all child images inherit anything from parents, including exposed ports.

**Comment by n0n0x** [comment]
Awesome, thanks for the explanation! I am closing this.
