### ISSUE TITLE
Difference between deis.io and deis.com is confusing

### ISSUE THREAD

**Issue by tback** [deis/workflow#331]
The difference between the two websites is confusing. To me it seems deis.io is focussed on v1 where deis.com is focussed on v2. Maybe there is a better way to serve both user groups that avoids the confusion.

**Comment by slack** [comment]
Completely agree! And I have some plans in the works. Now that we've shipped Workflow we have some time to dedicate to bringing deis.io and deis.com together. We are also drawing up plans to help folks discover and navigate the various Deis projects more clearly. Keep your eyes peeled, you should start seeing changes in the next month or so.

**Comment by bacongobbler** [comment]
these changes have since been implemented, I assume, so it should be more clear to the user between the two sites. Closing!
