### ISSUE TITLE
Deis documentation should warn users that a free GCE trial account cannot run deis workflow due to account quota

### ISSUE THREAD

**Issue by rothgar** [deis/workflow#333]
A free Google cloud account is limited to 1 public IP. If a user uses GCE with `kube-up` to create their kubernetes cluster and then run `helmc` to install deis on their cluster the kubernetes-master will use a public IP and the deis router will try to create a LoadBalancer with a public IP.

The load balancer will fail. In `kubectl describe svc deis-router --namespace deis` you will see the following error.

```
Error creating load balancer (will retry): Failed to create load balancer for service deis/deis-router: failed to ensure static IP : error creating gce static IP address: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 1.0, quotaExceeded
```
Users should probably be warned about that limitation before they run into the problem trying to get deis deployed.

**Comment by kmala** [comment]
@rothgar If you want a work around for this problem in the testing or dev environments you can change the  type of the router service(https://github.com/deis/charts/blob/master/workflow-v2.0.0/manifests/deis-router-service.yaml#L11) from Load balancer to NodePort and use the ip of the node on which router pod has started.

**Comment by rothgar** [comment]
Thanks, I'm aware of the work around but I think it maybe should be documented as a warning for users. If someone were trying deis without being very familiar with kubernetes it would probably take them a while to figure out why things aren't working.

**Comment by Joshua-Anderson** [comment]
I'm not seeing the problem. I'm running deis on GKE with the free trail with no issues. The quota limit seems to be 23 ip addresses for me.

**Comment by rimusz** [comment]
I'm not seeing that problem too, as at my workshops most of guys are using trial accounts and nobody complained about not being able to install the Workflow to GKE

**Comment by rothgar** [comment]
That's very strange. Maybe it's just something on my account. I did talk to the product manager for GKE at dockercon and mentioned I ran into this problem. Could be they changed the limits.

@Joshua-Anderson Where did you find the quota limit?

If no one else is having this problem we can close the issue.

**Comment by Joshua-Anderson** [comment]
There is a quota page in the compute section that contains the IP quota.

**Comment by Joshua-Anderson** [comment]
@rothgar Did you ever take a look at your quotas?

Given that most people haven't had this problem, maybe you started their trial and then they the bumped the quotas.

**Comment by rothgar** [comment]
Sorry for not following up. I did look for the quotas but didn't find this one. I did talk to a couple people at Google about the limitation but not sure if it was changed. My free trial has since ended so I'm fine closing this as un-reproducible.
