### ISSUE TITLE
Expose user/app checking for Builder in a builder specific hook

### ISSUE THREAD

**Issue by helgi** [deis/workflow#335]
Relates to deis/builder#81 and deis/builder#122

TL;DR from deis/builder#122 (has a more detailed discussion)

Expose `GET /v2/hooks/keys/$APP_NAME` and `GET /v2/hooks/keys/$APP_NAME/$USER_NAME` endpoints for Builder Auth Key only where it returns `404` when `APP_NAME` or `USER_NAME` are missing.

Return body will be `{"users": {"aaron": "keysandthings"}}` for the `APP_NAME` specific hook and `{"key": "keysandthings"}` for the per user hook

**Comment by arschles** [comment]
@helgi is `"keysandthings"` gonna be just the pub key for the user?

**Comment by helgi** [comment]
Yeah, whatever the key is that you need in the builder, which is the public

**Comment by helgi** [comment]
I changed it so that the `APP_NAME/USER_NAME` endpoint returns `{"$USERNAME": "$KEY"}`

If we want to support multiple keys per user then I could change the key part into a `list` - Thoughts?

**Comment by arschles** [comment]
>I changed it so that the APP_NAME/USER_NAME endpoint returns {"$USERNAME": "$KEY"}
:+1: 

>If we want to support multiple keys per user then I could change the key part into a list - Thoughts?

So the response body would look like the following?

```json
{"users":[{"$USERNAME":"$KEY"},...]}
```
