### ISSUE TITLE
Failure to put git images to Azure Blob.

### ISSUE THREAD

**Issue by monaka** [deis/workflow#340]
Yesterday Workflow on my cruster works fine. But today I got errors like this.
I tried a dozen time and 100% reproduced.
Where is an entry point for debugging this?
 
```
$ git push -u deis master
Counting objects: 8, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 927 bytes | 0 bytes/s, done.
Total 8 (delta 0), reused 0 (delta 0)
Starting build... but first, coffee!
22016/06/23 03:40:01 Put https://{censored}.blob.core.windows.net/builder?restype=container: dial tcp: i/o timeout
remote: 2016/06/23 03:40:02 Error running git receive hook [Build pod exited with code 1, stopping build.]
```

**Comment by bacongobbler** [comment]
the i/o timeout indicates that the builder is having some trouble connecting to azure. Can you confirm that azure is up/down for you?

**Comment by monaka** [comment]
There is no trouble event from Azure.
And WAL-E in deis-database puts wabs://database with no trouble.
So my Azure Storage will be up.
Are rerated code in Builder? I'll check it.

**Comment by monaka** [comment]
There had "dial tcp: i/o timeout" error in some tests on the upstream. 
https://travis-ci.org/Azure/azure-sdk-for-go/builds/122566057
https://travis-ci.org/Azure/azure-sdk-for-go/builds/122568002
I'm not sure if they are related on this issue now.

**Comment by monaka** [comment]
This was fixed automagically by re-installing. I close this for now.
I'll open new issue on deis/builder (or azure-sdk-for-go) if I could reproduce it.
