### ISSUE TITLE
Add quickstart documentation for Azure

### ISSUE THREAD

**Issue by jgogstad** [deis/workflow#341]
The "Installing Deis"-documentation [1.0](http://docs.deis.io/en/latest/installing_deis/azure/) includes documentation for how to setup Deis on Azure. A corresponding document for Deis Workflow is not available.

**Comment by bacongobbler** [comment]
Hey @jgogstad! If you feel like writing a tutorial up, you should be able to go through the [kubernetes on azure](http://kubernetes.io/docs/getting-started-guides/coreos/azure/) docs to get you set up.

**Comment by monaka** [comment]
I also runs Deis Workflow on Azure.
I also use scripts in the document on "kubernetes on azure" at the first time.
But it was just for tiny getting started (/var/lib/docker is too small for Workflow, and so on).
So I rebuilt my cluster by my hand. [CoreOS + Kubernetes Step By Step](https://coreos.com/kubernetes/docs/latest/getting-started.html)  is good tutorial for building K8s.

**Comment by bacongobbler** [comment]
this is now available. https://deis.com/docs/workflow/quickstart/provider/azure-acs/boot/
