### ISSUE TITLE
deis auth command(s)  not listed in deis help

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#343]
```bash
deis version                                                                                                               
2.0.0-7c8df5a

deis help | grep auth
<no output>
```

**Comment by bacongobbler** [comment]
```
deis help | grep Auth
Auth commands::
```

If you look at the help string, there should be three auth-related commands:

```
Auth commands::

  register      register a new user with a controller
  login         login to a controller
  logout        logout from the current controller
```

The reason why we show each individual one is because they are shortcuts for `auth:register`, `auth:login` and `auth:logout`. Is that more clear, or is there something you'd like addresseing here?

**Comment by dmcnaught** [comment]
I was looking for how to delete a user, and had to go to online docs to find auth:cancel

**Comment by dmcnaught** [comment]
Maybe `deis help users` could be a little more informative on how to manage users...

**Comment by bacongobbler** [comment]
use `deis help users:list` for more information. `deis users` isn't used for anything more than just listing the users registered with the controller.

To address your original question, I'm just quickly hacking up a solution for you.

**Comment by dmcnaught** [comment]
Yeah - I think that auth should be listed as a subcommand, since it is. I think have register, login and logout listed as "Auth commands" is a little bit meaningless to the command user - it doesn't matter to them that it is a shortcut to the auth commands that aren't listed. 
I would prefer register, login, and logout to be listed either as subcommands, or shortcut commands.

**Comment by bacongobbler** [comment]
deis/workflow-cli#95 should help your `deis help | grep auth` dilemma. :)

**Comment by dmcnaught** [comment]
Also `Shortcut commands, use 'deis shortcuts' to see all::`, but `deis shortcuts` isn't a valid command?

**Comment by dmcnaught** [comment]
It wasn't really just that the grep wasn't returning. I generally feel that command help should output all subcommands, but that may not be the deis feeling?

**Comment by bacongobbler** [comment]
> Also Shortcut commands, use 'deis shortcuts' to see all::, but deis shortcuts isn't a valid command?

I have added that back in deis/workflow-cli#96.

**Comment by bacongobbler** [comment]
We've generally sidetracked from displaying *all* the subcommands, just the top-level ones. Its intent is to stick to the "bare minimum" to get you going; most users don't need to know about `auth:cancel` when first being introduced, however being introduced to `deis auth` is a good idea.

**Comment by dmcnaught** [comment]
Maybe we can add a `deis help all` that lists all commands. It's often a great way to get to know a command - to browse the subcommands 😄

**Comment by bacongobbler** [comment]
> Maybe we can add a deis help all that lists all commands. It's often a great way to get to know a command - to browse the subcommands :smile:

PRs welcome! ;)
