### ISSUE TITLE
[Proposal]: Increase timeout in probes

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#344]
Currently the probes are using `timeoutSeconds: 1` which works fine for local deployments. Using Amazon RDS that is too low.
```
bash-4.3# time curl -v localhost:8000/healthz
*   Trying ::1...
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.4.5
< Date: Fri, 05 Feb 2016 19:10:22 GMT
< Connection: close
< Transfer-Encoding: chunked
< x-content-type-options: nosniff
< DEIS_API_VERSION: 2.0
< X-Frame-Options: DENY
< x-xss-protection: 1; mode=block
< DEIS_PLATFORM_VERSION: 2.0.0-dev
< Content-Type: text/html; charset=utf-8
<
* Closing connection 0
OK
real	0m1.120s
user	0m0.000s
sys	0m0.000s
```

**Comment by technosophos** [comment]
I agree, @aledbf . Do you think we should simply set a higher limit, or make this configurable?

**Comment by aledbf** [comment]
> or make this configurable?

Configurable with a default? :)

**Comment by technosophos** [comment]
Default of 5 seconds?

**Comment by aledbf** [comment]
> Default of 5 seconds?

:+1:

**Comment by helgi** [comment]
Just a heads up that right now the default for Deis apps is 1 second as well (https://github.com/deis/workflow/blob/master/rootfs/api/models/config.py#L32) with initial delay of 10 but it is pretty easily configurable.

While the deis platform itself can be treated differently we should probably go ahead and bump that default (and update the docs) for the apps if we decide on a 5 second timeout

**Comment by technosophos** [comment]
I'm pulling this to RC1, since it's not a blocker for beta1. Feel free to PR a change whenever.
