### ISSUE TITLE
Documentation should target latest version of deis, not the development version.

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/workflow#351]
Right now, every PR targets master, regardless of whether the PR addresses an unreleased version of deis or it targets the current release.

One solution that could fix this is that `master` branch targets the current release of deis and is currently in production. Then a second branch, called `future` targets the next version of deis and is merged into master when that next version is released.

There are lots of ways to solve this problem, so what does everyone think about this?

**Comment by bacongobbler** [comment]
I'd personally opt for our build tools to handle this for us by building the docs on every tag as well as master. I've filed an issue to that tune on our deis.com repo (private due to blog post licensing issues).

**Comment by Joshua-Anderson** [comment]
That strategy sounds good to me!

**Comment by olalonde** [comment]
Related https://github.com/deis/workflow/issues/385#issuecomment-233846550 :)

**Comment by bacongobbler** [comment]
This doesn't work just yet. See #520. Once https://deis.com/docs/workflow/en/dev and https://deis.com/docs/workflow/en/v2.4.0 no longer show a 404 then we are rolling.

**Comment by bacongobbler** [comment]
FYI https://deis.com/docs/workflow/en/v2.4.1/ is now available, it's just /en/dev that's missing. #524 fixes that.
