### ISSUE TITLE
Setting user and pw in tpl/deis-database-secret-creds.yaml gives password authentication failed

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#354]
Using S3, IAM, and workflow-dev: 
As part of my deis workflow custer creation scripts, I set a user and password in ~/.helmc/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml so as to avoid autogenerating new ones, and I’m getting an issue in the deis db:
```bash
ku logs deis-database-dgvec
DETAIL:  Connection matched pg_hba.conf line 95: "host all all 0.0.0.0/0 md5"
FATAL:  password authentication failed for user "dbuser
    "
```
I delete the contents of the s3 database bucket, and that works when using the random passwords, but when I set them, I get the error. It looks like it works for a while, and then fails - database log at https://gist.github.com/dmcnaught/bb3047f1d4126abb0a3d96c91d04a00b

**Comment by krancour** [comment]
I'm curious if you have remembered to base64 encode the credentials.

**Comment by dmcnaught** [comment]
Yes. I didn't at first and it told me that was the problem.

**Comment by krancour** [comment]
@dmcnaught, possible you can share the script in question (with some dummy value substituted for your actual DB password, of course)?

**Comment by dmcnaught** [comment]
```bash
DEIS_DATABASE_USER=dbuser
DEIS_DATABASE_PW=Pa04M8hdrtENXG@d@7xyoODLkQCf4z
DEIS_VERSION=dev

DB_USER64=$(echo ${DEIS_DATABASE_USER} | openssl base64)
DB_PW64=$(echo ${DEIS_DATABASE_PW} | openssl base64)
sed -i.bak "s/user:.*$/user: ${DB_USER64}/g" ~/.helmc/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml
sed -i.bak2 "s/password:.*$/password: ${DB_PW64}/g" ~/.helmc/workspace/charts/workflow-dev/tpl/deis-database-secret-creds.yaml

helmc generate -f -x manifests workflow-${DEIS_VERSION}

helmc install workflow-${DEIS_VERSION}
```
I put the password into quotes, and we are good now...

**Comment by dmcnaught** [comment]
secret creds had this, so surprising it was a problem: 
```bash
data:
  user: ZGJ1c2VyCg==
  password: UGEwNE04aGRydEVOWEdAZEA3eHlvT0RMa1FDZjR6Cg==
```

**Comment by dmcnaught** [comment]
Oops - maybe not, now the replacement is not happening...

**Comment by dmcnaught** [comment]
My test wasn't valid - I had the sed lines commented out so was still using the random.
Uncommented - still failing.
It looks like it's failing when the controller tries to access the db. Does the controller get creds from somewhere else?

**Comment by dmcnaught** [comment]
I set the password to testpw, to make it simple - same failure.

**Comment by bacongobbler** [comment]
The controller gets the credentials [from the same secret](https://github.com/deis/charts/blob/master/workflow-dev/tpl/deis-controller-rc.yaml#L64-L73), so that's not the issue.

**Comment by dmcnaught** [comment]
I just did a diff on the helmc charts when using the random password, and when setting them and didn't see any clues. Going to try setting the passwords to be the same as the generated ones now.

**Comment by bacongobbler** [comment]
for reference, here's what mine looks like.

```
><> cat ~/.helmc/workspace/charts/workflow-v2.1.0/manifests/deis-database-secret-creds.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  namespace: deis
  labels:
    app: deis-database
    heritage: deis
data:
  user: U3J6cXBpelFSSHROZ0dkYUw2SkRXMUNaWTg0bXh1czY=
  password: OUYwVUE0YmRPbVB2N2pnQWtuVW9JSmpuanpBWUVkdFE=
```

When decoded:

```
><> echo U3J6cXBpelFSSHROZ0dkYUw2SkRXMUNaWTg0bXh1czY= | base64 --decode
SrzqpizQRHtNgGdaL6JDW1CZY84mxus6
><> echo OUYwVUE0YmRPbVB2N2pnQWtuVW9JSmpuanpBWUVkdFE= | base64 --decode
9F0UA4bdOmPv7jgAknUoIJjnjzAYEdtQ
```

**Comment by dmcnaught** [comment]
Are you seeing this working ok with STORAGE_TYPE=S3?

**Comment by bacongobbler** [comment]
Yep! Asides the bug that @krancour found while testing out v2.1.0 we are seeing this work just fine with S3 and GCS.

**Comment by dmcnaught** [comment]
I manually set them to the random values, and still getting failure.
I might have found a clue:

_templates_:
```bash
A:
data:
  user: {{ randAlphaNum 32 | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}
B:
data:
  user: ekN2R0NLSnZIOXM2VVZEU1k3dVpMQTJ5OVRudmhDNnQK
  password: T05HeWhTVmdjNGxraDJJU2pmM2Y1VlYydHdXWTQ0aVAK
```
_manifests_:
```bash
A: 
data:
  user: ekN2R0NLSnZIOXM2VVZEU1k3dVpMQTJ5OVRudmhDNnQ=
  password: T05HeWhTVmdjNGxraDJJU2pmM2Y1VlYydHdXWTQ0aVA=
B:
data:
  user: ekN2R0NLSnZIOXM2VVZEU1k3dVpMQTJ5OVRudmhDNnQK
  password: T05HeWhTVmdjNGxraDJJU2pmM2Y1VlYydHdXWTQ0aVAK
```
Then, if I decode and then encode the one from A (random generated) - I don't get the data from the manifest when random generated:
```bash
echo ekN2R0NLSnZIOXM2VVZEU1k3dVpMQTJ5OVRudmhDNnQ= | base64 --decode
zCvGCKJvH9s6UVDSY7uZLA2y9TnvhC6t
echo zCvGCKJvH9s6UVDSY7uZLA2y9TnvhC6t | base64
ekN2R0NLSnZIOXM2VVZEU1k3dVpMQTJ5OVRudmhDNnQK
```

**Comment by dmcnaught** [comment]
Can I log into the database manually from another pod, or a test pod?

**Comment by kmala** [comment]
yes...you should be able to

**Comment by dmcnaught** [comment]
Ah - I should have begun my question with "How"... 😄

**Comment by kmala** [comment]
`kubectl get service deis-database --namespace=deis` will give you the ip and port on which database instance is running...and you can get the base64 encoded username/password using `k get secret database-creds --namespace=deis -o yaml` or get the plain username/password from the database pod
```
k exec -it <db-pod> cat /var/run/secrets/deis/database/creds/password --namespace=deis
k exec -it <db-pod> cat /var/run/secrets/deis/database/creds/user --namespace=deis
```

**Comment by dmcnaught** [comment]
ok - the secret looks good, and so do the files on the database pod, but I'm still getting an error when the controller tries to log into the db.
```bash
ku logs deis-controller-43h2n
system information:
Django Version: 1.9.7
Python 3.5.1+
Django checks:
System check identified no issues (2 silenced).
Health Checks:
Checking if database is alive
There was a problem connecting to the database
```
```bash
ku logs deis-database-wghm8
DETAIL:  Connection matched pg_hba.conf line 95: "host all all 0.0.0.0/0 md5"
FATAL:  password authentication failed for user "zCvGCKJvH9s6UVDSY7uZLA2y9TnvhC6t
	"
```
Is the password stored on the controller filesystem?

**Comment by kmala** [comment]
yes...the database creds secret is mounted on both database and controller filesystem

**Comment by dmcnaught** [comment]
Pods not staying up long enough for me to query creds...

**Comment by kmala** [comment]
looks like there is a new line character in your username or password from your database logs above...

**Comment by dmcnaught** [comment]
Doesn't appear in queries - they look ok on the controller:
ku delete po $(ku get po | grep controller | awk '{print $1}') && sleep 1 && ku exec -ti $(ku get po | grep controller | awk '{print $1}') cat /var/run/secrets/deis/database/creds/password

**Comment by dmcnaught** [comment]
No newline in the file:
```bash
>ku delete po $(ku get po | grep controller | awk '{print $1}') && sleep 1 && ku exec -ti $(ku get po | grep controller | awk '{print $1}') cat /var/run/secrets/deis/database/creds/password
pod "deis-controller-5gxvh" deleted
ONGyhSVgc4lkh2ISjf3f5VV2twWY44iP
>
```

**Comment by dmcnaught** [comment]
Thanks @kmala for working that through - looks like the echo when I encode the password was adding a newline, so I'll update to `echo -n` - testing now.

**Comment by dmcnaught** [comment]
Tests pass.
