### ISSUE TITLE
[Meta] Improve deis client error messages

### ISSUE THREAD

**Issue by arschles** [deis/workflow#356]
See https://github.com/deis/workflow/pull/349/files#r52217168 for an example.

**Comment by helgi** [comment]
#343 raises the same issue

**Comment by arschles** [comment]
@helgi renamed meta to reflect that difference

**Comment by jchauncey** [comment]
let's use this issue to track the work on improving the client error messages

**Comment by arschles** [comment]
replaced by deis/workflow-cli#23
