### ISSUE TITLE
Rolling update on a micro-service without killing it until it's finished

### ISSUE THREAD

**Issue by grandmore** [deis/workflow#358]
Does the rolling update work without losing the work currently being carried out by the running micro-service that is being upgraded?

If we have a micro-service architecture with each service running. When we do an update and allow kubernetes to kill the service, we also kill the task that was running at the time of the update. This can lead to partially completed tasks.

For example:
1. We are reading an input from a user and want to save it to a database.
2. The service is upgraded.
3. It is killed half way through a save operation.
4. We now have a potentially corrupted dataset of half saved data 
5. When we retry the save we now have partially duplicate data.

There are 2 solutions I can see:
1. The service should not receive any new messages after an update has started so as not to cause more issues.
2. The service should keep running until we know it has finished, or leave X time for it to complete.

Does this work already?

**Comment by bacongobbler** [comment]
The proper way to handle this in your app is to gently shut down from a SIGTERM signal. When a pod is terminated, it receives SIGTERM. If your app handles that, then it can complete the save operation or handle ongoing requests, as well as refuse all incoming connections. For example, postgres will finish any database transactions, ship a final WAL backup and refuse incoming connections when SIGTERM is invoked.

Would that handle your problem, or is there another way you want to handle this?

**Comment by grandmore** [comment]
That should fix the second part of the issue, I will do some testing to confirm.

The first part I think is dealt with my kubernetes but can you confirm. My Understanding is that Kubernetes 1. starts the new version.
2. when its healthy starts sending network requests to it.
2. drains network requests from the old version.
3. terminates the old version.

Thanks for the fast answer.

**Comment by bacongobbler** [comment]
That is correct.

**Comment by bacongobbler** [comment]
closing due to the questions asked have been answered. If you have any more questions that need clarification please feel free to open another issue or ask in the #community channel in Slack. Thanks!
