### ISSUE TITLE
Ruby buildpack apps fail to deploy

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#367]
Deis' [example-ruby-sinatra](https://github.com/deis/example-ruby-sinatra) app fails to deploy on current Deis v2:
```
$ kubectl --namespace=cheery-kangaroo get po
NAME                           READY     STATUS             RESTARTS   AGE
cheery-kangaroo-v2-web-bquab   0/1       CrashLoopBackOff   3          55s
```
And the same is true for most other buildpack apps. The NodeJS, Java, Gradle, and Go example apps work, but others fail to start. See deis/slugbuilder#23 for testing status (I got the same results against master, not with that PR.)

I suspect a `PORT` mismatch, but haven't been able to pinpoint the problem yet.

**Comment by arschles** [comment]
@mboersma Is this issue pervasive of all buildpack apps?

**Comment by mboersma** [comment]
Not *all*, just most. I listed the working ones above. Example-go is happy, which may be why most of us haven't noticed this...

**Comment by arschles** [comment]
Ah, got it. I was wondering...

**Comment by smothiki** [comment]
I think the initial delay is 10secs and timesout for every 1 second after that. Example Go is a binary and starts real fast where as other apps are interpreted programs So we should consider the time to unpack the slug and run the main program

**Comment by smothiki** [comment]
I think increasing the  initial delay and timeouts for readiness probes should do

**Comment by bacongobbler** [comment]
That might help for now, but I don't think that's going to help for users who are running Deis with slow or unreliable internet connections similar to https://github.com/deis/deis/issues/1027. It's an arbitrary number that doesn't fix the root issue, though I don't have a solution that will fix it overnight. This is a design issue that comes with fetching the app slug at boot time rather than injecting it into the slugrunner image and generating an artifact.

**Comment by smothiki** [comment]
Here is what I propose health checks should be made configurable including timeouts.
BY default apps shouldn't be doing any health checks ??

**Comment by bacongobbler** [comment]
Sounds good to me..

**Comment by helgi** [comment]
healthchecks are already configurable, including timeout and initial delay

Why wouldn't apps do healthchecks by default? That's how deis v1 works

**Comment by bacongobbler** [comment]
> Why wouldn't apps do healthchecks by default? That's how deis v1 works

That's untrue. Health checks are disabled by default in Deis v1 unless [`HEALTHCHECK_URL` is set](https://github.com/deis/deis/blob/master/controller/api/models.py#L373-L374). :)

**Comment by helgi** [comment]
Interesting... We could turn this all off. I know in v1 there was a tcp check done to the service to see if the containers were up. Maybe that's what I was thinking about?

**Comment by bacongobbler** [comment]
That could be it. I know that we check to see if deployed containers are up after we've scheduled them, but that's about it for mandatory health checking.

**Comment by helgi** [comment]
@smothiki Feel free to pull out the default behaviour or move it so it only turns on when `HEALTHCHECK_URL` is set. That should solve this

**Comment by smothiki** [comment]
@helgi for now  let's remove health check which helps in giving demos. Lets make HEALTHCHECK_URL a different PR

**Comment by helgi** [comment]
You will have to make sure then if you set `HEALTHCHECK_PORT` that it pulls in other defaults, that was the point of adding the defaults initially was to let people set one item and the system would try to add sane other defaults so the probes would be able to do their job.

**Comment by smothiki** [comment]
Previously there was only one image which already has slug in it. Now the APP pulls the slug from S3 and un tars slug and starts APP. pulling slug from S3 time is not constant and varies according to slug size and network speed. So we should have larger intial delays  .

**Comment by helgi** [comment]
Yeah, feel free to update the defaults to something higher. And also removing the parts that specifically sets the defaults when an app is created. I just want us to set defaults if a user is setting only part of the required `HEALTHCHECK_*` configs

**Comment by smothiki** [comment]
The default initial delay would be very high for build pack apps and falls back to configured value after config set.

**Comment by helgi** [comment]
:+1:

**Comment by krancour** [comment]
fwiw, I agree that healthchecks are a factor in this, but I also am not positive that slow startup time is to blame.  See deis/deis#4263.  It documents unexplained latency in requests to the example Ruby app.

**Comment by krancour** [comment]
I just tried putting that to the test by manually removing the readiness and liveness probes from the RC then killing the pod to let it be replaced by a new one with new configuration sans probes.  It didn't help the situation at all and there's not a lick of anything in the failed containers' logs.

**Comment by krancour** [comment]
This could be a builder issue, actually.  Consistently, I am seeing that the `SLUG_URL` specified in the app's slugrunner is an address for a slug that is _not_ present in object storage.  Looking at the build output, there is agreement on what the URL _is_ and there is no obvious error in the upload.

I'm wondering if uploading and downloading slugs using the `--quiet` flag is a bad idea.  If there are failures in either of those, I think we should see them.

cc @arschles

**Comment by mboersma** [comment]
Looking at this with @smothiki, it appears that minio didn't finish assembling the final object from the multipart bits. Inside the minio container after such a `git push` error, we see this:
```console
$ ls git/home/casual-barbecue\:git-e1590887/push/
$tmpobjectslug.tgz408442165
slug.tgzQTNjyzbbkUjuBRXPYBY6WmXkmaiCAtgGd4Ew9BHZcg8r-3y0a80b7976a21f21ecb8c17930344650b$2-$multiparts
slug.tgzQTNjyzbbkUjuBRXPYBY6WmXkmaiCAtgGd4Ew9BHZcg8r-3y8434c3443f4514a297277c9f4c6c33c7$1-$multiparts
slug.tgzQTNjyzbbkUjuBRXPYBY6WmXkmaiCAtgGd4Ew9BHZcg8r-3y85557f79235dc68839bfbb09a4d24115$4-$multiparts
slug.tgzQTNjyzbbkUjuBRXPYBY6WmXkmaiCAtgGd4Ew9BHZcg8r-3yf961468e9549c349872b3c5cb0a50535$3-$multiparts
```
Next I'll try running minio with any available debug or verbose flags to see if there was an actual error reported.

**Comment by sgoings** [comment]
Could this be the same issue happening on CI? https://ci.deis.io/job/deis-v2-e2e/338/console
