### ISSUE TITLE
Document how to use workflow with an external database

### ISSUE THREAD

**Issue by krancour** [deis/workflow#37]
This is for those wishing to stick with the notion of "stateless platform" and utilize RDS or similar.

**Comment by rimusz** [comment]
:+1:

**Comment by bacongobbler** [comment]
Part of this has been documented: [Configuring Object Storage](https://github.com/deis/workflow/blob/5652eeff2643387f204eff93fadc34982a97b165/src/installing-workflow/configuring-object-storage.md)

We still need to flesh out how one can completely replace the database with RDS.

**Comment by bacongobbler** [comment]
related to #79

**Comment by arschles** [comment]
@krancour is this done now?
