### ISSUE TITLE
unable to ping registry endpoint

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#385]
After trying to deploy an app (`deis pull metabase/metabase`), I am getting an `unable to ping registry endpoint` error:

```
$ kd logs deis-controller-3e686
INFO [metabase]: olalonde deployed metabase/metabase
INFO Pulling Docker image metabase/metabase:latest
INFO Tagging Docker image metabase/metabase:latest as 10.0.239.32:80/metabase:v4
INFO Pushing Docker image 10.0.239.32:80/metabase:v4
INFO [metabase]: unable to ping registry endpoint https://10.0.239.32:80/v0/
v2 ping attempt failed with error: Get https://10.0.239.32:80/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.0.239.32:80/v1/_ping: tls: oversized record received with length 20527
ERROR:root:unable to ping registry endpoint https://10.0.239.32:80/v0/
v2 ping attempt failed with error: Get https://10.0.239.32:80/v2/: tls: oversized record received with length 20527
```

I just installed this cluster (workflow-v2.1.0, k8s v1.2.4) on AWS, following the instructions at https://deis.com/docs/workflow/installing-workflow/ and this is the first app I attempt to deploy.

I am guessing this has to do with the warning at the bottom of https://deis.com/docs/workflow/installing-workflow/system-requirements/:

```
Versions prior to 2.2 require '--insecure-registry' to function properly. Depending on your Kubernetes and Docker configuration, setting EXTRA_DOCKER_OPTS="--insecure-registry=10.0.0.0/8" may be sufficient.
```

However, as a noob, it's not clear to me whether 2.2 refers to the workflow chart or Kubernetes version. It's also not clear to me where I should be setting `EXTRA_DOCKER_OPTS="--insecure-registry=10.0.0.0/8"`. Do I need to set it with `deis config:set` on all my apps :/?

Finally, this warning should probably instead be part of the main "Installing Workflow" instructions since it seems to be a required step currently and I'm guessing not everyone is going to read to the bottom of System Requirements.

**Comment by bacongobbler** [comment]
In the quickstart documentation for AWS, it used to mention that you need to `export KUBE_ENABLE_INSECURE_REGISTRY=true` in order for the registry to work. Unfortunately this documentation was removed in #370, which you got caught in the middle of it. We plan to release v2.2 tomorrow if all goes well in testing if you can hold off, otherwise just re-provision a new cluster with that environment variable set and you should be good to go.

> However, as a noob, it's not clear to me whether 2.2 refers to the workflow chart or Kubernetes version.

2.2 refers to the Workflow version, as Kubernetes has not released a v2 release; they're still on v1.3 :)

**Comment by olalonde** [comment]
Fixed by tearing down my k8s cluster and reinstalling everything from scratch, this time with `export KUBE_ENABLE_INSECURE_REGISTRY=true`.

```
./cluster/kube-down.sh
export KUBE_ENABLE_INSECURE_REGISTRY=true
# more export ....
./cluster/kube-up.sh
helmc install workflow-v2.1.0
```

Maybe add `export KUBE_ENABLE_INSECURE_REGISTRY=true` to AWS install instructions?

**Comment by bacongobbler** [comment]
this should be resolved with https://github.com/deis/charts/pull/317, bypassing the need for `--insecure-registry` on the worker nodes.
