### ISSUE TITLE
Add documentation on how to communicate between two applications

### ISSUE THREAD

**Issue by arschles** [deis/workflow#396]
Given that Deis is a platform well-suited for running microservices, we should include documentation on the best way for microservices to communicate. As of now, we're saying that DNS is the best way to do so.

**Comment by onbjerg** [comment]
Amazing. This is just the answer I was looking for, and then it's the first issue on GitHub.

Is DNS in Deis the same as DNS in k8s?

**Comment by bacongobbler** [comment]
Sorta. We're referring to how two applications communicate, and that would be through the router. We eventually want to get to the point where an application can discover it's own processes which will be through DNS but that is not available at the moment.

**Comment by onbjerg** [comment]
Oh, alright. Thank you for the swift answer.

**Comment by bacongobbler** [comment]
We now have [a blog post on how two apps communicate](https://deis.com/blog/2016/private-applications-on-deis-workflow/). I can write up a little blurb in the docs about it.

**Comment by bacongobbler** [comment]
closed via #723.
