### ISSUE TITLE
[images] Determine where we want to push built images for v2

### ISSUE THREAD

**Issue by slack** [deis/workflow#4]
We need to have a spot to push images as we progress through the alpha. This location may not be the final location and should ideally not interfere with the Deis V1 images.

**Comment by rimusz** [comment]
We could use Google Container Registry as our v2 sandbox will be on GKE

**Comment by mboersma** [comment]
I think it would be confusing to use the existing repo names, even if we host them elsewhere than Docker Hub. My preference would be something like "deis/router-v2" for now, which would eventually just be "deis/router:v2.0.0" when we ship it.

Also, Deis has been pushing images both to Docker Hub and to quay.io so there is an alternate location, and I think in the future we should continue to do that, at least once we have a release.

**Comment by technosophos** [comment]
I feel like it might politically be in our best interest to not host Kubernetes-focused images on DockerHub. Solomon expressed his feelings about that on Twitter (directed at me) a few days ago. But I'll defer to @sgoings on what place is best.

**Comment by rimusz** [comment]
so we have two options left the Google Container Registry or quay.io :)
quay.io has an advantage that it supports rkt images but for the start GCR could be a better option, as it is quicker to work with.
quay.io is not so quick to use from Europe :(

**Comment by sgoings** [comment]
We will probably have our CI system and release process pushing out identical images to all 3. We'll start with just pushing to Docker Hub unless we deal with consistent image push problems... then we can re address.

**Comment by bacongobbler** [comment]
I think we've finally determined this, and we are using travis to push to both quay and dockerhub.
