### ISSUE TITLE
"Isolating the planes" documentation for Deis v2

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#401]
Deis v1 had some documentation on isolating the planes: http://docs.deis.io/en/latest/managing_deis/isolating-planes/

This made it possible to prevent apps from being scheduled on the same machine as deis-builder for example, which uses a lot of CPU during builds.

It would be nice if a similar procedure was documented for Deis v2 in the documentation.

**Comment by bacongobbler** [comment]
deis-builder is significantly better (referring to CPU) than it once was in v1 and in early versions of v2. You can achieve the same thing by modifying the existing charts for workflow and attaching `nodeSelector` labels to the charts. However we are not going to document how to do this as the charts will change over time, it requires extra administrative effort on the k8s cluster (whereas before we had total control over the setup process of the cluster), and we haven't seen a large amount of users who want this feature. That being said, you are more than welcome to maintain a fork of the charts with these changes and document the process yourself :)

Here's the document on Kubernetes' side for using nodeSelectors in manifests for reference: http://kubernetes.io/docs/user-guide/node-selection/
