### ISSUE TITLE
No information about required CPU cores in "Resource Requirements"

### ISSUE THREAD

**Issue by monaka** [deis/workflow#402]
There is no information about CPU cores in [docs](https://www.deis.com/docs/workflow/installing-workflow/system-requirements/).
It will be the important point to decide cost/stability balance.

(Referencing to  examples of Quick Start, it requires 2 cores x 2 nodes.
But by my experience, I suspect Workflow requires more CPU resources even if it was a smallest set for production.)

**Comment by jchauncey** [comment]
So we are working on this in a few different ways.

* You can now set limits within the chart template files for each resource. These resource limits will be enforced by kubernetes
* We are working on getting better cpu usage data from kuberentes to inform the above point. Right now you must explicitly state your cpu usage to kubernetes in millicores, however, we only capture data in usage/seconds. We are working on a fix that you can see here - https://github.com/deis/monitor/issues/139 to help get data from the kubelet in the proper format.

**Comment by bacongobbler** [comment]
In previous iterations of Workflow there were serious CPU leaks, though now our usage is much lower. The CPU requirements are very low and it doesn't seem to be the limiting factor, though if you have a decent number you'd like to put in the docs that'd be helpful!

**Comment by bacongobbler** [comment]
values.yaml has some commented-out defaults that users can try out and see if it works. Closing!
