### ISSUE TITLE
[proposal] Support process type autoscaling

### ISSUE THREAD

**Issue by slack** [deis/workflow#403]
Developers should be able to define an autoscaling policy per application process type. Under the covers, Workflow should use `HorizontalPodAutoscaling`.

Pre-req: Kubernetes Deployments

Examples:

- `deis autoscale:set web --min=2 --max=10 --cpu-percent=80`
- `deis autoscale:unset web`
- `deis autoscale:list`

If an operator users `deis scale web=5` when the application is set to autoscale, the replica count for the deployment should be set to that value and  the HPA should be left alone.

When recovering from a backup or controller restart the HPA should be set with known values and initial replica count should default to the last user-provided value.  Commands like `deis ps` should use Kubernetes as the source of truth for pods, rather than the postgres database.

**Comment by rimusz** [comment]
👍

**Comment by bacongobbler** [comment]
> Commands like deis ps should use Kubernetes as the source of truth for pods, rather than the postgres database.

I believe this is already true as of https://github.com/deis/controller/pull/359. :)

**Comment by helgi** [comment]
Yeah, no database interaction for Pod listing

**Comment by slack** [comment]
Yeah I know.

**Comment by slack** [comment]
Quick clarification on a few conversations. In the first pass, we should keep the scale factor for an application and the autoscaling configuration decoupled.

If, for example, autoscaling is set to min=5, max=10 and the operator runs `scale web=20`, we should update the replica count for the deployment, but _not_ update the autoscaling configuration.

Same on the other side, if autoscaling is set to min=5, max=10 and the operator runs `scale web=2` we would set the replica count to 2 and _not_ update the autoscaling configuration.

From a UX perspective, the CLI _may_ warn about these commands disagreeing but we shouldn't reject the `scale` API call.

**Comment by rimusz** [comment]
yes, autoscaling should not touch replicasets set by `scale web=2`.
but we should keep the same functionality there as in k8s, autoscaling set takes priority vs `scale`

**Comment by helgi** [comment]
Just to provide more information then here is my example setup

HPA is 2-5, deployment is at 3 (set via scale)
```
k get hpa,deployments
NAME                            REFERENCE                     TARGET    CURRENT      MINPODS     MAXPODS   AGE
scale-thing                     Deployment/nginx-deployment   50%       <waiting>    2           5         45m
NAME                            DESIRED                       CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment                3                             3         3            3           57d
```

I scale deployment to 1
`k scale --replicas 1 deployment/nginx-deployment`

For a while the deployment stays at 1 but with enough time passed it will be kicked back up to 2, due to HPA.

Same thing if I scale the deployment up to 8, confirm 8 replicas are created, wait a little while then HPA will bring it down to 5 (as configured).

I understand the decoupling nature as running the various Kubernetes API calls do not auto-correct for one another except HPA will eventually course correct upwards and downwards.
