### ISSUE TITLE
deis register returns 401

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow#405]
On a clean deis-dev install to our AWS staging cluster I get the following when trying to register - 

```
╰─± deis register https://my.aws.server.com
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version:
username: jchauncey
password:
password (confirm):
email: 
Registration failed: Error:
401 Unauthorized
Unauthorized
```

**Comment by jchauncey** [comment]
Nothing in the router logs -

```
╰─± kl deis-router-27h1e
2016/02/19 20:42:13 INFO: Starting nginx...
2016/02/19 20:42:13 INFO: nginx started.
2016/02/19 20:42:13 INFO: Router configuration has changed in k8s.
2016/02/19 20:42:13 INFO: Reloading nginx...
2016/02/19 20:42:13 INFO: nginx reloaded.
```

**Comment by bacongobbler** [comment]
@jchauncey if you try a raw curl, what do you see? `curl -i -XPOST https://my.aws.server.com -d '{"username": "bacongobbler", "password": "mypassword", "email": "mfisher@deis.com"}'`

**Comment by jchauncey** [comment]
```
╰─± curl -k -i -XPOST https://my.aws.server.com -d '{"username": "bacongobbler", "password": "mypassword", "email": "mfisher@deis.com"}'
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Date: Fri, 19 Feb 2016 21:27:09 GMT
Content-Length: 13

Unauthorized
```

I have tried this with and without https and prefixing `deis.` to my domain name

**Comment by jchauncey** [comment]
Ok I figured it out. Had to hook up the ELB to dns =)

**Comment by pfeodrippe** [comment]
Hi, @jchauncey, I've tried to follow the docs for v2, but still couldn't configure it properly, can you show me how you did it?

**Comment by jchauncey** [comment]
On aws?

**Comment by pfeodrippe** [comment]
Yes

**Comment by jchauncey** [comment]
The router creates an elb instance so go to the load balancer and get the
DNS entry and create a cname record that points to that DNS entry for
`*.your domain.com`

**Comment by pfeodrippe** [comment]
Thanks, man!! It's working =)

**Comment by jchauncey** [comment]
Yup :)
