### ISSUE TITLE
A few components seem to always stream to stderr instead of stdout?

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#409]
I was playing around with Kibana and I noticed a few components (e.g. deis-router) seem to **always** have their `stream` field set to `stderr`. I was wondering if this is intentional or if there might be some problem with my setup.

**Comment by mboersma** [comment]
Are there components other than router where this is true? We need to verify that this is happening and see if it's correct behavior.

**Comment by mboersma** [comment]
@olalonde this is intentional for deis/router at least, although logs should be visible at both `stdout` and `stderr` at the compoent level. See deis/router#5.

If this is still a problem in current Workflow (v2.6.0), could you help us reproduce what you're seeing?

**Comment by olalonde** [comment]
@mboersma I think I was seeing this in my k8s Kibana logs and papertrail logs IIRC (they're off right now). I was thinking I could use `stderr` to detect errors but it seems pretty useless for that :)  I guess it's not really an issue anyway.
