### ISSUE TITLE
rename of script install-v2-alpha.sh

### ISSUE THREAD

**Issue by rimusz** [deis/workflow#423]
we should rename deis cli download script `install-v2-alpha.sh` to `install-v2-beta.sh` when we have beta cut

**Comment by sgoings** [comment]
My thoughts - why not just `install-v2.sh`?

**Comment by rimusz** [comment]
or even just to `install-v2.sh`

**Comment by sgoings** [comment]
Fixed via https://github.com/deis/deis.io/pull/148
