### ISSUE TITLE
release 2.3.0 notes

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow#427]
This section needs to include the deployment file for controller as well

```
Change the workflow-$WORKFLOW_RELEASE/tpl/deis-controller-rc.yaml file:
Remove the KUBERNETES_POD_TERMINATION_GRACE_PERIOD_SECONDS env var
````

We talk about using deisrel but there is no information on how to get it.

**Comment by helgi** [comment]
Missing how to get `deisrel` from http://docs-v2.readthedocs.io/en/latest/roadmap/releases/

**Comment by helgi** [comment]
http://docs-v2.readthedocs.io/en/latest/roadmap/releases/#step-4-publish-release-to-versions-server

This step means nothing to me, where do I find that tool, how do i use it

**Comment by jchauncey** [comment]
This step needs to be reworded because it seems to talk about component releases when it is about the Workflow release -

```
Step 6: Merge and Put CHANGELOG in GitHub Release Notes¶
When testing has completed without uncovering any new showstopper bugs and the charts PR has been reviewed successfully, merge it to master. Then update your local master branch and generate the CHANGELOG with the deisrel tool. Paste that content into an annotation on the new release tag, then push the tag:

git checkout master && git fetch --tags upstream master && git merge upstream/master
deisrel changelog individual workflow $WORKFLOW_PREV_RELEASE HEAD $WORKFLOW_RELEASE | pbcopy
git tag -a $WORKFLOW_RELEASE  # paste the CHANGELOG into your editor and save
git push upstream $WORKFLOW_RELEASE
Paste the same CHANGELOG from the previous step into the body of release notes for deis/charts in GitHub. In the "Release Title" field, use the project & component with its release, such as "Deis Workflow v2.3.0":
```

**Comment by jchauncey** [comment]
`deisrel changelog individual logger v2.3.0` this is how you get the changelog for a component now

**Comment by vdice** [comment]
As discussed internally, as part of addressing this bug we want to add a flowchart of the Jenkins jobs in and/or leading up to a component release pipeline, so a given releaser has a handle on what jobs need to be (potentially) revisited/confirmed.

**Comment by bacongobbler** [comment]
Is this something we can tackle in the 2.6 release or is everyone that is intimate with Jenkins all booked up? I'd be happy to take this on but given my lack of understanding the Jenkins workflow, I'd end up asking someone to guide me through this which probably isn't an efficient use of someone else's time.

**Comment by vdice** [comment]
I'll take over with what has been started by @mboersma.  Specifically, the first PR will be flow diagrams in the github.com/deis/jenkins-jobs README illustrating the stages involved upon the following three actions: 1. Component PR created, 2. Component PR merged, 3. Component tagged (for release).  

After this, I am hazy on what needs addressing/improving in the release docs themselves, based on the (potentially dated) comments above.  Could I solicit help/guidance in this area?

**Comment by mboersma** [comment]
> Could I solicit help/guidance in this area?

I'll make changes to the release docs so we can close this issue before the next release.

**Comment by vdice** [comment]
See https://github.com/deis/jenkins-jobs/pull/238 for flow diagram PR

**Comment by bacongobbler** [comment]
Is this issue considered closed now?

**Comment by mboersma** [comment]
@bacongobbler #525 closes this.
