### ISSUE TITLE
Deploy php application error 

### ISSUE THREAD

**Issue by plispe** [deis/workflow#429]
When I try to deploy php application to deis, I get the following error

git push deis master
Counting objects: 231, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (166/166), done.
Writing objects: 100% (231/231), 371.84 KiB | 0 bytes/s, done.
Total 231 (delta 55), reused 231 (delta 55)
Starting build... but first, coffee!
-----> PHP app detected
-----> Bootstrapping...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I tried the following app https://github.com/deis/example-php.git and I use Deis workflow 2.2.0 on Kubernetes 1.26 on GKE. It must be somethink wrong with php buildpack, because golang application works like a charm.

**Comment by Joshua-Anderson** [comment]
Good catch! I can reproduce as well.
We use the same buildpack as heroku: https://github.com/heroku/heroku-buildpack-php/

It seems like heroku/heroku-buildpack-php#174 could the issue. We're currently using revision `v108`, but the latest revision seems to work.

You can tell your application to use the latest revision with: `deis config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php`

**Comment by Joshua-Anderson** [comment]
We periodically bump all the buildpack revisions. Unfortunately, I think it's too late to make `v2.3.0` but this should make it into `v2.4.0` in a few weeks.
