### ISSUE TITLE
Improvement to docs: ability to dedicate nodes to an app

### ISSUE THREAD

**Issue by andrewho83** [deis/workflow#430]
I would like to have the ability to specify that I want X number of nodes dedicated to my app.  I believe this is possible - just not clear on how to do it in the docs.

**Comment by helgi** [comment]
Looks like the old version of the docs has it but not the new, http://docs.deis.io/en/latest/using_deis/manage-application/

`deis tags` is what you need, however you will have to add labels to each Kubernetes Node for it to match up

**Comment by ultimateboy** [comment]
There is already documentation about `deis tags` in the "Security Considerations" section of the documentation. https://deis.com/docs/workflow/managing-workflow/security-considerations/#application-runtime-segregation

We should probably add a link to this page from within the "Managing Applications" to give more visibility to the docs that are already there.

**Comment by ultimateboy** [comment]
Related: https://github.com/deis/workflow/issues/401
