### ISSUE TITLE
Unexpected a result message from kubectl

### ISSUE THREAD

**Issue by monaka** [deis/workflow#434]
I got an unexpected message by Kubectl when I upgrading Workflow.

This is same as [the doc](https://deis.com/docs/workflow/managing-workflow/upgrading-workflow/)

```
~ $ kubectl --namespace=deis get service deis-router \
>     --output=go-template='{{ index .metadata.annotations "helm-keep" | println }}'
true
```

But at the next step, I got the unexpected message like this.

```
~ $ kubectl --namespace=deis annotate namespace deis helm-keep=true
error: --overwrite is false but found the following declared annotation(s): 'helm-keep' already has a value (true)
```

After adding `--overwrite`, it became similar to the document.

```
~ $ kubectl --overwrite --namespace=deis annotate namespace deis helm-keep=true
namespace "deis" annotated
```

Is it caused by my environment, or a typo in the document?

My environment is...
```
~ $ kubectl version 
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+coreos.cni.1", GitCommit:"89e3af04ef436f049e2e2d169e57ad1712cac375", GitTreeState:"clean"}
```

I'll send the pull request if it is caused by a typo.

**Comment by kmala** [comment]
you got the error because you namespace already has the annotation `helm-keep=true` and hence don't need to do it again.

**Comment by monaka** [comment]
Is this issue caused just by my misreading? Or is it better to add any notices to the document?

**Comment by kmala** [comment]
you can add a notice saying to add annotate by checking first to see if its not present.

**Comment by mboersma** [comment]
The docs prefix it by
>  To add a missing annotation, use `kubectl annotate`

So I think this is clear enough as-is.
