### ISSUE TITLE
Privileged option for Deis Apps

### ISSUE THREAD

**Issue by rimusz** [deis/workflow#450]
Would be handy to have the privileged option, as currently there is no support for persistent storage.
The privileged mode would allow to use NFS/CIFS/GlusterFS clients to mount remote volumes inside containers

**Comment by krancour** [comment]
This sounds contrary to 12factor-- which is where the workflow focus is.  In a 12factor app, you would never mount a file system.  Instead you'd use backing services to handle persistent storage.

I'm not saying _every_ app someone might want to deploy adapts well to that methodology, but for such apps, I believe the best way to handle is to "drop down" to k8s and handle it there, rather than by broadening the scope of workflow.

**Comment by bacongobbler** [comment]
related to @krancour's discussion: deis/deis#231

**Comment by rimusz** [comment]
We should leverage k8s volumes in v2 and yes not every Web App can follow 12factor, but these `no storage` limits are big blockers for many uses of Deis

**Comment by rimusz** [comment]
@krancour what kind of backing services you are talking if e.g. some files need to be access for read/write in Deis App?

**Comment by bacongobbler** [comment]
Please see other discussions related to this topic, where we have discussed this and given the reasons against it until we implement deis/deis#231:

https://github.com/deis/deis/issues/4907
https://github.com/deis/deis/issues/448
https://github.com/deis/deis/issues/4325

The idea is to use S3 credentials to read/write to persistent storage. Eventually when we implement service gateways, the gateways will provide a way to connect to persistent storage, but it'll be done in a similar fashion as recommended today.

**Comment by rimusz** [comment]
thanks @bacongobbler :)

**Comment by krancour** [comment]
@bacongobbler how do you dig up related issues so fast!?!

**Comment by rimusz** [comment]
@krancour he has a chip in his head :)

**Comment by bacongobbler** [comment]
^^

On a more serious note, I was part of those discussions, and keywords like wordpress, drupal, legacy apps will all point to those issues. It's generally the same question popping up again in another form. :)

@rimusz did my explanation give you a way to explain to users how to connect to persistent storage, and shall we close this in favour of deis/deis#231 as the actionable item?

**Comment by rimusz** [comment]
@bacongobbler we can close this one

For now I can tell only one thing for v2 Deis users, v2 supports only stateless Apps, the stateful part needs to run on Kubernertes side
