### ISSUE TITLE
How to change GIT_LOCK_TIMEOUT value ? 

### ISSUE THREAD

**Issue by rpechayr** [deis/workflow#457]
Hello, 

We've been playing with deis for a few days now and noticed that for some large applications that the git push timeout is too low. We've tried to tune deis workflow to make it work but did not find any solution so far.

Our AWS load balancer is correctly configured (3600 seconds) so the timeout does not come from this part. 

We've dived into deis/builder code are are now trying to find a way to update the `GIT_LOCK_TIMEOUT` env var of the builder pod, but it does not seem to work.

I am pretty sure a k8s expert would know how to work around this problem, but I am posting an issue here because the current timeout does not seem sufficient for building large apps, and I guess other people could come across this limitation. 

Thank you for your help.

**Comment by kmala** [comment]
You  might want to change this variable if your build takes long time by default this won't be present in the manifest but you can `kubectl edit deployment/deis-builder --namespace=deis` and then add this environment variable....https://github.com/deis/builder/blob/master/pkg/gitreceive/config.go#L35

**Comment by rpechayr** [comment]
Thanks @kmala, we'll look into it. I am quite surprised though because the error in deis-builder logs seemed to be related to GIT_LOCK_TIMEOUT

**Comment by kmala** [comment]
Can you say the exact error you are getting?

**Comment by rpechayr** [comment]
Wait, we found a way to update `GIT_LOCK_TIMEOUT`(which was the origin of our problem) the hlmc files before the `helmc install workflow-v2.3.0` step described in https://deis.com/docs/workflow/quickstart/provider/aws/install-aws/.

**Comment by bacongobbler** [comment]
cool, since I assume this issue is resolved, I'm going to close this but please re-open with logs/steps if you still require help with this. Thanks!

**Comment by rpechayr** [comment]
No problem. Thank you for your help
