### ISSUE TITLE
Trouble connecting to the database

### ISSUE THREAD

**Issue by krancour** [deis/workflow#461]
As of a couple hours ago, I keep running into this with workflow:

```
$ k get pods
NAME                  READY     STATUS             RESTARTS   AGE
deis-builder-faenw    1/1       Running            0          3m
deis-database-zw9a9   1/1       Running            2          3m
deis-minio-7awtz      1/1       Running            0          3m
deis-registry-fqdlh   1/1       Running            0          3m
deis-router-9daqc     1/1       Running            1          3m
deis-workflow-qua36   0/1       CrashLoopBackOff   5          3m
```

The reason:

```
$ k logs deis-workflow-qua36 --previous
system information:
Django Version: 1.9.3
Python 3.5.1
Django checks:
System check identified no issues (2 silenced).
Health Checks:
Checking if database is alive
There was a problem connecting to the database
```

**Comment by bacongobbler** [comment]
@krancour what are the logs in the database showing? This is expected behaviour while everything is booting up (database relies on minio, workflow relies on the database) and should shake itself out once the database is ready to accept connections and workflow has rebooted (to speed up the CrashLoopBackOff, just delete the workflow pod).

**Comment by krancour** [comment]
This is happening on a fresh install (no db restore) and seems to continue after the db is up.  I'll grab db logs shortly.

**Comment by bacongobbler** [comment]
I've discussed with @krancour offline that this is because the database was not ready at the time of the health check, so it went into a CrashLoopBackOff. Waiting for the controller to restart or killing it (forcing a new pod to boot) fixes this.
