### ISSUE TITLE
CHANGELOG.md is present in most (all?) repos but hasn't been updated since 2.0

### ISSUE THREAD

**Issue by helgi** [deis/workflow#464]
We should either remove all CHANGELOG.md files (or use it to point people to tags) or find a way to update it along with the git tags.

I know there was some back and forth on this before for the scenario of 2.4 is released, `master` is now 2.5, however 2.4.1 needs to be released and a fix is committed to `master` and then pulled into 2.4.1 via cherry-pick - Technically the item would show up under 2.4.1 and 2.5 unless we do some more intelligent way of bringing 2.4.1 back into `master` via Changelogs, etc etc

**Comment by bacongobbler** [comment]
TODO:

 - [ ] remove CHANGELOG.md
 - [ ] remove all scripts under _scripts that are changelog related (e.g. `deis-contributions-since`, `generate-changelog.sh`)
 - [ ] upload changelogs for any old component releases on github

**Comment by bacongobbler** [comment]
OK, so here's an exhaustive list of PRs that once merged, check points 1 and 2:

deis/controller#1091
deis/workflow-cli#253
deis/charts#361
deis/router#264
deis/monitor#145
deis/slugrunner#55
deis/slugbuilder#114
deis/postgres#148
deis/fluentd#55
deis/registry#68
deis/workflow-e2e#327
deis/workflow-manager#102
deis/minio#118
deis/logger#119
deis/dockerbuilder#99
deis/builder#435

Optionally, deis/pkg#26 removes some cruft left over as well, but isn't an official product... More of a byproduct.

**Comment by bacongobbler** [comment]
closing as all CHANGELOGs have been removed. Tracking the upload of old changelogs for previous releases in #531.
