### ISSUE TITLE
Client: "cannot execute binary file" when following v2 guide

### ISSUE THREAD

**Issue by ultimateboy** [deis/workflow#468]
Following the directions to install the deis client (http://docs-v2.readthedocs.org/en/latest/using-deis/installing-the-client/), I get the following:

```
$ curl -sSL http://deis.io/deis-cli/install-v2-alpha.sh | bash
Downloading deis-7ba6255-darwin-amd64 from Bintray...
deis is now available in your current directory.
To learn more about deis, execute:
    $ ./deis --help
```

This provides me a binary that I attempt to execute and get an error, slightly different if I'm on zsh or bash:

```
$ ./deis
zsh: exec format error: ./deis
$ bash
$ ./deis
bash: ./deis: cannot execute binary file
```

From what I can tell, the binary is for the correct platform (OS X El Capitan in this case):

```
$ file deis
deis: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
$ uname -mps
Darwin x86_64 i386
```

Any ideas on what might be causing this? I ended up building the deis client myself and had success, so that's my recommendation for anybody else running into this issue: https://github.com/deis/workflow/tree/master/client

**Comment by slack** [comment]
What system are you running on? Could you provide the output of `$ARCH` and `uname -m` from your system?

We still have references to the alpha material, since we haven't cut beta stuff yet. I'll drop a release checklist ticket to make sure we catch these alpha-isms.

**Comment by ultimateboy** [comment]
OS X El Capitan. I provided the output of uname in the original post. I do not have an $ARCH var, is it as simple as that?!

**Comment by slack** [comment]
Missed the uname output, sorry about that. We set `$ARCH` as part of the curl-pipe script. You pretty clearly ended up with Linux bins.

I'll check the bintray files to make sure we didn't cross the streams when pushing client builds.

**Comment by vdice** [comment]
Hey @ultimateboy, the fix will need a bit of time to travel through the pipeline before legit binaries reach bintray... thank you for the catch and for your patience!

**Comment by vdice** [comment]
Latest is now on [bintray](https://bintray.com/deis/deisci/deis/2d933d7/view#files) - take a look when you get a chance and let us know if you are still seeing issues.  Thanks!

**Comment by ultimateboy** [comment]
Works great now. Thanks for the quick fix!
