### ISSUE TITLE
Automate builder/database secrets backup/restore on install/upgrade

### ISSUE THREAD

**Issue by dtomcej** [deis/workflow#468]
Deis should be automatically backing up the secrets for the builder and the database on install. Relying on a manual process to backup and restore the key is prone to error, and should not be relied on for consistency (losing your key means your deis installation is toast).

It could be simple: Create backups if they don't exist. If they do, restore from backups.

The manual backup process can be still the "officially supported" process, but having an automatic backup/restore can be a huge safety net protecting users from catastrophic data loss.

If access/security is an issue, perhaps allowing for a separate object store target for secrets could be configured.

When a user configures off-cluster storage, it should be assumed that everything needed to restore a cluster in case of a failure would be there. Expecting keys to be checked into source control either needs to be EXPLICITLY stated, or it should be assumed that it is backed up into object storage.

Thanks!

**Comment by bacongobbler** [comment]
I'm fairly certain this will also be resolved through the new helm client, which will handle the upgrade process without having to backup/restore these keys.

**Comment by bacongobbler** [comment]
`helm upgrade` resolves this use case.
