### ISSUE TITLE
minio & off-cluster storage

### ISSUE THREAD

**Issue by arschles** [deis/workflow#47]
to accomplish #3, workflow needs to check the following in order:

- minio service environment variables
- off cluster storage environment variable (e.g. `DEIS_OFF_CLUSTER_OBJECT_STORAGE_URL`)
- fetcher URL

**Comment by bacongobbler** [comment]
I know you mentioned this in the standup, but I don't see any current need for the controller to go out to the object storage URL to fetch anything. Will that be changing in a follow up PR, and if so what needs to be done to accomodate that?

**Comment by arschles** [comment]
@bacongobbler I'm not familiar with the controller so don't know the answer to that yet. If the controller creates new slugrunners, then it could need to be aware of the storage locations. @mboersma maybe you could answer?

**Comment by arschles** [comment]
@bacongobbler I just talked to @smothiki, who pointed me at https://github.com/deis/workflow/pull/40. That PR will launch slugrunners (which download from a `$TAR_URL`), so controller will have to be aware of both the minio service and external storage env vars
