### ISSUE TITLE
Deis Workflow Upgrade - Controller CrashLoopBackOff

### ISSUE THREAD

**Issue by Immanuel-Daniel** [deis/workflow#471]
I had to reconfigure my deis workflow and I did a clean up of entire deis installation. On Re-installation the controller falls on CrashLoopBackOff with database connectivity issue. I've missed to take a backup of the database-creds and now I'm unable to set up the deis. Please help,

system information:
Django Version: 1.9.8
Python 3.5.2
groupadd: GID '107' already exists
usermod: group 'docker' does not exist

Django checks:
System check identified no issues (2 silenced).

Health Checks:
Checking if database is alive
There was a problem connecting to the database

**Comment by bacongobbler** [comment]
Hey @Immanuel-Daniel, huge apologies for dropping the ball on this one. Have you since fixed this issue by creating a new cluster? I believe there are ways to manually jump into postgres and change the password, then we can update the secret with the username/password set in the database.

**Comment by mboersma** [comment]
This has languished for several weeks, so I'm going to close it. @Immanuel-Daniel if this is still relevant, please comment here or in the Deis Slack #community channel and we will help you troubleshoot.
