### ISSUE TITLE
[question]: Unnecessary wait?

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#483]
Why the wait if ` from 0 to 0 replicas`?

```
DEBUG scaling RC srv-pdf-v137-web in namespace srv-pdf from 0 to 0 replicas
DEBUG waiting for RC srv-pdf-v137-web to get a newer resource version than 151359939 (30s timeout)
10.2.112.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.2.112.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
DEBUG waited 10s so far for a new resource version
```

**Comment by aledbf** [comment]
#488 fixes this behavior

**Comment by helgi** [comment]
I actually want to keep it open until I figure out if we need to wait on the resource version to be updated

**Comment by helgi** [comment]
I'm just going to close this since we do need to wait for resource versions to update if things are moving along with new replicas
