### ISSUE TITLE
Bug: deleting cert-bearing secret that is still needed

### ISSUE THREAD

**Issue by krancour** [deis/workflow#498]
See https://github.com/deis/router/issues/142

If a single cert is associated to n > 1 domains _of the same app_, detaching that cert from any one of those domains results in the removal of the secret containing the cert from that app's namespace in k8s.

A guard should probably be introduced to ensure that the cert-bearing secret sticks around in this scenario by checking how many domains of the app in question still remain associated to the cert after the detachment from the domain in question.  If > 0, then the secret should not be deleted.

**Comment by helgi** [comment]
Can you verify if https://github.com/deis/workflow/pull/492 took care of it?
