### ISSUE TITLE
allow access to k8s secrets via app environment variables

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/workflow#508]
I'ld like to be able for my app to be able to access specified k8s secrets. Perhaps this could be done at "deis create" or perhaps with a Procfile extension. Not sure what the best approach would be.

**Comment by helgi** [comment]
Right now doing confit:set creates a per version secret. What are you trying to achieve?

**Comment by jwalters-gpsw** [comment]
Just passing in S3, Slack creds/tokens, etc

**Comment by helgi** [comment]
You could do that using config:set if you want that per app. However you'd be able to see the values doing a config:list so they aren't fully secret but at least use the kubernetes primitivies (secrets)

**Comment by tryggth** [comment]
Actually, that will work for the short term. Thanks!

**Comment by jwalters-gpsw** [comment]
Actually, that will work for me. Thanks
