### ISSUE TITLE
GCE: Break connection after 10 min deployment.

### ISSUE THREAD

**Issue by zag2art** [deis/workflow#515]
I've installed workflow on Google Container Engine, trying to deploy an app. It breaks after 10 minutes:
```
~/workfiles/idg [master]> git push deis-gprod production
Counting objects: 172633, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (46754/46754), done.
Writing objects: 100% (172633/172633), 82.20 MiB | 3.13 MiB/s, done.
Total 172633 (delta 129865), reused 165534 (delta 124087)
Starting build... but first, coffee!
Step 1 : FROM dmapper/baseimage:v2.0.0
---> eec6d6fbd455
Step 2 : ADD . /app
---> 0dbc487f4940
Removing intermediate container a804c8383554
Step 3 : RUN echo

....

fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```
I've read the https://github.com/deis/router/pull/94/files about idle connections. But it's not an idle connection. All the 10 minutes I'm getting deployment log.

We have quite a big app. Usually it takes us a half an hour to deploy it (using deis 1.0 with baseimage and Dockerfile in DigitalOcean).

What could it be? How can I fix this?

**P.S.** Workflow version is 2.5.0

**Comment by kmala** [comment]
By default the builder waits for 15 min for the build to complete(https://github.com/deis/builder/blob/f8cc20b429784824d3bf6b3f1059f9b219bf60c7/pkg/gitreceive/config.go#L35)...you can override it using `BUILDER_POD_WAIT_DURATION` env variable in the builder deployment template `kubectl edit deployment deis-builder --namespace=deis`

**Comment by zag2art** [comment]
I don't think this is the right reason because it breaks exactly after 10 minutes. See the logs:
```
~/workfiles/idg [master]> date; BUILDER_POD_WAIT_DURATION=9000000 git push deis-gprod production; date;
Fri Sep 30 09:41:07 MSK 2016
Counting objects: 174057, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (47474/47474), done.
Writing objects: 100% (174057/174057), 82.43 MiB | 2.95 MiB/s, done.
Total 174057 (delta 130933), reused 166551 (delta 124772)
Starting build... but first, coffee!
Step 1 : FROM dmapper/baseimage:v2.0.0
---> eec6d6fbd455
Step 2 : ADD . /app
---> d45a3954cadb
Removing intermediate container 2c05b324678d

// ... another logs

[1]  39% 1234/2470 build modules
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Fri Sep 30 09:51:09 MSK 2016
~/workfiles/idg [master]>
```

**Comment by kmala** [comment]
can you change the `GIT_LOCK_TIMEOUT` from 10 min to something more on the builder deployment  https://github.com/deis/builder/blob/master/pkg/sshd/config.go#L17  and see if it helps

**Comment by zag2art** [comment]
Didn't help as well.
```
~/workfiles/idg [master]> date; GIT_LOCK_TIMEOUT=15 git push deis-gprod production; date;
Fri Sep 30 10:10:16 MSK 2016
Counting objects: 174057, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (47474/47474), done.
Writing objects: 100% (174057/174057), 82.43 MiB | 3.90 MiB/s, done.
Total 174057 (delta 130932), reused 166552 (delta 124772)
Starting build... but first, coffee!
Step 1 : FROM dmapper/baseimage:v2.0.0
---> eec6d6fbd455
Step 2 : ADD . /app
---> 40b50cec397f
Removing intermediate container 0f7de2dc4a36
Step 3 : RUN echo 
// ..

 51% 436/638 build modules
 51% 437/638 build modules
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Fri Sep 30 10:20:17 MSK 2016
```

**Comment by zag2art** [comment]
Hm, how do I change GIT_LOCK_TIMEOUT in the builder itself? Is there a easy way to change it right inside the created GCE container?

**Comment by zag2art** [comment]
Just tried to change config for builder using: "kubectl edit deployment deis-builder --namespace=deis"
Set up both `BUILDER_POD_WAIT_DURATION=3000000` and `GIT_LOCK_TIMEOUT=50. Didn't help. Still failing in 10 min.

**Comment by kmala** [comment]
is there anything in the builder logs?

**Comment by bacongobbler** [comment]
ping

**Comment by zag2art** [comment]
Sorry, they switched me to another task temporary. I close the issue for a while and then reopen it again.

**Comment by miracle2k** [comment]
I am seeing the same thing on Azure.
