### ISSUE TITLE
Doc issue: once installed, what's next?

### ISSUE THREAD

**Issue by cdupont** [deis/workflow#532]
Hi, I'm following this to install DEIS;
https://deis.com/docs/workflow/installing-workflow/

It's working, but doesn't says what to do next!
So I try:
https://deis.com/docs/workflow/users/registration/

But how to retrieve the controller URL?? ("supplied by your Deis administrator")

Cheers

**Comment by bacongobbler** [comment]
Hey @cdupont, I'm assuming you're using openstack as your provider but this information is documented in the [quickstart documentation](https://deis.com/docs/workflow/quickstart/). [This document](https://deis.com/docs/workflow/quickstart/deploy-an-app/) is the follow-up document to installing Workflow, and it describes how to retrieve the controller URL.

Hope this helps!

**Comment by cdupont** [comment]
I see, thanks!
Maybe we can add a link back to the original page?
