### ISSUE TITLE
[doc] which version to install?

### ISSUE THREAD

**Issue by cdupont** [deis/workflow#538]
Which version to install?
In https://github.com/deis/workflow/releases latest version if 2.5.0 but in https://deis.com/docs/workflow/installing-workflow/ it's v2.6.0

**Comment by bacongobbler** [comment]
It looks like we missed a step with our new release process. Thanks for catching that! The latest version is v2.6.0 which was released last week.

@mboersma do you think it's fair to tag the docs at https://github.com/deis/workflow/commit/f06e7bcfd8e50d8a4e899744f615b1ac93824bd7?

**Comment by mboersma** [comment]
> do you think it's fair to tag the docs at f06e7bc?

Yes indeed. Sorry about that oversight!

**Comment by mboersma** [comment]
Workflow v2.6.0 docs are now tagged here: https://github.com/deis/workflow/releases/tag/v2.6.0
