### ISSUE TITLE
Not all Github comments make it to Slack

### ISSUE THREAD

**Issue by helgi** [deis/workflow#552]
It seems that some comments on Github do not make it to slack, for example https://github.com/deis/workflow/pull/551#discussion_r83250083 - My "Fixed" comment did not and @bacongobbler has seen this a few times

I wonder if it is an option in GH or the Slack integration that simply needs to be "turned on", new notifiction types or similar

**Comment by bacongobbler** [comment]
haven't seen this crop up in a long time.
