### ISSUE TITLE
Make `deis config:push` accept a file as parameter

### ISSUE THREAD

**Issue by EDeijl** [deis/workflow#560]
I sometimes have multiple `.env` files in my project directory (for example: `.env.staging`, `.env.development`, `.env.production`) And it would be great if I could set the config of an application to the correct `.env` file without having to copy files around to the correct name.

**Comment by mmacvicar** [comment]
I believe there is an option for that already:
  -p <path>, --path=<path>
    a path leading to an environment file [default: .env]

deis config:push -p .env.production

**Comment by EDeijl** [comment]
Aaah alright, In that case, maybe it should be documented in the [managing app configuration](https://deis.com/docs/workflow/applications/managing-app-configuration/) section of the documentation? Or is it documented somewhere else?

**Comment by bacongobbler** [comment]
It is documented in 'deis help config:push'. We don't usually document every client option flag available in the docs. Does that work for you?

**Comment by EDeijl** [comment]
Works for me, I'll close the issue then.
