### ISSUE TITLE
Seperate limits:set <value> for requests/limits in Kubernetes

### ISSUE THREAD

**Issue by zinuzoid** [deis/workflow#562]
refer to: https://deis.com/docs/workflow/applications/managing-resource-limits/
`Limits set on a per-process type are given to Kubernetes as both a request and limit.`
`$deis limits:set web=64M`
`$deis limits:set web=250m --cpu`

Currently, there's no way to set pod's cpu, memory limits separately from requests. For example, I want to set only pod cpu limit to 1 unit but not cpu request, so it won't try to reschedule pods out of current Kubernetes node even there's 0% cpu usage.

I just went through Kubernetes docs http://kubernetes.io/docs/user-guide/compute-resources/ seems to be straightforward to add a new parameter to Kubernetes.

Not sure if this makes sense to you guys? If it's ok I can contribute a pull request for this one.

**Comment by kmala** [comment]
This will be very similar to the way limits work and should be pretty easy to implement. it will be awesome to have a PR and feel free to bug us if you have any issues/doubts working on it.

**Comment by zinuzoid** [comment]
Thanks for the green light. :green_heart:

To keep backward compatibility, a current command can do something like this.
`$deis limits:set web=250m cmd=500m --cpu`
I propose
`$deis limits:set web=0m/250m cmd=100m/500m --cpu`
which is add another value(requests/limits) in each key pair. would this format make sense?

**Comment by kmala** [comment]
i think the docs needs to be changed as we don't set the requests on setting the limits. i would like to have have similar to limits for requests like `$deis requests:set web=250m cmd=500m --cpu`.
cc @bacongobbler @mboersma @slack

**Comment by zinuzoid** [comment]
I have a concern for `requests:set` approach. refer to Kubernetes docs: http://kubernetes.io/docs/user-guide/compute-resources/
> If the requests values are not specified, they are set to be equal to the limits values by default

If we don't send `requests` together with `limits` we might reset their value.

**Comment by kmala** [comment]
yes.. i missed it in the docs that they are defaulted.
 i think having to send them together will make it tough to unset individual limit/request. Can you write a small proposal on how set and unset would work as per you.

**Comment by zinuzoid** [comment]
### Set requests/limits
Set only limits
`$deis limits:set web=-/250m cmd=-/500m --cpu`
I want to avoid using zero value. `-` will map to `nil` in deis-controller. It should mean fallback to Kubernetes default value.
I'm not quite like this `-` approach, maybe you have a better idea?

Set both requests/limit
`$deis limits:set web=100m/250m cmd=400m/500m --cpu`

Set both requests/limit with same requests/limits value (backward compatibility)
`$deis limits:set web=250m cmd=500m --cpu`

Set only requests - not possible refer to Kubernetes docs
> Please note that limits must always be greater than or equal to requests.
> 0 <= request <= limit <= Infinity

### Unset requests/limits
Unset both requests/limits otherwise you can use `limits:set` to override some value
`$deis limits:unset web cmd --cpu`

**Comment by kmala** [comment]
Even though i am not super happy with `-` or setting both at the same time in this way but this is the simplest way to get this done with out much hassle.But i would to like to have another opinion on this. @bacongobbler what do you think about this?

**Comment by bacongobbler** [comment]
As long as it's backwards-compatible with the current commands, LGTM.

**Comment by zinuzoid** [comment]
I just got back to Kubernetes docs a bit and realize that we don't really need `-`.
eg. If we set `web=-/250m` then Kubernetes will default requests value to be the same as limits, which is equal `web=250m`.
If we have to specify the value if we don't want Kubernetes to default for us. eg. `web=0/250m`.
So, I don't see use case for `-` here anymore.

Here's the simplified propose.
### Set requests/limits
Set only limits
`$deis limits:set web=0/250m cmd=0/500m --cpu`

Set both requests/limit
`$deis limits:set web=100m/250m cmd=400m/500m --cpu`

Set both requests/limit with same requests/limits value (backward compatibility)
`$deis limits:set web=250m cmd=500m --cpu`

Set only requests - not possible refer to Kubernetes docs
> Please note that limits must always be greater than or equal to requests.
> 0 <= request <= limit <= Infinity

### Unset requests/limits
Unset both requests/limits otherwise you can use `limits:set` to override some value 
`$deis limits:unset web cmd --cpu`

**Comment by kmala** [comment]
fixed in #565
