### ISSUE TITLE
Have one place to install workflow and refer it instead of duplicating

### ISSUE THREAD

**Issue by kmala** [deis/workflow#570]

**Comment by bacongobbler** [comment]
@mboersma @vdice or @kmala do you remember why we opened this ticket (i.e. where in the docs is the duplicate information)?

**Comment by kmala** [comment]
https://github.com/deis/workflow/blob/master/src/quickstart/provider/aws/install-aws.md 
https://github.com/deis/workflow/blob/master/src/quickstart/provider/gke/install-gke.md
https://github.com/deis/workflow/blob/master/src/quickstart/provider/vagrant/install-vagrant.md
https://github.com/deis/workflow/blob/master/src/quickstart/provider/azure-acs/install-azure-acs.md
All these say almost the same info and steps.

**Comment by mboersma** [comment]
I *thought* the idea was to reduce the amount of copy-and-pasted content between the several "Quick Start" installation paths. `sphinx` had an `include` directive, but `mkdocs` doesn't, so that would either require some trickery or rearrangement of content into general and specific installation paths with links to each other (which I think we should avoid--it wasn't user-friendly in Deis v1 when we had that).

**Comment by mboersma** [comment]
Maybe there is a Markdown pre-proceesor or `mkdocs` extension that allows for include-type blocks? In Deis v1 we had directives like this throughout the install docs to keep things [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself):

```.. include:: ../_includes/_generate-discovery-url.rst```

If there's no such mechanism, I think we should close this issue and live with the duplication. Users *really* did not appreciate being told "go here for general DNS setup instructions, then return to this AWS-specific guide," and that seems like the only other solution.

**Comment by vdice** [comment]
@mboersma thanks for researching; I'll take a look as well.  

I definitely agree if there isn't such an `include` solution we should stick w/ the duplication.

**Comment by bacongobbler** [comment]
https://pypi.python.org/pypi/markdown-include exists and can be installed as an extension of mkdocs. I can tackle this.
