### ISSUE TITLE
"deis registry:set" creates a new release (AWS ECR)

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#574]
I have setup a CI/CD pipeline that builds a docker image, pushes it to my private AWS ECR registry and deploys to deis using `deis pull`.

However, since the "the docker login command to authenticate to an Amazon ECR registry with an authorization token that is provided by Amazon ECR and is valid for 12 hours", I have to run `deis registry:set password=${registry_pass}` before each pull.

Since `deis registry:set` creates a new release each time, it slows down the build significantly and causes 2 deployments back to back. I was wondering if there is any workaround for that. I know I could set the AWS ECR registry but another alternative would be nice since I feel like doing that will be a PITA.

**Comment by bacongobbler** [comment]
I'm pretty sure this is what [deis/registry-token-refresher](https://github.com/deis/registry-token-refresher/) is supposed to solve, which was introduced shortly after `deis registry:set` was introduced. Does it refresh the tokens for you, or is there an issue we need to fix?

**Comment by bacongobbler** [comment]
It's [in the README](https://github.com/deis/registry-token-refresher/#about):

> The Registry Token Refresher service creates the imagePullSecret and updates it at regular interval of time for each app(namespace) created by Deis Workflow. The secrets are used by dockerbuilder and controller for authenticating with the private registry.

It should be doing this automatically. If it isn't on v2.10.0 then can you file an issue there?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
