### ISSUE TITLE
Process types can only contain alphanumeric

### ISSUE THREAD

**Issue by robinmonjo** [deis/workflow#580]
Workflow version 2.7.0

At the end of a push I've got this error:

`````
Build complete.
Launching App...
remote: 2016/10/26 16:53:57 Error running git receive hook [publishing release (Unknown Error (400): {"procfile":["Process types can only contain alphanumeric"]})]
`````

My Procfile is good:

`````
web: bundle exec puma ...
worker: ...
worker_critical:  ...
scheduler: ...
`````

I haven't seen this on older version. Any clues ?

**Comment by kmala** [comment]
you shouldn't have `_` in the proctype. This validation is always present but before it wasn't checked during build time because of which there are issues after the app is deployed and i made the validation occur before deploy.
https://github.com/deis/controller/pull/1105

**Comment by bacongobbler** [comment]
https://github.com/deis/workflow-cli/issues/247 also explains the issue.

**Comment by robinmonjo** [comment]
Thank your for the quick answer, and sorry for not correctly reading the error :(
