### ISSUE TITLE
Proposal: How CI signs Deis Helm charts

### ISSUE THREAD

**Issue by vdice** [deis/workflow#585]
After creating a general, "How might organizations sign Helm charts?" ticket in https://github.com/kubernetes/helm/issues/1448, a couple of concrete, CI-centric proposals specifically applicable to Deis have bubbled to the surface.  

Here they are presented to hopefully gain consensus on which (if any) direction we should move forward with, assuming these CI/automated approaches are favored over manual signing by a Deis maintainer at the end of each chart release.
## Single Signatory

<img width="848" alt="single_signatory" src="https://cloud.githubusercontent.com/assets/9322017/19779344/ed3253d4-9c3d-11e6-9bdc-73969415f62f.png">

_Benefits_: Adheres to traditional single-signatory PGP model, Perhaps least amount of setup work (depending on api server effort)

_Drawbacks_: Manual setup and maintenance of signatory machine (most likely), Single point of failure/holdup, TBD on whether or not we want the signing key material in another 'safe' place if machine not responsive/down

_Resources Needed_: 
- An ec2/gce instance
- A minimal REST api server on said instance to handle sign requests

_Effort_: Medium
## Multiple Signatories

<img width="827" alt="multiple_signatories" src="https://cloud.githubusercontent.com/assets/9322017/19779564/dbb24d02-9c3e-11e6-8ea5-dea0a264e38a.png">

_Benefits_: Employs already-utilized CI nodes for signing, Supports dynamic addition/removal of signatories

_Drawbacks_: Perhaps against the grain of how PGP is traditionally meant to be used, Signing key exists temporarily on not-as-locked-down-as-above node (although for absolute minimum amount of time)

_Resources Needed_: 
- Vault setup from scratch (full-bore HA Consul backend?)

_Effort_: Medium/High (looking for those with more familiarity/experience with Vault to inform)

**Comment by bacongobbler** [comment]
Personally while I think it'd be cool to do something like Vault, I'd veer more towards option 1 (Single Signatory) as a first step simply because of time involved setting up the service + bus factor + training for supporting the infra when it goes down/upgrades etc. If the single signatory goes down or has an issue, it's just a relatively simple API server from the sounds of it. Updates would be as simple as rolling the version and deploying to prod. In comparison, Vault would be much more difficult to debug/stand up, and would likely have a more involved upgrade process.

This is all off the cuff of my hand, so if someone else has more experience with maintaining Vault in production, please let us know if this sounds simpler than we're making it sound.

**Comment by vdice** [comment]
A closing remark to document where we ended up for the first stage for signing Helm charts as part of our CI chart release process.  We created a dedicated Jenkins node for this task, setting it up both with restricted access as compared to the other/standard Jenkins nodes and to be the sole holder of the actual signing keypair.

Now that this work is done, the CI flow for releasing a Workflow chart looks like:
* git tag the workflow repo with release (say, `v1.2.3`)
* tag event triggers job to package and push candidate `workflow` chart to staging
* triggers e2e job vetting candidate chart as fetched from staging
* if successful, triggers migration of candidate chart from staging to production
* finally, the production-hosted chart is fetched and signed by the signatory node, whereupon the resulting `workflow-v1.2.3.tgz` and `workflow-v1.2.3.tgz.prov` files are uploaded to production

Here's a basic diagram of the infra:

<img width="932" alt="deis_signatory_node" src="https://cloud.githubusercontent.com/assets/9322017/20149893/71eda7e0-a670-11e6-9464-c5a0ea88671f.png">
