### ISSUE TITLE
Change default SSL cert policy in client

### ISSUE THREAD

**Issue by vpetersson** [deis/workflow#589]
Upon deploying a staging environment, I realized that the default ssl_verify policy is to not verify the SSL certificate. That seems a bit risky to me.

```
$ deis login https://deis.stage.foobar.com
username: jdoe
password:
Logged in as jdoe
Configuration file written to /Users/jdoe/.deis/client.json
$  cat ~/.deis/client.json
{"username":"jdoe","ssl_verify":false, [...] }
 ```

While it is true, that you can pass on the flag `--ssl-verify=true`, it would make more sense IMHO to have this as the default.

Moreover, looking at the help, you get the following:

```
$ deis login --help
[...]
  --ssl-verify=false
    disables SSL certificate verification for API requests
```

I personally interpret that as that the default option would be that SSL verification would be enabled.

**Comment by bacongobbler** [comment]
Thanks @vpetersson. There is a duplicate ticket at https://github.com/deis/workflow-cli/issues/264 so I'm going to close this in favour of that one. Thanks!

**Comment by bacongobbler** [comment]
Also please check out https://github.com/deis/workflow-cli/pull/265 for the corresponding PR.

**Comment by vpetersson** [comment]
Thanks, @bacongobbler.
