### ISSUE TITLE
[install] Document install process for alpha

### ISSUE THREAD

**Issue by slack** [deis/workflow#6]
We need a common location for alpha instructions. Ideally, this would/could use helm, but should include all the info needed to stand up the deis alpha.

Relevant alpha components:
* deis/postgres#5
* deis/etcd#7
* deis/registry#1
* deis/minio#1
* deis/builder

**Comment by bacongobbler** [comment]
With deis/charts#30 this should be as easy as "stand up your kubernetes cluster, configure kubectl, install helm, run `helm update` then run `helm install deis`".
