### ISSUE TITLE
Proposal: Allow option of integrating Workflow user authn/authz with k8s authn/authz

### ISSUE THREAD

**Issue by aboyett** [deis/workflow#601]
Kubernetes provides pluggable [authentication (authn)](http://kubernetes.io/docs/admin/authentication/) and [authorization (authz)](http://kubernetes.io/docs/admin/authorization/) mechanisms for the k8s api. Thes could simplify the use and management of Workflow in a couple ways:

1) User registration doesn't need to be done through Workflow itself, users are automatically managed based on the upstream authn mechanism(s) configured in k8s.

2) If the Workflow permissions model is augmented to support user groups, membership info could be fetched from the k8s authn provider (ie: GitHub Teams.)

3) Given a sufficiently privileged service account the Workflow controller could automatically apply RBAC on k8s objects as users call `deis perms:` commands.
This could allow users to run select `kubectl` commands against these resources[1]

This represents multiple individual feature requests but I thought it might be worth discussing the larger picture to give context for the individual feature requests. If a given feature aligns with envisioned direction of Deis Workflow then I'll create a specific request for that feature. So far in the above use-case I think I'm requesting four separate features:

1) Back Deis Workflow authn with k8s authn
2) Impelement user groups in Deis Workflow
3) Integrate k8s authz with Deis Workflow permissions

[1] For example, the user may want to attach a JVM debugger to a specific pod in a Workflow application. The Deis Workflow (and the upstream Heroku) interface(s) don't provide any verbs suitable for such an action, but `kubectl port-forward` could allow the user to connect to the JVM in Workflow from the IDE on their local machine.

**Comment by aboyett** [comment]
I accidentally posted this issue before I finished writing the description, I've edited the original post to complete the partial sentence.

**Comment by bacongobbler** [comment]
Yes, it's certainly on our roadmap (cc @mboersma).

Right now we are concerned about backwards compatibility because we still want to support older kubernetes clusters. This is a recent feature and is still in beta, but we are investigating it in tandem with `deis teams` support.

**Comment by aboyett** [comment]
I understand and agree with the Deis team's stance of waiting until features reach a stable status before adding support in Workflow.

To confirm, https://github.com/deis/deis/issues/4173 is the ticket to track regarding teams in Workflow?

**Comment by bacongobbler** [comment]
Yep!

**Comment by mboersma** [comment]
Closing this as a duplicated of deis/deis#4173.
