### ISSUE TITLE
Rollback failed, build logs full of 'Failed handshake: EOF' errors

### ISSUE THREAD

**Issue by danhawkes** [deis/workflow#604]
Background: 

- testing out workflow (2.8.0) on Azure's free trial
- install kubernetes via [kubernetes-anywhere](https://github.com/kubernetes/kubernetes-anywhere)
- deploy the sample app, try a few more git pushes, rollbacks, successfully
- (possibly: start a rollback and terminate shell session while in progress) 
... (come back a few days later)
- app seems to be down (503)
- git push starts a build, but nothing ever happens:

      git push deis master
      Counting objects: 78, done.
      Delta compression using up to 4 threads.
      Compressing objects: 100% (67/67), done.
      Writing objects: 100% (78/78), 12.56 KiB | 0 bytes/s, done.
      Total 78 (delta 20), reused 0 (delta 0)
      Starting build... but first, coffee!
      ...
      ...
      ...

`deis logs`: _(note "s3aws: Path not found" seems suspicious)_

    INFO [testapp]: admin rolled back to v3
    INFO [testapp]: buildpack type detected. Defaulting to $PORT 5000
    INFO [testapp]: buildpack type detected. Defaulting to $PORT 5000
    INFO [testapp]: adding 30s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
    INFO [testapp]: This deployments overall timeout is 150s - batch timout is 150s and there are 1 batches to deploy with a total of 1 pods
    INFO [testapp]: waited 10s and 1 pods are in service
    INFO [testapp]: waited 20s and 1 pods are in service
    INFO [testapp]: waited 30s and 1 pods are in service
    INFO [testapp]: appsettings testapp-2766834 updated
    INFO [testapp]: appsettings testapp-35bd168 updated
    testapp-web-4020771625-wi5sf -- 2016/11/10 18:15:19 Error downloading home/testapp:git-f5b24659/push/slug.tgz (s3aws: Path not found: home/testapp:git-f5b24659/push/slug.tgz)
    INFO [testapp]: buildpack type detected. Defaulting to $PORT 5000
    INFO [testapp]: buildpack type detected. Defaulting to $PORT 5000
    INFO [testapp]: admin rolled back to v4
    INFO [testapp]: This deployments overall timeout is 150s - batch timout is 150s and there are 1 batches to deploy with a total of 1 pods
    INFO [testapp]: adding 30s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
    INFO [testapp]: waited 10s and 1 pods are in service
    INFO [testapp]: waited 20s and 1 pods are in service
    INFO [testapp]: waited 30s and 1 pods are in service
    INFO [testapp]: waited 40s and 1 pods are in service
    INFO [testapp]: waited 50s and 1 pods are in service
    INFO [testapp]: waited 60s and 1 pods are in service
    INFO [testapp]: waited 70s and 1 pods are in service
    INFO [testapp]: waited 80s and 1 pods are in service
    INFO [testapp]: waited 90s and 1 pods are in service
    INFO [testapp]: waited 100s and 1 pods are in service
    INFO [testapp]: waited 110s and 1 pods are in service
    INFO [testapp]: waited 120s and 1 pods are in service
    INFO [testapp]: waited 130s and 1 pods are in service
    INFO [testapp]: waited 140s and 1 pods are in service
    INFO [testapp]: admin rolled back to v2

`kb get pods`:

        NAME                                     READY     STATUS              RESTARTS   AGE
        deis-builder-415246326-pwpir             1/1       Running             1          3d
        deis-controller-1590631305-lry8j         1/1       Running             1          3d
        deis-database-510315365-ezvjv            1/1       Running             0          3d
        deis-logger-9212198-z1wme                1/1       Running             0          3d
        deis-logger-fluentd-85m35                1/1       Running             0          3d
        deis-logger-fluentd-bra9h                1/1       Running             0          3d
        deis-logger-fluentd-jt6h7                1/1       Running             0          3d
        deis-logger-fluentd-w8os7                1/1       Running             0          3d
        deis-logger-redis-663064164-mufff        1/1       Running             0          3d
        deis-minio-3160338312-y6362              1/1       Running             0          3d
        deis-monitor-grafana-432364990-hksij     1/1       Running             0          3d
        deis-monitor-influxdb-2729526471-ypbn4   1/1       Running             0          3d
        deis-monitor-telegraf-bsivz              1/1       Running             1          3d
        deis-monitor-telegraf-p20la              1/1       Running             0          3d
        deis-monitor-telegraf-vhx4k              1/1       Running             1          3d
        deis-monitor-telegraf-w9c86              1/1       Running             0          3d
        deis-nsqd-3264449345-q5f9i               1/1       Running             0          3d
        deis-registry-2182132043-oknzu           1/1       Running             1          3d
        deis-registry-proxy-c9fo8                1/1       Running             0          3d
        deis-registry-proxy-d2t1h                1/1       Running             0          3d
        deis-registry-proxy-rdben                1/1       Running             0          3d
        deis-registry-proxy-y46rl                1/1       Running             0          3d
        deis-router-2457652422-14hmz             1/1       Running             0          3d
        deis-workflow-manager-2210821749-3gt34   1/1       Running             0          3d
        dockerbuild-another-5d313d57-32257c17    0/1       ContainerCreating   0          7h
        dockerbuild-another-5d313d57-c169f9f5    0/1       ContainerCreating   0          6h

`kb logs deis-builder-415246326-pwpir`:

    2016/11/09 22:13:43 Starting health check server on port 8092
    2016/11/09 22:13:43 Starting deleted app cleaner
    2016/11/09 22:13:43 Starting SSH server on 0.0.0.0:2223
    Listening on 0.0.0.0:2223
    Accepting new connections.
    ---> ---> 2016/11/09 22:14:32 Readinesscheck endpoint timed out after 10s
    2016/11/09 22:14:42 Readinesscheck endpoint timed out after 10s
    2016/11/09 22:14:52 Readinesscheck endpoint timed out after 10s
    2016/11/09 22:15:02 Readinesscheck endpoint timed out after 10s
    Accepted connection.
    Accepted connection.
    ---> ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    ---> [ERROR] Failed handshake: EOF
    Accepted connection.
    Accepted connection.
    ---> ---> [ERROR] Failed handshake: EOF
    [ERROR] Failed handshake: EOF
    Accepted connection.
    (and so on)

**Comment by bacongobbler** [comment]
> 2016/11/09 22:14:42 Readinesscheck endpoint timed out after 10s

Perhaps this has something to do on Azure's side? I've seen multiple reported failures specifically on Azure's new cloud infrastructure. We've had problems in the past running both v1 and v2 on their infrastructure due to poor performance and network latency issues.

**Comment by bacongobbler** [comment]
Ah as I'm reading the logs a bit more, yes indeed `> s3aws: Path not found` is your issue, which again may be Azure pod-to-pod networking issues, causing dockerbuilder and minio to be unable to communicate.

> git push starts a build, but nothing ever happens:

That seems to be correct given that the `dockerbuilder` pods have been in `ContainerCreating` status for over 7 hours. It definitely smells like a kubernetes issue here.

**Comment by danhawkes** [comment]
Right, thanks for the quick response! Anything I can do to help debug it here?

**Comment by kmala** [comment]
can you do a describe of the pod `kubectl describe pod dockerbuild-another-5d313d57-32257c17 --namespace=deis` and see the reason for it to be in creating state for so long.

**Comment by danhawkes** [comment]
That one disappeared over night, but here's another showing the same behaviour:

```
Name:		dockerbuild-another-5d313d57-a3ef8932
Namespace:	deis
Node:		7ea81fa9-9292-4d64-b77c-4f2813c8fb93-node-1/10.240.0.6
Start Time:	Mon, 14 Nov 2016 11:13:15 +0000
Labels:		heritage=dockerbuild-another-5d313d57-a3ef8932
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  deis-dockerbuilder:
    Container ID:	
    Image:		quay.io/deis/dockerbuilder:v2.5.0
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
      TAR_PATH:				home/another:git-5d313d57/tar
      SOURCE_VERSION:			5d313d57
      IMG_NAME:				another:git-5d313d57
      BUILDER_STORAGE:			minio
      DEIS_REGISTRY_SERVICE_HOST:	localhost
      DEIS_REGISTRY_SERVICE_PORT:	5555
      DEIS_REGISTRY_PROXY_PORT:		5555
      DEIS_REGISTRY_LOCATION:		on-cluster
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  objectstorage-keyfile:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	objectstorage-keyfile
  docker-socket:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/docker.sock
  default-token-yvgc6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-yvgc6
QoS Tier:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  4m		4m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned dockerbuild-another-5d313d57-a3ef8932 to 7ea81fa9-9292-4d64-b77c-4f2813c8fb93-node-1
```

**Comment by danhawkes** [comment]
Also here's the builder:
```
Name:		deis-builder-415246326-pwpir
Namespace:	deis
Node:		7ea81fa9-9292-4d64-b77c-4f2813c8fb93-node-2/10.240.0.4
Start Time:	Wed, 09 Nov 2016 22:12:32 +0000
Labels:		app=deis-builder
		pod-template-hash=415246326
Status:		Running
IP:		10.244.3.3
Controllers:	ReplicaSet/deis-builder-415246326
Containers:
  deis-builder:
    Container ID:	docker://078b8b51bd5014105785b00edbb2d4197adc0a86eb397e77ae43d55e8c58b73b
    Image:		quay.io/deis/builder:v2.5.4
    Image ID:		docker://sha256:bf06a99550964190cf99efbb910e842c9bde4e5391c2fa1f9e4ace81da79e79d
    Ports:		2223/TCP, 8092/TCP
    State:		Running
      Started:		Wed, 09 Nov 2016 22:13:43 +0000
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Wed, 09 Nov 2016 22:12:45 +0000
      Finished:		Wed, 09 Nov 2016 22:13:43 +0000
    Ready:		True
    Restart Count:	1
    Liveness:		http-get http://:8092/healthz delay=30s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:8092/readiness delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      DEIS_REGISTRY_SERVICE_HOST:	localhost
      DEIS_REGISTRY_SERVICE_PORT:	5555
      HEALTH_SERVER_PORT:		8092
      EXTERNAL_PORT:			2223
      BUILDER_STORAGE:			minio
      DEIS_REGISTRY_LOCATION:		on-cluster
      DEIS_REGISTRY_SECRET_PREFIX:	private-registry
      GIT_LOCK_TIMEOUT:			10
      SLUGBUILDER_IMAGE_NAME:		quay.io/deis/slugbuilder:v2.4.5
      SLUG_BUILDER_IMAGE_PULL_POLICY:	IfNotPresent
      DOCKERBUILDER_IMAGE_NAME:		quay.io/deis/dockerbuilder:v2.5.0
      DOCKER_BUILDER_IMAGE_PULL_POLICY:	IfNotPresent
      DOCKERIMAGE:			1
      DEIS_DEBUG:			false
      POD_NAMESPACE:			deis (v1:metadata.namespace)
      DEIS_BUILDER_KEY:			<set to the key 'builder-key' in secret 'builder-key-auth'>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  builder-key-auth:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-key-auth
  builder-ssh-private-keys:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	builder-ssh-private-keys
  objectstore-creds:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	objectstorage-keyfile
  deis-builder-token-tpgkw:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-builder-token-tpgkw
QoS Tier:	BestEffort
No events.
```

**Comment by bacongobbler** [comment]
> Failed to setup network for pod \"dockerbuild-another-5d313d57-a3ef8932_deis(4d7a6cc8-aa5b-11e6-b9d9-000d3af76add)\" using network plugins \"kubenet\": Failed to retrieve pods from runtime: operation timeout: context deadline exceeded; Skipping pod"

This looks like the underlying platform (kubernetes) is failing. I would submit a ticket to kubernetes-anywhere and see if they have any open issues related to this one.

**Comment by bacongobbler** [comment]
closing as an upstream issue
