### ISSUE TITLE
Design Doc: Outbound Webhook Notifications

### ISSUE THREAD

**Issue by jschneiderhan** [deis/workflow#607]
## Goal

Send webhook notifications to external systems facilitating integration with third party services like Slack and HipChat. Types of events that will trigger webhook notifications include:

- Releases
- Scale events

Allow webhook consumers to be added/removed through the API or the CLI using `webhooks`, `webhooks:add`, and `webhooks:remove` commands.

The goal of this feature is not to integrate directly with a bunch of 3rd party services like Slack and HipChat. That would require Deis to support a different notification format and set of configurations for each service. Instead, a single notification format will sent to consumers with information about the Deis event. The consumers can take these events and do whatever they want with them, such as post messages to Slack or HipChat. If Deis would like to ship with a default consumer that integrates with popular 3rd party services, it can do so at a future time. At first it would be up to users to create their own consumers.

## Code Changes

- Create a new `/apps/<id>/webhooks/` endpoint which supports listing, adding, and removing webhooks
- Update the controller to send events to all webhooks registered for a product when releases and scale events occur
- Ensure the controller retries delivery of webhooks a few times with an exponential back-off
- Add `webhooks`, `webhooks:list`, `webhooks:add`, and `webhooks:remove` commands to the workflow CLI
- Sign events so that clients cat verify they originated from the Deis platform. Travis CI has a neat way of doing this using (https://docs.travis-ci.com/user/notifications#Verifying-Webhook-requests)

## Tests

It should be possible to create a test consumer application in https://github.com/deis/workflow-e2e and verify that it is receiving events.

**Comment by jschneiderhan** [comment]
My team currently makes use of HipChat and PagerDuty in our continuous deployment setup, and would love to keep using them as we move to Deis. I see that outbound webhooks are listed on the roadmap, but asking on Slack it sounds like it's not on the short-term roadmap. Instead of putting effort towards creating some hack that only works for us, I'd love to try and properly implement the feature in Deis.

I put some of my initial thoughts above. If anyone has any feedback, please let me know. I haven't actually discussed this with anyone, so I don't know how far off the mark I am from what was in mind when the item was added to the roadmap.

**Comment by bacongobbler** [comment]
This is an excellent proposal, @jschneiderhan. The idea of a webhook design rather than an events API which users will have to poll is a better overall design and better reflects current use cases.

I think the only change I'd make would be that the CLI commands be `deis webhooks`, `deis webhooks:list`, `deis webhooks:add` and `deis webhooks:remove` rather than `deis workflow`. `workflow` might confuse others since that is the official name of the product (Deis Workflow).

Going with travis' implementation of signing the webhooks also sounds like a great idea. We'd also need to add an endpoint to the API server that displays the public key used to sign webhooks as well as generate a new secret key, but the implementation doesn't sound too hard or over-complicated.

Looks good to me! 👍

**Comment by bacongobbler** [comment]
As far as testing goes, it could be possible to write an end-to-end test for this in https://github.com/deis/workflow-e2e. Potentially it could be an application that is deployed onto the cluster, then a webhook is sent to `appname.k8s.local`, then we check the logs and verify it saw the webhook after creating a new release for the app. Essentially the app would be listening to its own events.

That's just an idea, but you get the picture :)

**Comment by jschneiderhan** [comment]
@bacongobbler oops - using `webhooks` was my intention - that was a slip up. I'll fix that.

Do you think the webhooks should be configured for each app, or should there be a single set for the entire platform?

Take my current use case. We have two product teams, and each has it's own HipChat room. With app-level webhooks, I would have a simple webhook consumer running for each team configured to send messages to their room. With platform-level webhooks, I would have a single more complicated consumer that would figure out which room to send to based on the app specified in message details.

I think I like the app-level webhooks. It allows me to keep my consumer simple, but I may have to run multiple consumer instances, and configure a webhook for every app. I notice that other projects which send webhooks, like Travis, are configured at what would be comparable to the app-level. I could be sold the other way, though.

**Comment by bacongobbler** [comment]
> Do you think the webhooks should be configured for each app, or should there be a single set for the entire platform?

I think per-app is a good design. As you mentioned, each application may only be relevant to a certain slack channel so the webhooks for one app may differ to another.

**Comment by mboersma** [comment]
This was implemented by @bacongobbler in the Workflow v2.10.0 release.

**Comment by jschneiderhan** [comment]
Oh wow, excellent!

**Comment by jschneiderhan** [comment]
https://github.com/deis/controller/issues/1153 for anyone else looking for the implementation.
