### ISSUE TITLE
helmc generate -f does not work

### ISSUE THREAD

**Issue by cdupont** [deis/workflow#609]
I generate my manifests using:

```
$ helmc generate -x manifests workflow-v2.8.0
```
But if I want to regenerate them after some changes, if does not work:
```
$ helmc generate -x -f manifests workflow-v2.8.0
[ERROR] Failed to complete generation: lstat /home/cdupont/.helmc/workspace/charts/manifests: no such file or directory
```

**Comment by bacongobbler** [comment]
can you try re-creating that directory via `mkdir -p /home/cdupont/.helmc/workspace/charts/manifests` then run it again? Sounds like you're missing a directory.

**Comment by cdupont** [comment]
@bacongobbler If I do so and I run `helmc generate -x manifests workflow-v2.8.0` it says:
```
---> Ran 0 generators.
```

**Comment by bacongobbler** [comment]
That's probably because your workspace is empty. Try running `helmc update && helmc fetch workflow-v2.8.0` then run it again.

**Comment by bacongobbler** [comment]
Also it should be `helmc -f -x manifests workflow-v2.8.0`. -f is the force command and does not accept arguments, so you need to make sure the arguments are properly formed.

**Comment by cdupont** [comment]
Thanks baccongobbler, I think the problem was argument order.

**Comment by bacongobbler** [comment]
Awesome, I think we can consider this closed :)
