### ISSUE TITLE
Need more details on external object storage

### ISSUE THREAD

**Issue by krancour** [deis/workflow#61]
I think [this section](https://github.com/deis/docs-v2/blame/master/src/installing-workflow/configuring-object-storage.md#L17-L23) requires more details.

I know @technosophos recently submitted and merged an _awesome_ PR (https://github.com/deis/charts/pull/123) to hypothetically add a consolidated point of configuration for object storage platform-wide.  (In practice, I don't think all components are making use of this yet, but they should.)

I think no section on configuring object storage could be complete without covering this.

**Comment by bacongobbler** [comment]
IIRC @kmala is working on consolidating the object storage configuration, so perhaps he would be the best person to tackle the docs :)

**Comment by kmala** [comment]
I had made changes to the docs apart from the database part which will be done using https://github.com/deis/workflow/pull/138

**Comment by kmala** [comment]
fixed in https://github.com/deis/deis/issues/4966
