### ISSUE TITLE
ship a v2 client for testing

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#61]
now that we've merged #58, the default install docs no longer work because `curl -sSL http://deis.io/deis-cli/install.sh | sh` will install v1.12.2. What we need is for `_scripts/deploy.sh` to ship a v2 client :)

**Comment by arschles** [comment]
@bacongobbler where should `_scripts/deploy.sh` put the client?

**Comment by arschles** [comment]
also, FYI for now there's a deis v2 client at https://storage.googleapis.com/deis-client/deis.tgz. built with `docker run -e GO15VENDOREXPERIMENT=1 -e CGO_ENABLED=0 -v $GOPATH:/go -w /go/src/github.com/deis/workflow/client golang:1.5.2 go build -a -installsuffix cgo -ldflags '-s' -o deis .`

**Comment by bacongobbler** [comment]
@arschles I've got [a fork](https://travis-ci.org/bacongobbler/workflow/builds) which is deploying the client in an S3 bucket, similar to our current jenkins client jobs. I'm just ironing out the kinks before I PR this.

**Comment by arschles** [comment]
sgtm. I'll hold off unless you tell me otherwise @bacongobbler
