### ISSUE TITLE
deis pull deis/example-python-flask resealing in "Error: Unknown Error (400)"

### ISSUE THREAD

**Issue by jmspring** [deis/workflow#620]
Deploying example-go seems to work fine.  However, NodeJS and Python Buildpack approaches are failing.  Logs to deis-controller shown below.  This is Deis on Kubernetes on Azure.  

10.244.4.5 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.8.0"
INFO [rental-undertow]: config rental-undertow-5625e6a updated
INFO [rental-undertow]: admin created initial release
INFO [rental-undertow]: appsettings rental-undertow-e1447ad updated
INFO [rental-undertow]: domain rental-undertow added
10.244.4.5 "POST /v2/apps/ HTTP/1.1" 201 167 "Deis Client v2.8.0"
INFO [rental-undertow]: build rental-undertow-268efdf created
INFO [rental-undertow]: admin deployed deis/example-python-flask
INFO Pulling Docker image deis/example-python-flask:latest
INFO Pulling Docker image deis/example-python-flask:latest
INFO Pulling Docker image deis/example-python-flask:latest
INFO [rental-undertow]: image deis/example-python-flask:latest not found
ERROR:root:image deis/example-python-flask:latest not found
Traceback (most recent call last):
  File "/app/api/models/release.py", line 89, in new
    release.publish()
  File "/app/api/models/release.py", line 136, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 195, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 107, in publish_release
    self.pull(repo, src_tag)
  File "/usr/local/lib/python3.5/dist-packages/backoff.py", line 286, in retry
    ret = target(*args, **kwargs)
  File "/app/registry/dockerclient.py", line 124, in pull
    log_output(stream, 'pull', repo, tag)
  File "/app/registry/dockerclient.py", line 174, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 191, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: image deis/example-python-flask:latest not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 63, in create
    source_version=self.version
  File "/app/api/models/release.py", line 96, in new
    raise DeisException(str(e)) from e
api.exceptions.DeisException: image deis/example-python-flask:latest not found

**Comment by bacongobbler** [comment]
As the error suggests, no Docker image for deis/example-python-flask exists. If you wish to deploy that application, follow the documentation at https://github.com/deis/example-python-flask. `deis pull deis/example-python-flask` won't work. Is there a document you're trying to follow?

FYI `deis pull` fetches an image directly from a registry like dockerhub so buildpacks are not used at all in this context. Hope that clears up a few things. :)
