### ISSUE TITLE
Stuck in './cluster/kube-up.sh'

### ISSUE THREAD

**Issue by pfeodrippe** [deis/workflow#621]
I'm trying to make a cluster with ```./cluster/kube-up.sh``` at the AWS account of the place where I work and it's stuck at the s3 uploading part... do I have to setup something not in the docs yet (I am with admin permissions)? 

```
make_bucket: s3://kubernetes-staging-xxxxxxxxxxxxxxxxxxxxxx/
Confirming bucket was created...
+++ Staging server tars to S3 Storage: kubernetes-staging-xxxxxxxxxxxxxxxxxxxxxx/devel
upload: ../../../../../../var/folders/5p/bv03lbvj2ln_pxslx4ddgzw00000gn/T/kubernetes.XXXXXX.jAH5Bnkb/s3/bootstrap-script to s3://kubernetes-staging-xxxxxxxxxxxxxxxxxxxxxx/devel/bootstrap-script
upload: ../../../../../../var/folders/5p/bv03lbvj2ln_pxslx4ddgzw00000gn/T/kubernetes.XXXXXX.jAH5Bnkb/s3/kubernetes-salt.tar.gz to s3://kubernetes-staging-xxxxxxxxxxxxxxxxxxxxxx/devel/kubernetes-salt.tar.gz
Completed 2 of 46 part(s) with 1 file(s) remaining

```

And when I ```CTRL+C```, it stays forever at 
```

^CCleaning up. Please wait...
^C
^C
```

**Comment by kmala** [comment]
how long are you waiting for it to upload because the k8s distro is pretty big(~1GB) and takes time to upload depending on you connection speed.

**Comment by pfeodrippe** [comment]
@kmala I'll wait a bit longer (it could be more verbose), let me try...

**Comment by pfeodrippe** [comment]
@kmala Ok, the speed connection is very bad here, but it worked =), thanks!
