### ISSUE TITLE
Configure namespace creation

### ISSUE THREAD

**Issue by cdupont** [deis/workflow#627]
All deis apps create their own namespace.
This can clutter kubernetes namespaces quite quickly. 
Is it possible to configure deis to have the apps all in the same namespace, such as "deis-apps"?

**Comment by kmala** [comment]
ref https://github.com/deis/controller/issues/710

**Comment by bacongobbler** [comment]
Thanks @kmala. Closing this one as a duplicate so we can keep the conversation in one ticket.
