### ISSUE TITLE
helm upgrade results in jobs.batch "deis-upgrade" already exists

### ISSUE THREAD

**Issue by ged15** [deis/workflow#634]
Just installed Workflow 2.9 using helm, then wanted to tweak some values in `values.yaml`. To apply them I ran `helm upgrade -f values.yaml <release name> deis/workflow`, but the output was:

```
Fetched deis/workflow to workflow-v2.9.0.tgz
Error: UPGRADE FAILED: jobs.batch "deis-upgrade" already exists
```

When I look at the K8s dashboard, there is indeed a job named `deis-upgrade`, the pod says it was "successful" and the output from the pod's logs are:

```
2016-12-06T17:16:12.859733147Z deis-registry-proxy daemonset not found
2016-12-06T17:16:12.864244473Z pods for deis-logger-fluentd daemonset deleted successfuly
2016-12-06T17:16:12.869435021Z pods for deis-monitor-telegraf daemonset deleted successfuly
```

Am I wrong to use `helm upgrade` here? Or is there a bug?

If I manually delete the `deis-upgrade` job, I am able to apply the new values using `helm upgrade`.

**Comment by bacongobbler** [comment]
@ged15 how was the deis-upgrade job present on your cluster if you've never ran `helm upgrade` before?

It is correct to use `helm upgrade` here as far as I know. ping @kmala as he might know more information on this. If not then I can try to reproduce this myself.

**Comment by kmala** [comment]
yes...helm upgrade is correct thing to do...let me test it locally

**Comment by ged15** [comment]
@bacongobbler sorry, inaccurate description.
I actually ran `helm upgrade` and once it succeeded, then it failed the second time.

**Comment by mboersma** [comment]
I've run into the same problem trying to do `helm upgrade` twice after making minor changes to the Workflow v2.9.0 chart.
