### ISSUE TITLE
org/projet:latest exists in the target registry

### ISSUE THREAD

**Issue by laghoule** [deis/workflow#635]
deis pull org/projet:latest doesn't try to download latest build from docker hub.

EX:
INFO [projet-dev]: build projet-dev-2ca6aa9 created
INFO [projet-dev]: admin deployed org/projet:latest
INFO [projet-dev]: org/projet:latest exists in the target registry. Using image for release 23 of app projet-dev
INFO [projet-dev]: adding 50s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
INFO [projet-dev]: adding 50s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
INFO [projet-dev]: This deployments overall timeout is 170s - batch timout is 170s and there are 1 batches to deploy with a total of 1 pods

**Comment by draeron** [comment]
is there a way to force an update or delete the cached version of the image stored ?

**Comment by bacongobbler** [comment]
By default the application image pull policy is set to `IfNotPresent`. You can change this by editing the deployment object via `kubectl --namespace deis edit deployment deis-controller` and change the `IMAGE_PULL_POLICY` environment variable to `Always`.

**Comment by bacongobbler** [comment]
relevant docs: https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/#global-and-per-application-settings

**Comment by laghoule** [comment]
Thank you!
