### ISSUE TITLE
Error when reinstalling using helm

### ISSUE THREAD

**Issue by ged15** [deis/workflow#636]
I installed Workflow 2.9 using helm, then deleted it. Some pods were left behind, as expected. When I tried to install Workflow again on the same cluster, I got this error:

```
Fetched deis/workflow to workflow-v2.9.0.tgz
Error: secrets "logger-redis-creds" already exists
```

**Comment by rimusz** [comment]
just run 'kubectl delete namespace deis'

**Comment by ged15** [comment]
@rimusz `kubectl delete namespace deis` does indeed work. Is there a more elegant way to handle this? :)

**Comment by rimusz** [comment]
@kmala could answer it

**Comment by kmala** [comment]
currently that is the only way until https://github.com/kubernetes/helm/issues/1464

**Comment by ged15** [comment]
And what about reinstalling? Nuking the namespace is not an option for deployments that are already in production. Suppose somebody installs Workflow, deploys some apps using it, does a `helm delete` for some reason. All is good until trying to install it again.
Deleting the namespace means losing all apps running.
Helm Classic used to support reinstalling without downtime. Are there plans or ideas to support this with Helm? Or is that something that should never be done? :)

**Comment by kmala** [comment]
nuking the namespace was an option while the other option is to make helm delete everything it installed. `helm delete` deletes the router which means the apps are down. If you are talking about upgrading the workflow you can use `helm upgrade` which upgrades the workflow without any downtime for the apps and it is the preferred way for the production installs.
