### ISSUE TITLE
replace deis/registry-proxy with kube-registry-proxy

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#644]
Now that registry-proxy has been contributed upstream as a kubernetes addon, there is no need to maintain the chart/repo any more.

TODO:

 - [ ] contribute a kube-registry-proxy chart: https://github.com/kubernetes/charts/issues/285
 - [x] disable registry-proxy builds in CI
 - [ ] update workfow chart requirements to depend on new kube-registry-proxy chart

**Comment by bacongobbler** [comment]
chart available at https://github.com/kubernetes/charts/pull/286, just waiting on it to be merged to PR the update to our requirements

**Comment by bacongobbler** [comment]
pending work being done by a kube dev in https://github.com/kubernetes/kubernetes/issues/38843

**Comment by mboersma** [comment]
`docker pull docker pull gcr.io/google_containers/kube-registry-proxy:0.4` is working now. @bacongobbler is the remaining chart work ready to roll, or should we defer this to the next release?

**Comment by bacongobbler** [comment]
I think we need to defer for one more release.

**Comment by bacongobbler** [comment]
The kube-registry-proxy chart now exists in the kubernetes incubator chart.

```
><> helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
"incubator" has been added to your repositories
><> helm search registry
NAME                         	VERSION	DESCRIPTION
incubator/kube-registry-proxy	0.1.0  	Installs the kubernetes-registry-proxy cluster ...
```
