### ISSUE TITLE
nginx configuration invalid when hostname too long

### ISSUE THREAD

**Issue by ged15** [deis/workflow#659]
The platform domain in my Deis installation is set to a quite long hostname, so when somebody created an app with a 23 char length name it resulted in a hostname 48 chars long. This made nginx not reload:

```
Router configuration has changed in k8s.
Reloading nginx...
INFO: nginx reloaded.
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
```

**Comment by bacongobbler** [comment]
You can modify the `router.deis.io/nginx.serverNameHashBucketSize` to something larger. See https://github.com/deis/router#annotations

Will that work for you?

**Comment by ged15** [comment]
Somehow missed that setting :smile: Thanks @bacongobbler!
