### ISSUE TITLE
App name that starts with digit is invalid

### ISSUE THREAD

**Issue by landonclark** [deis/workflow#663]
I created an app like this `deis create 201612-demo`

I can see the app in Deis when using `deis apps:list`:
  === Apps
  20161215-demo

But Kubernetes doesn't like the digits so doesn't create the pods and deis can't delete the app. 

So there are two bugs:
1. Deis shouldn't allow an app to be created that starts with a digit
2. Deis can't delete an app that starts with a digit.

This is workflow 2.9.0 on k8s 1.4.5.

**Comment by bacongobbler** [comment]
This was fixed recently in master and will be in the v2.10 release: 

https://github.com/deis/controller/issues/1160
https://github.com/deis/controller/pull/1163

Both bugs are resolved by this. Workflow now doesn't allow an app to be created that starts with a digit, therefore Workflow doesn't need to delete apps that start with digits :)
