### ISSUE TITLE
Trouble adding application SSL

### ISSUE THREAD

**Issue by robinmonjo** [deis/workflow#665]
Hello,

I'm running deis v2.8.0, and try to add a SSL certificate to one of my app domain. I always end up with this error:

`````
$> deis certs:add app.mydomain.com ~/server.crt ~/server.key
Adding SSL endpoint... Error: Can only contain a-z (lowercase), 0-9 and hyphens
`````

I generated my certificate on startssl using this guide: https://about.gitlab.com/2016/06/24/secure-gitlab-pages-with-startssl/#step-by-step

I'm probably doing something wrong but can't figure out what.
Any help would be great.

Regards,
Robin

**Comment by bacongobbler** [comment]
The name of the certificate cannot contain dots. After adding it you can attach it to the domain via `deis certs:attach`.

**Comment by robinmonjo** [comment]
Thank you for your quick and helpful answer ! I was stupid :)
