### ISSUE TITLE
update http healthcheck docs on custom HTTP headers

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#666]
See https://github.com/deis/workflow-cli/issues/279#issuecomment-267631372

**Comment by felixbuenemann** [comment]
When I tried this there was also some confusion wether `X-Foo=bar` or `X-Foo:bar` should be used, because the tests use colon, but the docs use equals…

**Comment by bacongobbler** [comment]
That would be my fault. Sorry about that!
