### ISSUE TITLE
Current best practice for stateful containers

### ISSUE THREAD

**Issue by flux627** [deis/workflow#676]
I understand this technology is in constant flux, but I was wondering if there's any resources available showing the best practice for deploying stateful containers either using or alongside Workflow? The information I've found so far seems to be dated.

I'm also confused if I should be looking into Helm or Helm Classic, as the tutorials reference Classic but the repository warns that it is deprecated.

Anyone willing to help steer me in the right direction would be greatly appreciated.

**Comment by rimusz** [comment]
@flux627 yes, the recommended way for stateful apps is via Helm, check for example charts here https://github.com/kubernetes/charts/tree/master/stable/
e.g. mariadb one https://github.com/kubernetes/charts/tree/master/stable/mariadb

**Comment by flux627** [comment]
Thank you @rimusz, for some reason I was only finding the charts under `deis/`.
