### ISSUE TITLE
Allow to define admin credentials right inside values.yaml

### ISSUE THREAD

**Issue by sheerun** [deis/workflow#702]
Hey,

I've deployed deis to production and unfortunately:

1. I needed to set `registration_mode: "enabled"` when deploying deis first time, so I could create first admin account. I needed then re-deploy deis with `registration_mode: "admin_only"`, to prevent random people registering. I'd argue my flow is the most common one, so ideally, I could set `registration_mode: "admin_only"` and allow deis to create default admin account for me with the credentials from `values.yaml`
2. By default user credentials for grafana are `admin:admin`.. When deploying first time, one needs to log-in and change its password (and on top, disable signing-up to grafana as mentioned in deis/monitor#171). Ideally I would be able the specify credentials different than admin:admin directly inside values.yaml

So here's what I'm asking for:

Please allow for specifying default admin credentials for controller and grafana in values.yaml, e.g.

```
default_admin_credentials:
  username: admin
  password: admin
```

and default `registration_mode` to `admin_only`

**Comment by bacongobbler** [comment]
The former is possible, but we cannot do the latter due to backwards compatibility. People have come to expect the open registration as a default for the v2 timeline, so we cannot change it.

However, I believe there was a PR a few releases ago that allows you to still register the first account when admin_only is enabled. I'm on mobile so I can't find it at the moment.

**Comment by bacongobbler** [comment]
https://github.com/deis/controller/pull/1116 is the PR I'm referencing, which has been available since v2.8.0. Will that work for you?

**Comment by bacongobbler** [comment]
> and default registration_mode to admin_only

We have already discussed this in https://github.com/deis/controller/issues/950, and we're not changing defaults in the v2 timeline.

**Comment by bacongobbler** [comment]
Default admin credentials can be changed via

```
monitor:
    grafana:
        user: myuser
        password: mypass
```

Hope this helps!
