### ISSUE TITLE
Creating a new cluster deis workflow 2.10.0 - S3 storage using iam permissions fails.

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#712]
(K8s 1.4.8)
I update the storage and S3 section with `helm inspect values deis/workflow | sed -n '1!p' > deis-values.yaml` and use the updated file to start my cluster.
S3 permissions errors when starting

registry:
```bash
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId></AWSAccessKeyId><RequestId>1671A70DD29DC9DC</RequestId><HostId>0swvmNcpCG3jwdTDDxJVLb7rtYdNda3mDC5zSXD726liYjFeKMpTN+11nvGM8GUPi78sOgAGiqg=</HostId></Error>
```
database:
```bash
server started
wal_e.main   ERROR    MSG: AWS Access Key credential is required but not provided
        HINT: Pass "--aws-access-key-id" or set the environment variable "AWS_ACCESS_KEY_ID".
        STRUCTURED: time=2017-01-23T23:27:19.399328-00 pid=101
```
I have been using the s3 permissions successfully with helmc installs with deis-workflow 2.x since June 2016. 
I am able to run s3 queries with the aws cli on the kubernetes nodes hosting the two failing deis components.

**Comment by bacongobbler** [comment]
closed via deis/postgres#186

**Comment by jwalters-gpsw** [comment]
Actually, I'm still getting this with the latest 2.13.

**Comment by bacongobbler** [comment]
can you file a report over at deis/postgres along with your logs and a sample values.yaml and the output of `kubectl -n deis get po <my-postgres-pod> -o yaml` so we can take a look? Thanks.
