### ISSUE TITLE
`deis pull` doesn't respect `cmd` in a Docker image.

### ISSUE THREAD

**Issue by monaka** [deis/workflow#720]
(I'm not sure which component causes this. So I create this issue for now. I'll move this issue to another repository you contributors specified)

### How to reproduce:

In this case, I use deis-registry as the local repository.

```
$ deis create --no-remote
Creating Application... done, created zigzag-teamwork
If you want to add a git remote for this app later, use `deis git:remote -a zigzag-teamwork`
$ deis pull monami0ya/deis-pgweb -a zigzag-teamwork
Creating build... done
$ deis ps -a zigzag-teamwork
=== zigzag-teamwork Processes
--- web:
zigzag-teamwork-web-3921211065-dqhrb error (v2)
$ kubectl logs --namespace=zigzag-teamwork zigzag-teamwork-web-3921211065-dqhrb
/bin/bash: bundle: command not found

$ sudo docker inspect --format='{{.Config.Cmd}}' monami0ya/deis-pgweb
[/usr/bin/pgweb --bind=0.0.0.0 --listen=8081]
$ sudo docker inspect --format='{{.Config.ExposedPorts}}' monami0ya/deis-pgweb
map[8081/tcp:{}]
```

The part of result from `kubectl get deployment --namespace=zigzag-teamwork zigzag-teamwork-web -o yaml`

```
                "containers": [
                    {
                        "name": "zigzag-teamwork-web",
                        "image": "172.17.0.191:80/zigzag-teamwork:v2",
                        "command": [
                            "/bin/bash",
                            "-c"
                        ],
                        "args": [
                            "bundle exec unicorn_rails -p $PORT -c ./config/unicorn.rb"
                        ],
```

### versions

```
$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                 
punk-alpaca     1               Wed Dec 28 05:56:25 2016        DEPLOYED        workflow-v2.9.1
$ deis version
v2.9.1-3e324ea
```

**Comment by monaka** [comment]
I guess pulled Docker images should be assigned to `cmd` isntead of `web`.

And in the another case, I deployed phpMyAdmin into same Workflow with success.
So possibly pulls will be failed in particular cases.

**Comment by monaka** [comment]
And one more. I disabled using repository-proxy to avoid https://github.com/deis/registry/issues/64 .
(I'm not sure if this causes side effects)

**Comment by monaka** [comment]
Gotcha.

`deis pull` works collect after applying patch [like this](https://github.com/monami-ya/deis-pgweb/commit/4c5ecda359a2a3452b0252ce004b448ed748caec#diff-3254677a7917c6c01f55212f86c57fbf) and rebuilding.

Looks some issues are available in code or [description in the doc](https://deis.com/docs/workflow/applications/using-docker-images/#docker-image-requirements).

```
$ deis create delme
(snip)
$ deis pull monami0ya/deis-pgweb -a delme
Creating build... done
$ deis ps -a delme
=== delme Processes
--- cmd:
delme-cmd-2899816377-z1z93 up (v2)
$ kubectl logs --namespace=delme delme-cmd-2899816377-z1z93 
Pgweb v0.9.6 (git: b580b2456ad4c766bfc93fd19cff0c8f904a0999)
Starting server...
To view database open http://0.0.0.0:8081/ in browser
```

**Comment by bacongobbler** [comment]
thanks for the report @monaka. SOrry this one fell through the cracks, but glad you got it all working again!
