### ISSUE TITLE
Configuring GIT_LOCK_TIMEOUT with helm

### ISSUE THREAD

**Issue by robinmonjo** [deis/workflow#724]
Hello all,

I've been using deis 2.8 and installed it with helmc. I used to generate my manifests and configure Object Storage this way:

````
STORAGE_TYPE=s3 AWS_BUILDER_BUCKET=some_bucket AWS_DATABASE_BUCKET=some_bucket AWS_REGISTRY_BUCKET=some_bucket S3_REGION=eu-west-1 helmc generate -x manifests workflow-$DEIS_VERSION
````

Then I edited the file `~/.helmc/workspace/charts/workflow-$DEIS_VERSION/manifests/deis-builder-deployment.yaml` and set `GIT_LOCK_TIMEOUT` to 60.

If I don't do this, I can't push big app that take a while to compile (push rejected, ssh connection closed).

Now that deis uses `helm` (and not `helmc`), I see how I can configure the Object Storage (it's documented) however I have no idea how to edit the GIT_LOCK_TIMEOUT.

Regards,
Robin

**Comment by bacongobbler** [comment]
The easiest way would be to fetch the chart locally and edit the builder deployment manifest directly like you would with helm-classic. To do that, run

```
helm fetch deis/workflow --untar
vim workflow/charts/builder/templates/deis-builder-deployment.yaml
helm install ./workflow --namespace deis
```

Hope this helps!

**Comment by robinmonjo** [comment]
Thank you very much, I was confused by how `helm` differs from `helmc` (with the server side aspect). I ran `helm init --client-only` and got less confused. I can now do what you suggest and everything should work fine :+1:
