### ISSUE TITLE
missing documentation: configure environment variables for components

### ISSUE THREAD

**Issue by nathansamson** [deis/workflow#726]
The page https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/ mentions that you can configure components by editing environment variables.

It mentions

> To customize the respective component, edit values.yaml and modify the section of the component to tune these settings.

And also mentions a list of environment variables for the different components

It fails to explain where these environment variables can be defined. I assume not just in
`router:
   ENV_VARIABLE: value`

but it is anyone's guess..

It also fails to explain how to update an existng installation. I assume this is just following the update procedure, but it is not explictly mentionned as far as I can see.

**Comment by chexxor** [comment]
I also had that question last week. I found this command worked for customizing the controller's env vars.

`kubectl -n deis edit deploy/deis-controller`

Does this solve your problem? If so, I can make a PR to add this to docs.

**Comment by nathansamson** [comment]
I guess that does not persist when you reinstall your k8s cluster and reinstall workflow via helm.

Ideally I want the values to be stored in the values.yml file or similar

**Comment by bacongobbler** [comment]
If you fetch the chart down locally, you can edit the manifests as well. See https://github.com/deis/workflow/issues/724

We could probably add that to the documentation.

**Comment by nathansamson** [comment]
~~~
[nathan@zeta beepleapp]$ kubectl --namespace deis edit deploy/deis-controller
the server doesn't have a resource type "deploy"
[nathan@zeta beepleapp]$ 
~~~

Something I am doing wrong?

Also my point stays that dies probably does not persist if I deploy a newer version of workflow?

**Comment by vdice** [comment]
@nathansamson re: first question, command should read: `kubectl --namespace deis edit deploy deis-controller` (no forward slash between deploy and deis-controller)

> Also my point stays that this probably does not persist if I deploy a newer version of workflow?

I did run a trivial exercise of adding
```
- name: FOO
  value: "bar"
```
under the `env` section of the `deis-controller` deployment and this value did persist after a Workflow upgrade (`helm upgrade <release> workflow/workflow`)
```
$ kubectl --namespace deis exec -it deis-controller-1613669790-7tkjf env | grep FOO
FOO=bar
```
Though not sure if this example covers all bases...

**Comment by nathansamson** [comment]
The right command seems to be
~~~
kubectl --namespace deis edit deployments deis-controller
~~~

**Comment by bacongobbler** [comment]
I think we've cleared this all up in the docs now with `helm fetch` and/or `kubectl edit`. Closing!
