### ISSUE TITLE
Components should all ship with memory and CPU limits

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#738]
As a good Kubernetes citizen, Workflow should ship with reasonable memory and cpu limits for all components.

- Discover real-world baseline requirements
- Add limits to charts and allow operator override via generate_params.toml

**Comment by bacongobbler** [comment]
We have commented-out resource values in values.yaml now. Is that considered OK to close out this ticket?

**Comment by dmcnaught** [comment]
Which version is that in @bacongobbler ? Thanks

**Comment by bacongobbler** [comment]
They've been there since the migration to helm, it's just not in the global values.yaml. See https://github.com/deis/registry/blob/master/charts/registry/values.yaml for example

**Comment by dmcnaught** [comment]
Ah - I was looking in the global values.yaml after your comment. Thanks

**Comment by dmcnaught** [comment]
Is there a simple way to get deis to use those values during installation/upgrade? Is that documented? Thanks

**Comment by bacongobbler** [comment]
Yes. Either set it under the component of your choice in values.yaml:

```
registry:
    limits_cpu: 100m
```

 or use `--set registry.limits_cpu=100m` when running `helm install`. This is documented via https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/#setting-resource-limits, which looks like it wasn't updated from toml to yaml. I'll fix that.

**Comment by bacongobbler** [comment]
closing as we have documentation on how to get this set up now.
