### ISSUE TITLE
`deis addons` command should work with k8s service brokers

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#741]
Developers should be able to list, provision and deprovision services available to them through the deis workflow cli. This is forward-looking, anticipating a service broker implementation that eventually comes out of k8s sig-service-catalog efforts, or [steward](https://github.com/deis/steward).

This could be implemented as a deis CLI plugin, if we want to keep things decoupled or vendor-neutral.

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/workflow#34
