### ISSUE TITLE
Using exec readiness probe, app doesn't become ready (deis workflow 2.11.0, k8s 1.5.2)

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#743]
Steps to reproduce:
```bash
deis create test --no-remote
deis healthchecks:set liveness exec '/bin/ls /var/log/nginx/error.log' -a test
deis healthchecks:set readiness exec '/bin/ls /var/log/nginx/error.log' -a test
deis pull tutum/hello-world -a test
```
output:
```bash
Creating build... Error: Unknown Error (400): {"detail":"(app::deploy): Liveness probe failed: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/bin/ls /var/log/nginx/error.log\\\\\\\": stat /bin/ls /var/log/nginx/error.log: no such file or directory\\\"\
\"
"}
```
command works fine manually when app is starting up:
```bash
--- kubernetes/test ‹master* M?› » ku -n test exec -ti test-cmd-534060287-dwfvb /bin/ls /var/log/nginx/error.log
/var/log/nginx/error.log
```
I've tried with other commands like `echo`, and `cat` too...
Also tried with my app first, but this test app is much simpler.
I also tried changing the settings in the deployment, with no success:
```bash
        readinessProbe:
            exec:
              command:
              - /bin/ls /var/log/nginx/error.log
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 50
```

**Comment by vdice** [comment]
I'm able to reproduce this as well (same Workflow/k8s versions, running on minikube)

**Comment by mboersma** [comment]
I can also reproduce this but can't see why this is an error. i can see the log file inside the container.

Setting only the livenessProbe seems to cause no errors.

**Comment by dmcnaught** [comment]
If you set just the liveness probe then there has to be a port for readiness? My use case for this is a silent worker that doesn't expose a port at all...

**Comment by dmcnaught** [comment]
Actually with just the liveness probe configured, the app does seem to get to Ready status ok...

**Comment by dmcnaught** [comment]
with a silent worker (no exposed port and no readiness probe) the pod seems to get killed and restarted every couple of minutes: `container "containername" is unhealthy, it will be killed and re-created.`

**Comment by dmcnaught** [comment]
Any update on this issue @mboersma ? Is a fix still projected for 2.12? We have a project waiting on this.

**Comment by monaka** [comment]
I tested now on workflow-v2.11.0, Kubelet v1.5.3_coreos.0, CoreOS 1339.0.0 (means Docker 1.13.1).
I got same result as @dmcnaught 's.

And I did `kubectl describe po`
```
$ kubectl get po  --namespace test
NAME                        READY     STATUS             RESTARTS   AGE
test-cmd-2926644209-td1nd   0/1       CrashLoopBackOff   6          10m
```
```
$ kubectl describe po --namespace=test test-cmd-2926644209-td1nd
Name:           test-cmd-2926644209-td1nd
{snip}
container_linux.go:247: starting container process caused "exec: \"/bin/ls /var/log/ngnix/error.log\": stat /bin/ls /var/log/ngnix/error.log: no such file or directory"
{snip}
$
```

@mboersma, Guess K8s trying execute "/bin/ls /var/log/ngnix/error.log\" instead of "/bin/ls" ???

**Comment by vdice** [comment]
> Guess K8s is trying execute "/bin/ls /var/log/ngnix/error.log" instead of "/bin/ls" ???

Ah great guess - appears the command sent to kubectl is erroneously wrapped in quotes?

**Comment by bacongobbler** [comment]
I believe the correct format for `deis healthchecks:set` in this case would be:

```
deis healthchecks:set -a test liveness exec -- /bin/ls /var/log/nginx/error.log
```

Wrapping the command in single quotes is making the CLI interpret that as a single argument.

```
Usage: deis healthchecks:set <health-type> <probe-type> [options] [--] <args>...
```

I'll see if I can verify that.

**Comment by dmcnaught** [comment]
Ah! I'll try that out this afternoon. Thanks

**Comment by bacongobbler** [comment]
The following worked for me using example-dockerfile-http:

```
><> deis healthchecks:set liveness exec /bin/ls /usr/share/nginx/html/index.html
```

liveness probe output:

```
    livenessProbe:
      exec:
        command:
        - /bin/ls
        - /usr/share/nginx/html/index.html
      failureThreshold: 3
      initialDelaySeconds: 50
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 50
```

**Comment by bacongobbler** [comment]
And wrapping it in single quotes did indeed replicate the same behaviour, which is to be expected:

```
><> deis healthchecks:set liveness exec '/bin/ls /usr/share/nginx/html/index.html'
```

```
    livenessProbe:
      exec:
        command:
        - /bin/ls /usr/share/nginx/html/index.html
      failureThreshold: 3
      initialDelaySeconds: 50
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 50
```

**Comment by dmcnaught** [comment]
Great - it's working for me. I'm a little :embarrassed: that I didn't format the command correctly. and glad it's an easy fix. Thanks @bacongobbler
