### ISSUE TITLE
Automatic restart of all pods

### ISSUE THREAD

**Issue by nathansamson** [deis/workflow#744]
Yesterday all of my pods restarted, but all of them at different times (although a few moments appear a few times, so they are grouped a bit)

Is their a bultin "restart after X amount of time running" built in? Or was there a deeper issue running in my cluster?

I don't see any special events when I inspect the pods

Any suggestions on how I can debug this?

**Comment by bacongobbler** [comment]
that sounds like a deeper issue with your cluster. There is no restart after X time built in.

**Comment by bacongobbler** [comment]
the only doc we have is https://deis.com/docs/workflow/troubleshooting/kubectl/. I'd suggest looking at the kubelets themselves or the master API and see what's up there.

**Comment by nathansamson** [comment]
Not sure what happened.

Around the time the isuse started I see a slightly increased disk usage in my monitoring on the k8s master (it stayed at a certain level for a few days, but higher than it was before), Then it spiked, rebooted the hosts (both the master and the workers) and then everything seems to be gone to normal again...

Will monitor again if this happens again

**Comment by nathansamson** [comment]
I will close this issue as I assumme nothing is to be done here (unless it is because of a bug in a workflow component that the system went haywire)
