### ISSUE TITLE
create legacy-v1 branch upstream

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#75]
Before we merge this back into deis/deis, we need to keep a branch for v1 so we can continue work on a LTS release of Deis.

**Comment by rimusz** [comment]
+1, plus we should have separate channels in slack too.

**Comment by mboersma** [comment]
This is already being done in the [version-one](https://github.com/deis/workflow/tree/version-one) branch of deis/workflow. And it's not clear that this necessarily merges back into deis/deis yet, although I think that's the likely end-game.

**Comment by helgi** [comment]
Looks like this is being taken care of already
