### ISSUE TITLE
Customizing Workflow?

### ISSUE THREAD

**Issue by krancour** [deis/workflow#75]
In the "Customizing Workflow" section, we currently have very little-- just a tiny bit about CLI plugins.

Formerly, we had _extensive_ documentation on how each component could be customized.  I think given the complexity of some components, including all of that here might be way overkill.

I would, however, propose that we expand this section two include two things:

1.  Links to component-specific documentation for those who really do want to dig down and tweak things.
2.  A very brief tutorial on customizing Workflow's Helm chart.

**Comment by bacongobbler** [comment]
tagging as something that needs to be done for the stable release, as right now there's no documentation for users migrating from v1 to disable user registration mode, for example.

**Comment by bacongobbler** [comment]
I've started to lay down some of the groundwork in #139 but we need to add tunable settings for the other components as well.

**Comment by arschles** [comment]
doesn't https://github.com/deis/workflow/pull/141 also have some customization information?

**Comment by arschles** [comment]
punting to beta4

**Comment by bacongobbler** [comment]
#141 is different, but it references #139

**Comment by jchauncey** [comment]
moving to rc1
