### ISSUE TITLE
cpu/mem requests and limits not getting through to K8s with Docker Image Apps (K8s 1.5.2, deis 2.11.0)

### ISSUE THREAD

**Issue by dmcnaught** [deis/workflow#752]
I have set limits on my deis apps, but the settings don't seem to get through to K8s:
```bash
--- kubernetes/graphql ‹master› » deis limits -a athena-graphql
=== athena-graphql Limits

--- Memory
web     100M

--- CPU
web     50m
```
`ku describe no` that the pod is on (some lines removed).
```bash
  Namespace			Name							CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----							------------	----------	---------------	-------------
  athena-graphql		athena-graphql-cmd-4184045482-k0x6g			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-builder-193588232-mp0cz				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-controller-2434209242-7dn0g			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-logger-176328999-bhgkp				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-logger-fluentd-l4c4j				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-monitor-influxdb-2729657543-tgrjs			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-monitor-telegraf-x59h5				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-nsqd-3597503299-2mhcf				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  deis				deis-router-3101872284-3ms54				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-dns-782804071-hjf6m				260m (13%)	0 (0%)		140Mi (1%)	220Mi (2%)
  kube-system			kube-proxy-ip-10-101-35-149.ec2.internal		100m (5%)	0 (0%)		0 (0%)		0 (0%)
  wellbot			wellbot-web-2518992024-scm6x				100m (5%)	100m (5%)	250Mi (3%)	250Mi (3%)
```

wellbot is a deis app deployed from a Buildpack - and it has worked for that deis app, so it looks like it's not working for the docker images pulled from Quay...

**Comment by bacongobbler** [comment]
I was not able to replicate this locally:

```
><> deis limits:set --cpu cmd=500m
Applying limits... done

=== go Limits

--- Memory
Unlimited

--- CPU
cmd     500m
```

And in the pod:

```
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
```

Are there any logs in the controller to help support what is happening?

**Comment by dmcnaught** [comment]
ok - thanks for checking on that. I'll remove/redefine and see if the controller logs give any clues and update this issue.

**Comment by dmcnaught** [comment]
I was setting the limits for web, not cmd. Thanks @bacongobbler 😄

**Comment by dmcnaught** [comment]
Should the deis app still redeploy if we change process types that aren't running?

**Comment by bacongobbler** [comment]
It requires changing the deployment manifests so Kubernetes will re-deploy with the new changes, yes.

**Comment by bacongobbler** [comment]
Sorry, I misread that. I still believe answer should still be yes though. Anything related to application config requires a re-deploy. The controller is already a labyrinth of edge cases: making it a yes/no on changing certain resources causing an application deployment greatly simplifies maintenance of the controller.
