### ISSUE TITLE
How i use workflow on digitalocean ? 

### ISSUE THREAD

**Issue by Ima8** [deis/workflow#774]
How i use workflow on digitalocean ? 

Thank you.

**Comment by bacongobbler** [comment]
Hey @Ima8! I know there are third party services providing assistance with standing up a Kubernetes cluster on Digital Ocean like https://stackpoint.io/. @scottrobertson do you have any advice for that?

After installing Kubernetes on there, you can follow through with the [Installing Workflow](https://deis.com/docs/workflow/installing-workflow/) doc to bootstrap Workflow on top of your cluster.

Hope this helps!

**Comment by scottrobertson** [comment]
Hey hey

Yeah it works perfectly :) there is an option to install Deis on there, but don't use it as it's out of date. 

Just let it install and then run helm install deis/workflow. 

I then use a digital ocean load balancer to forward port 80 to the deis-router port. Same with the git port etc. 

On my phone at the moment, but let me know if you need some help and i can write something up when i get home.

**Comment by kris-nova** [comment]
I am pushing for Digital Ocean support for `kops` right now.. If you are interested in that could you please give the issue a +1, or better yet a comment on how you would use it or why you think it's a good idea.

If it gets enough attention I will probably starting driving the feature and eventually code it 😄 

https://github.com/kubernetes/kops/issues/2150

**Comment by Ima8** [comment]
Thank you guys .
