### ISSUE TITLE
docs: Tell user to set the `--namespace=deis` flag

### ISSUE THREAD

**Issue by technosophos** [deis/workflow#80]
The most likely workflow for a new user will be that their namespace is set to be `default`. So we need to make sure that the install works fine even so.

That means we need to do:

```
$ helm install --namespace=deis deis/deis
```

(Alternate config instructions could suggest that they do this with `kubectl` itself)

Currently, the installation workflow will fail without the `--namespace`.

**Comment by arschles** [comment]
@technosophos I've been able to `helm install` without the flag. later `kubectl --namespace=deis ...` commands work as expected

**Comment by mboersma** [comment]
@arschles me too, but now I think I've effectively worked around this issue by putting my `kubectl` in the "deis" namespace by default.

**Comment by arschles** [comment]
@mboersma got it. I was confused by the `--namespace=deis` flag on `helm`. Is that a valid flag? I don't see it listed under `helm help`

**Comment by mboersma** [comment]
My `helm` has a `--namespace` flag for `install`. I just built it from source at HEAD recently--maybe it's a newish flag?

**Comment by technosophos** [comment]
I should have been more explicit about the error conditions:

```
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.245.1.2
  name: vagrant
contexts:
- context:
    cluster: vagrant
    namespace: deis
    user: vagrant
  name: deis-dev
- context:
    cluster: vagrant
    user: vagrant
  name: vagrant
current-context: vagrant
kind: Config
preferences: {}
users:
- name: vagrant
  user: ...
```

Note that since there is no `namespace` set for `vagrant`, I am in namespace:default

Now if I do `helm --debug install deis/deis` I get this: https://gist.github.com/technosophos/9d5ebda491141eaf3475#installing-the-deis-platform

**Comment by arschles** [comment]
@mboersma didn't realize it was under `install`. thanks for clarifying

**Comment by krancour** [comment]
I thought the manifests in the chart are already ensuring the existence of the deis namespace and then puts eveything else in it with `metadata.namespace: deis`

**Comment by technosophos** [comment]
After more investigation, I discovered that the issue is actually with an older version of `kubectl`. The >= 1.1.2 kubectls seem to be just fine. (The previously tested version reported itself as 0.16)
