### ISSUE TITLE
`deis info` produces a 404 error

### ISSUE THREAD

**Issue by arschles** [deis/workflow#82]
Using a client built last Friday (12/11/2015) from `HEAD` of `master`,

```console
core@micro-kube ~/example-go $ ./deis --version
1.13.0-dev
core@micro-kube ~/example-go $ ./deis info
Error: 
404 NOT FOUND
detail: Not found
```

@bacongobbler since you have #71 open and it's marked under the `v2.0-alpha1` milestone, I've marked this issue as such as well. I have't tested with a client uploaded by the CI setup in your PR, however.

If you can give me such a client, I'll re-test.

**Comment by bacongobbler** [comment]
@arschles https://s3-us-west-1.amazonaws.com/bacongobbler/bacongobbler/workflow/19/19.1/client/deis should give you a v2 client from my testing last week

**Comment by bacongobbler** [comment]
`deis info` is supposed to return a 404 unless you're pointing it at an app, btw. Did you try it with the --app flag as well?

**Comment by arschles** [comment]
@bacongobbler :facepalm: I forgot the --app flag. closing this.

also, thanks for the s3 link. I'll be using until official ones go up.
