### ISSUE TITLE
People using Alea want Deis socks as well

### ISSUE THREAD

**Issue by foxycoder** [deis/workflow#831]
Just passing along the message here. Reported at Codaisseur/alea#17 initially, but seems like a Deis issue, really.

I think the cause of this might be this picture in the [Alea](https://github.com/Codaisseur/alea) README:

[![](http://cd.sseu.re/Cksa06GXIAA7cDa.jpg)](https://github.com/Codaisseur/alea/blob/master/README.md)

👞 👡 👟 👠 

Have a great weekend!

**Comment by squillace** [comment]
Let's see what can be done here. :-) @slack

**Comment by squillace** [comment]
So, if we MANAGED TO LOCATE a remaining pair, @foxycoder, what would we do? @karenchu

**Comment by Cryptophobia** [comment]
@squillace : You can send some directly to me. I can give you our address. They would be very useful for our "socks compliance." 😀

**Comment by karenhchu** [comment]
email me a mailing address at karen.chu@microsoft.com :D
