### ISSUE TITLE
helm install fails

### ISSUE THREAD

**Issue by UlTriX** [deis/workflow#868]
Trying to install on minikube

helm install hephy/workflow --namespace deis --set global.use_rbac=true,router.host_port.enabled=true

returns 

Error: must either provide a name or specify --generate-name

Adding the --generate-name

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]

deis v2.20.0
kubectl
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
helm version
.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Comment by bacongobbler** [comment]
Hi @UlTriX. This project is no longer being maintained as of 2 years ago. Have a look at https://github.com/teamhephy/workflow for a community-maintained fork. Thanks!
