### ISSUE TITLE
dockerbuilder is missing from the object storage docs

### ISSUE THREAD

**Issue by arschles** [deis/workflow#94]
Dockerbuilder uses object storage, so it should be added to https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials

**Comment by smothiki** [comment]
@arschles Can you be more specific about docs. I don't think dockerfile builder requires any additional docs

**Comment by arschles** [comment]
@smothiki you're right, closing

In case you're interested, this issue was opened when there was an exhaustive list of _all_ the workflow components that used object storage, and the dockerbuilder component wasn't in the list. Now that such a list doesn't exist, and the dockerbuilder is mentioned under ["Component Details"](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#component-details), this issue is obsolete.
