### ISSUE TITLE
migrate client builds to bintray

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow#94]
Travis artifacts is great for creating builds and uploading to S3, but one thing it misses on is the ability to grab the "latest" build (as seen in the README). In order for a user to grab the latest client build, he or she must know the latest Travis build that went green and download the client using that URL.

@sgoings fronted the work with releasing the [helm](https://github.com/helm/helm) client on [bintray](https://bintray.com/) which so far has been a great success, so perhaps we should move over to bintray for that one-liner (`curl https://... | sh`) special sauce.

**Comment by bacongobbler** [comment]
this is even moreso important because travis artifacts will only generate a linux client. That's great for testing on the k8s machines themselves, but not on a local cluster.

**Comment by sgoings** [comment]
I wholeheartedly approve of this direction. :smile: Extra points if the publishing logic can be placed in a makeup kit similar to: https://github.com/sgoings/makeup-kit-go-cli

**Comment by jchauncey** [comment]
alright for the time being should we build the client locally? I keep getting this error when downloading from travis - 

```
╰─○ ./deis
zsh: exec format error: ./deis
```

**Comment by bacongobbler** [comment]
@jchauncey yes, that's because travis only compiles linux binaries. You'll have to build it locally for now.

**Comment by helgi** [comment]
Already happened in https://github.com/deis/workflow/commit/35abd9d4b60fe4b78513b090491c7a3b1f4af193

**Comment by helgi** [comment]
Open up a diff ticket if you want to generate more than just linux clients :)
