### ISSUE TITLE
[meta] all components should report their 2.0.x version string

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#97]
In Deis v1.x each component has an `ENV DEIS_RELEASE v1.x` string in its Dockerfile. That was a workaround that may no longer be needed, and requires lots of clerical PRs just to update strings. In Deis v2.x it would be preferable for each component to print its version up-front, on startup.

**Comment by arschles** [comment]
@mboersma should the versions be `2.0.0`?

**Comment by mboersma** [comment]
In workflow we bumped the `deis` client to `2.0.0-dev`. But that's probably not specific enough at this point--it will be more useful to have `2.0.0-beta1` or something similar that contains the pre-release version. (And maybe the git SHA?) And since printing such a version up-front will require changes to components, it's not in scope for alpha.

**Comment by arschles** [comment]
@mboersma I see. I opened a few PRs that I'll leave open for now, without an alpha milestone

**Comment by helgi** [comment]
@mboersma Can we start opening up tickets for the components that are missing and fix up the version strings as needed?

**Comment by helgi** [comment]
@mboersma says this isn't needed anymore
