### ISSUE TITLE
Update component descriptions at Docker Hub and quay.io

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#98]
As part of the Deis v2 release process, designated registry images will move from the deis to deisci organization, and be re-tagged: e.g. `quay.io/deis/controller:v2.0.0-beta1`.

Each component's repository web page shows a "Description" field as documentation, for example https://quay.io/repository/deis/controller. These were originally seeded from project README.md files when Deis used Docker Hub for automated builds, but now they must be manually updated and have gone stale.

These description fields need to be updated as be component landing pages, since they will contain registry tags from (at least) `v1.9.0` through `v2.0.0` and onward.

**Comment by bacongobbler** [comment]
Funny enough, quay.io descriptions don't support github markdown backticks. I say we just make the descriptions dead simple:

# deis/router

See https://github.com/deis/router

**Comment by bacongobbler** [comment]
done!
